import type { FamilyCuration } from './types';
import { SOCIAL_PROFILE_WAVE_2_IDS } from '../SocialProfileExtended2';

/**
 * Owned by the social family. Names, archived ids and tags — nothing else.
 *
 * Four cards, one system: Profile · Cover · Post · Story. Between them the
 * family shipped 176 variants and offered every one. What was culled, and
 * why:
 *
 *   • **The legacy 38** (`instagram-posts-1` … `-10`, `instagram-stories-1`
 *     … `-8`, `facebook-covers-1` … `-8`, `profile-icons-1` … `-12`) were
 *     eight square posts, five stories and four covers shown on repeat by
 *     `SocialMediaRenderer`'s `idx % posts.length`, plus twelve profile
 *     icons from `ProfileIconRenderer`. Every one of them advertised a
 *     fintech company nobody here owns — "94% of our users report improved
 *     financial clarity", "$2.4B processed this quarter", "Join the team
 *     building the future of finance", a testimonial from a CFO at
 *     TechCorp. They reach the artwork through `renderTemplateDesign`,
 *     which carries no content, so not one word of it could ever be
 *     edited. (The two legacy renderers now delegate to the curated
 *     designs, so anything still holding a legacy id paints the brand's
 *     own work rather than that company's.)
 *   • **All 100 of the profile wave 2** (`profile-icons-ext-25` …
 *     `-ext-118`, and the six that were kept, renamed) were generated by
 *     movement — fifteen "Apple-restrained", fifteen "Brutalist", fifteen
 *     "Swiss" — named by their loop index ("Wave 2 · 43"), painted on
 *     off-brand grounds (`#FFEB3B`, `#FF3B30`, `#39FF14`), and welded to
 *     `Caveat, cursive` and Tailwind's `font-serif`/`font-mono`. Six of
 *     them survive as real designs in `SocialProfileExtended.tsx`; the
 *     other 94 are archived. See `SocialProfileExtended2.tsx`.
 *   • **`instagram-posts-ext-17` … `-ext-20`**, **`instagram-stories-ext-17`
 *     … `-ext-22`** and **`facebook-covers-ext-13` … `-ext-22`** never
 *     existed as ids beyond the arrays that named them; the rewritten
 *     families declare sixteen, sixteen and twelve and nothing more, so
 *     there is nothing to archive there.
 *
 * Archiving, not deleting: every id above stays a valid persistence key, so
 * a customer who saved a customization against one still has it, and the
 * `-ext-N` → design index arithmetic in each renderer is untouched.
 */

const legacy = (type: string, count: number) =>
  Array.from({ length: count }, (_, i) => `${type}-${i + 1}`);

export const curation: FamilyCuration = {
  archived: [
    ...legacy('instagram-posts', 10),
    ...legacy('instagram-stories', 8),
    ...legacy('facebook-covers', 8),
    ...legacy('profile-icons', 12),
    ...SOCIAL_PROFILE_WAVE_2_IDS,
  ],

  names: {
    /* ── Post — 1:1 ─────────────────────────────────────────────── */
    'instagram-posts-ext-1': 'Statement',
    'instagram-posts-ext-2': 'Pull Quote',
    'instagram-posts-ext-3': 'Split Deck',
    'instagram-posts-ext-4': 'Header Band',
    'instagram-posts-ext-5': 'Ruled Frame',
    'instagram-posts-ext-6': 'Night Offer',
    'instagram-posts-ext-7': 'Editorial',
    'instagram-posts-ext-8': 'Corner Mark',
    'instagram-posts-ext-9': 'Centre Stage',
    'instagram-posts-ext-10': 'Season Ribbon',
    'instagram-posts-ext-11': 'Underline',
    'instagram-posts-ext-12': 'Inset Card',
    'instagram-posts-ext-13': 'Tile Field',
    'instagram-posts-ext-14': 'Accent Bar',
    'instagram-posts-ext-15': 'Quiet Page',
    'instagram-posts-ext-16': 'Footer Bar',

    /* ── Story — 9:16 ───────────────────────────────────────────── */
    'instagram-stories-ext-1': 'Tall Statement',
    'instagram-stories-ext-2': 'Story Quote',
    'instagram-stories-ext-3': 'Third Split',
    'instagram-stories-ext-4': 'Top Chrome',
    'instagram-stories-ext-5': 'Tall Frame',
    'instagram-stories-ext-6': 'Night Drop',
    'instagram-stories-ext-7': 'Side Rule',
    'instagram-stories-ext-8': 'Low Mark',
    'instagram-stories-ext-9': 'Middle Stage',
    'instagram-stories-ext-10': 'Season Band',
    'instagram-stories-ext-11': 'Heavy Rule',
    'instagram-stories-ext-12': 'Inset Sheet',
    'instagram-stories-ext-13': 'Stacked Tiles',
    'instagram-stories-ext-14': 'Reversed Bar',
    'instagram-stories-ext-15': 'Quiet Column',
    'instagram-stories-ext-16': 'Foot Bar',

    /* ── Cover — wide ───────────────────────────────────────────── */
    'facebook-covers-ext-1': 'Wide Banner',
    'facebook-covers-ext-2': 'Ruled Page',
    'facebook-covers-ext-3': 'Split Panel',
    'facebook-covers-ext-4': 'Ink Band',
    'facebook-covers-ext-5': 'Edge Strip',
    'facebook-covers-ext-6': 'Centre Mark',
    'facebook-covers-ext-7': 'Tag Rail',
    'facebook-covers-ext-8': 'Inset Card',
    'facebook-covers-ext-9': 'Wide Underline',
    'facebook-covers-ext-10': 'Footer Strip',
    'facebook-covers-ext-11': 'Tile Edge',
    'facebook-covers-ext-12': 'Quiet Wide',

    /* ── Profile — 1:1 ───────────────────────────────────── */
    'profile-icons-ext-1': 'Solid Circle',
    'profile-icons-ext-2': 'Brand Squircle',
    'profile-icons-ext-3': 'Tinted Rounded',
    'profile-icons-ext-4': 'Night Square',
    'profile-icons-ext-5': 'Circle Row',
    'profile-icons-ext-6': 'Quiet Row',
    'profile-icons-ext-7': 'Brand Row',
    'profile-icons-ext-8': 'Support Row',
    'profile-icons-ext-9': 'Circle Band',
    'profile-icons-ext-10': 'Paper Band',
    'profile-icons-ext-11': 'Night Band',
    'profile-icons-ext-12': 'Tint Band',
    'profile-icons-ext-13': 'Ring Circle',
    'profile-icons-ext-14': 'Ring Squircle',
    'profile-icons-ext-15': 'Ring Rounded',
    'profile-icons-ext-16': 'Ring Square',
    'profile-icons-ext-17': 'Corner Circle',
    'profile-icons-ext-18': 'Corner Squircle',
    'profile-icons-ext-19': 'Corner Rounded',
    'profile-icons-ext-20': 'Corner Square',
    'profile-icons-ext-21': 'Stacked Circle',
    'profile-icons-ext-22': 'Stacked Squircle',
    'profile-icons-ext-23': 'Stacked Rounded',
    'profile-icons-ext-24': 'Stacked Square',
  },

  /**
   * Three chips per design: the trade it suits, the post it is FOR, and
   * how it looks. The intent chip is the one that matters here — a social
   * shelf sorted by "Bold / Minimal" tells a customer nothing about which
   * tile to open when they have a sale on.
   */
  tags: {
    'instagram-posts-ext-1': ['Studio', 'Announcement', 'Bold'],
    'instagram-posts-ext-2': ['Agency', 'Quote', 'Editorial'],
    'instagram-posts-ext-3': ['Tech', 'Launch', 'Modern'],
    'instagram-posts-ext-4': ['Studio', 'Announcement', 'Minimal'],
    'instagram-posts-ext-5': ['Hospitality', 'Quote', 'Minimal'],
    'instagram-posts-ext-6': ['Retail', 'Sales', 'Bold'],
    'instagram-posts-ext-7': ['Agency', 'Quote', 'Editorial'],
    'instagram-posts-ext-8': ['Tech', 'Launch', 'Minimal'],
    'instagram-posts-ext-9': ['Studio', 'Announcement', 'Bold'],
    'instagram-posts-ext-10': ['Retail', 'Holiday', 'Modern'],
    'instagram-posts-ext-11': ['Retail', 'Sales', 'Bold'],
    'instagram-posts-ext-12': ['Tech', 'Launch', 'Modern'],
    'instagram-posts-ext-13': ['Hospitality', 'Holiday', 'Modern'],
    'instagram-posts-ext-14': ['Retail', 'Sales', 'Bold'],
    'instagram-posts-ext-15': ['Studio', 'Quote', 'Minimal'],
    'instagram-posts-ext-16': ['Agency', 'Announcement', 'Modern'],

    'instagram-stories-ext-1': ['Studio', 'Announcement', 'Bold'],
    'instagram-stories-ext-2': ['Agency', 'Quote', 'Editorial'],
    'instagram-stories-ext-3': ['Tech', 'Launch', 'Modern'],
    'instagram-stories-ext-4': ['Studio', 'Announcement', 'Minimal'],
    'instagram-stories-ext-5': ['Hospitality', 'Quote', 'Minimal'],
    'instagram-stories-ext-6': ['Retail', 'Sales', 'Bold'],
    'instagram-stories-ext-7': ['Agency', 'Quote', 'Editorial'],
    'instagram-stories-ext-8': ['Tech', 'Launch', 'Minimal'],
    'instagram-stories-ext-9': ['Studio', 'Announcement', 'Bold'],
    'instagram-stories-ext-10': ['Retail', 'Holiday', 'Modern'],
    'instagram-stories-ext-11': ['Retail', 'Sales', 'Bold'],
    'instagram-stories-ext-12': ['Tech', 'Launch', 'Modern'],
    'instagram-stories-ext-13': ['Hospitality', 'Holiday', 'Modern'],
    'instagram-stories-ext-14': ['Retail', 'Sales', 'Bold'],
    'instagram-stories-ext-15': ['Studio', 'Quote', 'Minimal'],
    'instagram-stories-ext-16': ['Agency', 'Announcement', 'Modern'],

    'facebook-covers-ext-1': ['Studio', 'Announcement', 'Bold'],
    'facebook-covers-ext-2': ['Agency', 'Quote', 'Editorial'],
    'facebook-covers-ext-3': ['Tech', 'Launch', 'Modern'],
    'facebook-covers-ext-4': ['Studio', 'Announcement', 'Bold'],
    'facebook-covers-ext-5': ['Tech', 'Launch', 'Minimal'],
    'facebook-covers-ext-6': ['Hospitality', 'Quote', 'Minimal'],
    'facebook-covers-ext-7': ['Retail', 'Holiday', 'Modern'],
    'facebook-covers-ext-8': ['Agency', 'Launch', 'Modern'],
    'facebook-covers-ext-9': ['Retail', 'Sales', 'Bold'],
    'facebook-covers-ext-10': ['Agency', 'Announcement', 'Modern'],
    'facebook-covers-ext-11': ['Hospitality', 'Holiday', 'Modern'],
    'facebook-covers-ext-12': ['Studio', 'Quote', 'Minimal'],

    'profile-icons-ext-1': ['Studio', 'Logo', 'Bold'],
    'profile-icons-ext-2': ['Retail', 'Logo', 'Bold'],
    'profile-icons-ext-3': ['Agency', 'Logo', 'Modern'],
    'profile-icons-ext-4': ['Tech', 'Logo', 'Bold'],
    'profile-icons-ext-5': ['Studio', 'Account', 'Modern'],
    'profile-icons-ext-6': ['Agency', 'Account', 'Minimal'],
    'profile-icons-ext-7': ['Retail', 'Account', 'Bold'],
    'profile-icons-ext-8': ['Hospitality', 'Account', 'Modern'],
    'profile-icons-ext-9': ['Retail', 'Account', 'Bold'],
    'profile-icons-ext-10': ['Studio', 'Account', 'Modern'],
    'profile-icons-ext-11': ['Tech', 'Account', 'Bold'],
    'profile-icons-ext-12': ['Agency', 'Account', 'Minimal'],
    'profile-icons-ext-13': ['Studio', 'Monogram', 'Minimal'],
    'profile-icons-ext-14': ['Agency', 'Monogram', 'Minimal'],
    'profile-icons-ext-15': ['Retail', 'Monogram', 'Minimal'],
    'profile-icons-ext-16': ['Tech', 'Monogram', 'Minimal'],
    'profile-icons-ext-17': ['Retail', 'Logo', 'Modern'],
    'profile-icons-ext-18': ['Studio', 'Logo', 'Modern'],
    'profile-icons-ext-19': ['Hospitality', 'Logo', 'Modern'],
    'profile-icons-ext-20': ['Agency', 'Logo', 'Modern'],
    'profile-icons-ext-21': ['Tech', 'Monogram', 'Minimal'],
    'profile-icons-ext-22': ['Retail', 'Monogram', 'Bold'],
    'profile-icons-ext-23': ['Studio', 'Monogram', 'Minimal'],
    'profile-icons-ext-24': ['Hospitality', 'Monogram', 'Minimal'],
  },
};
