-- Down for 038.
DROP TRIGGER IF EXISTS trg_workspace_members_self_role ON public.workspace_members;
DROP TRIGGER IF EXISTS trg_workspace_members_guard_last_owner ON public.workspace_members;
DROP TRIGGER IF EXISTS trg_workspace_members_validate_overrides ON public.workspace_members;
DROP TRIGGER IF EXISTS trg_brand_access_validate_overrides ON public.brand_access;
DROP TRIGGER IF EXISTS trg_brand_access_refuse_implicit ON public.brand_access;
DROP FUNCTION IF EXISTS public.create_workspace(text, text);
DROP FUNCTION IF EXISTS public.archive_brand(uuid, boolean);
DROP FUNCTION IF EXISTS public.revoke_brand_access(uuid, uuid);
DROP FUNCTION IF EXISTS public.grant_brand_access(uuid, uuid, public.brand_role, jsonb, boolean);
DROP FUNCTION IF EXISTS public.transfer_ownership(uuid, uuid, boolean);
DROP FUNCTION IF EXISTS public.leave_workspace(uuid);
DROP FUNCTION IF EXISTS public.remove_member(uuid, uuid);
DROP FUNCTION IF EXISTS public.set_member_role(uuid, uuid, public.workspace_role_v2, public.brand_access_mode, public.brand_role, jsonb);
DROP FUNCTION IF EXISTS public.assert_capability(text, uuid, uuid);
DROP FUNCTION IF EXISTS public.guard_immutable_columns();
DROP FUNCTION IF EXISTS public.guard_self_role_change();
DROP FUNCTION IF EXISTS public.guard_last_owner();
DROP FUNCTION IF EXISTS public.brand_access_refuse_implicit_manager();
DROP FUNCTION IF EXISTS public.validate_capability_overrides();
DROP FUNCTION IF EXISTS public.my_brand_access(uuid);
DROP FUNCTION IF EXISTS public.my_access();
DROP FUNCTION IF EXISTS public.brands_with_capability(text);
DROP FUNCTION IF EXISTS public.workspaces_with_capability(text);
DROP FUNCTION IF EXISTS public.has_capability(text, uuid, uuid);
DROP FUNCTION IF EXISTS public.effective_capabilities(uuid, uuid, uuid);
DROP FUNCTION IF EXISTS public.overridable_capabilities(text, text);
DROP FUNCTION IF EXISTS public.reserved_capabilities();
DROP TABLE IF EXISTS public.role_capabilities;
DROP VIEW IF EXISTS public.workspace_member_state;
