// Phase 4 categories — the 11 initial taxonomy entries that ship
// with the LocalTemplatesService. The Supabase migration seeds the
// same taxonomy on production deploy.

import type { TemplateCategory } from '../types';

export const SEED_CATEGORIES: TemplateCategory[] = [
  {
    id: 'cat-social-posts',
    slug: 'social-posts',
    name: 'Social posts',
    description: 'Square + story formats for Instagram, Facebook, LinkedIn, X.',
    iconName: 'Square',
    displayOrder: 10,
    contentTypeConfigId: 'social-post',
  },
  {
    id: 'cat-presentations',
    slug: 'presentations',
    name: 'Presentations',
    description: 'Pitch decks, business reviews, multi-slide stories.',
    iconName: 'Presentation',
    displayOrder: 20,
    contentTypeConfigId: 'presentation',
  },
  {
    id: 'cat-business-cards',
    slug: 'business-cards',
    name: 'Business cards',
    description: 'Print-safe US/EU standard formats.',
    iconName: 'IdCard',
    displayOrder: 30,
    contentTypeConfigId: 'business-card',
  },
  {
    id: 'cat-invoices',
    slug: 'invoices',
    name: 'Invoices',
    description: 'A4 / US Letter portrait financial documents.',
    iconName: 'Receipt',
    displayOrder: 40,
    contentTypeConfigId: 'invoice',
  },
  {
    id: 'cat-letterheads',
    slug: 'letterheads',
    name: 'Letterheads',
    description: 'Business correspondence on branded paper.',
    iconName: 'FileText',
    displayOrder: 50,
    contentTypeConfigId: 'letterhead',
  },
  {
    id: 'cat-brochures',
    slug: 'brochures',
    name: 'Brochures',
    description: 'Bi-fold and tri-fold print pieces.',
    iconName: 'BookOpen',
    displayOrder: 60,
    contentTypeConfigId: 'brochure',
  },
  {
    id: 'cat-posters',
    slug: 'posters',
    name: 'Posters',
    description: 'Large-format print pieces for events, promo, art.',
    iconName: 'Image',
    displayOrder: 70,
    contentTypeConfigId: 'poster',
  },
  {
    id: 'cat-banners',
    slug: 'banners',
    name: 'Banners',
    description: 'Web headers, social covers, ad creatives.',
    iconName: 'RectangleHorizontal',
    displayOrder: 80,
    contentTypeConfigId: 'banner',
  },
  {
    id: 'cat-email-signatures',
    slug: 'email-signatures',
    name: 'Email signatures',
    description: 'Wide compact formats for email footers.',
    iconName: 'Mail',
    displayOrder: 90,
    contentTypeConfigId: 'email-signature',
  },
  {
    id: 'cat-profile-icons',
    slug: 'profile-icons',
    name: 'Profile icons',
    description: 'Avatars and favicons at exact icon sizes.',
    iconName: 'CircleUser',
    displayOrder: 100,
    contentTypeConfigId: 'profile-icon',
  },
  {
    id: 'cat-brand-guidelines',
    slug: 'brand-guidelines',
    name: 'Brand guidelines',
    description: 'Multi-page brand identity documentation.',
    iconName: 'Palette',
    displayOrder: 110,
    contentTypeConfigId: 'brand-guideline-slide',
  },
];
