-- ============================================================================
-- QA probe — insufficient credits, against the DEPLOYED Edge Function.
--
-- STEP 0 reports leftovers and asserts the script matches the live schema.
-- STEP 1 prepares an isolated fixture. STEP 2 releases and removes it.
--
-- Guarantees:
--
--   ISOLATED     Creates its OWN workspace ('qa-credit-probe') and its own
--                brand inside it. Your real workspace is only ever READ, to
--                print a before/after comparison.
--
--   IDEMPOTENT   Safe to run twice. Workspace, membership and brand are all
--                insert-if-absent, and the credit hold carries the idempotency
--                key 'qa-probe-hold', so a second run reports duplicate:true
--                and moves no credits.
--
--   NO BYPASS    The hold goes through public.reserve_credits — the same
--                atomic function the Edge Function calls. A ledger row is
--                written and the balance/reserved split moves exactly as it
--                does in production.
--
--   NO SCHEMA CHANGE   No GRANT, REVOKE, ALTER, CREATE POLICY, CREATE TABLE or
--                CREATE FUNCTION anywhere in this file. STEP 0 READS
--                information_schema; it does not modify it.
--
--   NO SPEND     The point is that the generation is refused BEFORE a provider
--                is contacted, so nothing is billed to any vendor.
--
-- ─── Required-column audit (why the columns below are the ones supplied) ────
--
-- The first run failed because `brands.primary_color` is NOT NULL with no
-- default and was not supplied. Rather than fix that one column and hope,
-- STEP 0 asserts against the LIVE catalogue that every NOT NULL column without
-- a default on the three tables written here is accounted for.
--
--   workspaces         name, slug, owner_id            — supplied
--   workspace_members  workspace_id, user_id           — supplied
--   brands             user_id, name, primary_color    — supplied
--                      slug                            — generated by the
--                                                        brands_set_slug
--                                                        BEFORE INSERT trigger
--                                                        (it overwrites any
--                                                        value passed in, so
--                                                        slug is deliberately
--                                                        NOT supplied)
--
-- Everything else on these tables is nullable or defaulted, including every
-- JSONB column added by migrations 013/014/016/022.
-- ============================================================================


-- ════════════════════════════════════════════════════════════════════════════
-- STEP 0 — leftovers from the failed run, and a live-schema pre-flight
-- ════════════════════════════════════════════════════════════════════════════

-- A DO block is a single statement, so a RAISE inside it aborts and rolls back
-- everything it did — including trigger side effects such as the credit grant.
-- This query is the evidence rather than the assumption: after the failed run
-- every count below should be 0.
SELECT
  (SELECT count(*) FROM public.workspaces        WHERE slug = 'qa-credit-probe')          AS leftover_workspaces,
  (SELECT count(*) FROM public.brands            WHERE name = 'QA Credit Probe Brand')    AS leftover_brands,
  (SELECT count(*) FROM public.credit_accounts a
     JOIN public.workspaces w ON w.id = a.workspace_id
    WHERE w.slug = 'qa-credit-probe')                                                     AS leftover_credit_accounts;

-- Assert this script supplies every NOT NULL column that has no default.
-- Reads the live catalogue, so it cannot drift from the deployed schema.
DO $$
DECLARE
  unhandled TEXT;
BEGIN
  SELECT string_agg(format('%s.%s', c.table_name, c.column_name), ', ' ORDER BY c.table_name, c.column_name)
    INTO unhandled
    FROM information_schema.columns c
   WHERE c.table_schema = 'public'
     AND c.table_name IN ('workspaces', 'workspace_members', 'brands')
     AND c.is_nullable = 'NO'
     AND c.column_default IS NULL
     AND c.is_identity = 'NO'
     AND NOT (
          (c.table_name = 'workspaces'        AND c.column_name IN ('name', 'slug', 'owner_id'))
       OR (c.table_name = 'workspace_members' AND c.column_name IN ('workspace_id', 'user_id'))
       -- brands.slug is filled by the brands_set_slug trigger, not by us.
       OR (c.table_name = 'brands'            AND c.column_name IN ('user_id', 'name', 'primary_color', 'slug'))
     );

  IF unhandled IS NOT NULL THEN
    RAISE EXCEPTION
      'STEP 1 would fail — unhandled NOT NULL column(s) without a default: %', unhandled;
  END IF;

  RAISE NOTICE 'pre-flight OK: every NOT NULL column without a default is supplied';
END $$;


-- ════════════════════════════════════════════════════════════════════════════
-- STEP 1 — create the isolated fixture and hold most of its credits
-- ════════════════════════════════════════════════════════════════════════════

DO $$
DECLARE
  qa_email  CONSTANT TEXT   := 'alex.test.2026@brandos-qa.dev';
  test_color CONSTANT TEXT  := '#4F46E5';   -- brands.primary_color is NOT NULL
  uid   UUID;
  ws    UUID;
  br    UUID;
  acct  public.credit_accounts;
  res   JSONB;
  hold  BIGINT;
  keep  CONSTANT BIGINT := 5;   -- less than the 14 one Nano Banana Pro image costs
BEGIN
  SELECT id INTO uid FROM auth.users WHERE email = qa_email;
  IF uid IS NULL THEN
    RAISE EXCEPTION 'QA user % not found', qa_email;
  END IF;

  -- ── Isolated workspace (insert-if-absent) ────────────────────────────────
  SELECT id INTO ws FROM public.workspaces WHERE slug = 'qa-credit-probe';
  IF ws IS NULL THEN
    INSERT INTO public.workspaces (name, slug, owner_id)
    VALUES ('QA credit probe', 'qa-credit-probe', uid)
    RETURNING id INTO ws;
    RAISE NOTICE 'created throwaway workspace';
  ELSE
    RAISE NOTICE 'throwaway workspace already existed — reusing';
  END IF;

  INSERT INTO public.workspace_members (workspace_id, user_id, role)
  VALUES (ws, uid, 'owner')
  ON CONFLICT DO NOTHING;

  -- ── Isolated brand inside that workspace ─────────────────────────────────
  -- primary_color is NOT NULL with no default. slug is NOT NULL too, but the
  -- brands_set_slug trigger generates it from name on insert.
  SELECT id INTO br FROM public.brands
   WHERE workspace_id = ws AND name = 'QA Credit Probe Brand';
  IF br IS NULL THEN
    INSERT INTO public.brands (name, user_id, workspace_id, primary_color)
    VALUES ('QA Credit Probe Brand', uid, ws, test_color)
    RETURNING id INTO br;
    RAISE NOTICE 'created throwaway brand';
  ELSE
    RAISE NOTICE 'throwaway brand already existed — reusing';
  END IF;

  -- ── Hold the credits through the real atomic flow ────────────────────────
  -- The workspace trigger granted 500. Leave `keep` behind so the next
  -- generation cannot be afforded.
  SELECT * INTO acct FROM public.credit_accounts WHERE workspace_id = ws;
  IF acct IS NULL THEN
    RAISE EXCEPTION 'no credit account for the throwaway workspace — trigger did not fire';
  END IF;

  hold := GREATEST(0, acct.balance_credits - keep);

  IF hold > 0 THEN
    res := public.reserve_credits(ws, NULL, hold, 'qa-probe-hold');
    IF NOT (res->>'ok')::boolean THEN
      RAISE EXCEPTION 'hold failed: %', res;
    END IF;
    IF (res->>'duplicate')::boolean THEN
      RAISE NOTICE 'hold was already in place (idempotent no-op)';
    END IF;
  END IF;

  SELECT * INTO acct FROM public.credit_accounts WHERE workspace_id = ws;
  IF acct.balance_credits > keep THEN
    RAISE EXCEPTION 'expected <= % credits left, found %', keep, acct.balance_credits;
  END IF;

  RAISE NOTICE '─────────────────────────────────────────────';
  RAISE NOTICE 'brand_id  = %', br;
  RAISE NOTICE 'balance   = % credits (reserved %)', acct.balance_credits, acct.reserved_credits;
  RAISE NOTICE '─────────────────────────────────────────────';
END $$;

-- Return the brand_id to hand back, plus proof the two workspaces are separate.
SELECT
  (SELECT b.id FROM public.brands b
     JOIN public.workspaces w ON w.id = b.workspace_id
    WHERE w.slug = 'qa-credit-probe'
      AND b.name = 'QA Credit Probe Brand')                        AS brand_id_to_send,
  (SELECT a.balance_credits FROM public.credit_accounts a
     JOIN public.workspaces w ON w.id = a.workspace_id
    WHERE w.slug = 'qa-credit-probe')                              AS probe_balance,
  (SELECT a.reserved_credits FROM public.credit_accounts a
     JOIN public.workspaces w ON w.id = a.workspace_id
    WHERE w.slug = 'qa-credit-probe')                              AS probe_reserved,
  (SELECT a.balance_credits FROM public.credit_accounts a
     JOIN public.workspaces w ON w.id = a.workspace_id
    WHERE w.slug <> 'qa-credit-probe'
    ORDER BY a.created_at LIMIT 1)                                 AS your_real_balance_unchanged;


-- ════════════════════════════════════════════════════════════════════════════
-- STEP 2 — release the hold and delete the fixture  (run when the probe is done)
-- ════════════════════════════════════════════════════════════════════════════
--
-- DO $$
-- DECLARE
--   ws   UUID := (SELECT id FROM public.workspaces WHERE slug = 'qa-credit-probe');
--   held BIGINT;
-- BEGIN
--   IF ws IS NULL THEN
--     RAISE NOTICE 'fixture already removed — nothing to do';
--     RETURN;
--   END IF;
--
--   SELECT reserved_credits INTO held FROM public.credit_accounts WHERE workspace_id = ws;
--   IF held > 0 THEN
--     PERFORM public.release_credits(ws, NULL, held, 'qa probe release', 'qa-probe-release');
--   END IF;
--
--   -- Deleting the workspace cascades its credit account, ledger rows and jobs.
--   DELETE FROM public.brands     WHERE workspace_id = ws;
--   DELETE FROM public.workspaces WHERE id = ws;
--
--   RAISE NOTICE 'QA credit probe fixture removed';
-- END $$;
--
-- -- Confirm only your real account remains, untouched:
-- SELECT w.slug, a.balance_credits, a.reserved_credits, a.lifetime_spent
--   FROM public.credit_accounts a
--   JOIN public.workspaces w ON w.id = a.workspace_id;
