import { renderToStaticMarkup } from 'react-dom/server';
import { createElement } from 'react';
import JSZip from 'jszip';
import jsPDF from 'jspdf';
import type { BrandContext } from '@/shared/services/mockup/registry';
import { MOCKUP_TEMPLATES } from '@/shared/services/mockup/registry';
import type { PaletteSuggestion } from './brand-context';
import { DEFAULT_TYPOGRAPHY } from './brand-context';

// One-shot zip of everything in the brand kit. Client-side only — no backend.
//
// Layout:
//   /{slug}/
//     logo/primary.svg
//     logo/icon.svg (best-effort — same file for now)
//     mockups/<id>.svg
//     palette.json
//     typography.json
//     guidelines.pdf
//     README.txt

export interface DownloadInput {
  ctx: BrandContext;
  palette: PaletteSuggestion;
  editedSVG: string | null;
}

function slugify(name: string): string {
  return name
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 40) || 'brand';
}

function mockupToSVG(ctx: BrandContext, templateId: string): string | null {
  const template = MOCKUP_TEMPLATES.find((m) => m.id === templateId);
  if (!template) return null;
  return renderToStaticMarkup(createElement(template.render, { ctx }));
}

function buildGuidelinesPDF(ctx: BrandContext, palette: PaletteSuggestion): Blob {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const W = doc.internal.pageSize.getWidth();

  // ── Cover
  doc.setFillColor(palette.primary);
  doc.rect(0, 0, W, 6, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(42);
  doc.setTextColor('#111111');
  doc.text(ctx.brandName, 48, 120);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(14);
  doc.setTextColor('#555555');
  doc.text(ctx.tagline ?? 'Brand guidelines', 48, 148);

  // ── Palette page
  doc.addPage();
  doc.setFontSize(22);
  doc.setTextColor('#111');
  doc.text('Color palette', 48, 80);
  const colors: Array<[string, string]> = [
    ['Primary', palette.primary],
    ['Secondary', palette.secondary],
    ...palette.accents.map((hex, i) => [`Accent ${i + 1}`, hex] as [string, string]),
  ];
  colors.forEach(([label, hex], i) => {
    const y = 120 + i * 72;
    doc.setFillColor(hex);
    doc.rect(48, y, 64, 48, 'F');
    doc.setFontSize(12);
    doc.setTextColor('#111');
    doc.text(label, 128, y + 22);
    doc.setFontSize(10);
    doc.setTextColor('#666');
    doc.text(hex.toUpperCase(), 128, y + 40);
  });

  // ── Typography page
  doc.addPage();
  doc.setFontSize(22);
  doc.setTextColor('#111');
  doc.text('Typography', 48, 80);
  doc.setFontSize(14);
  doc.setTextColor('#111');
  doc.text(`Heading: ${DEFAULT_TYPOGRAPHY.heading.family.split(',')[0]}`, 48, 130);
  doc.text(`Body: ${DEFAULT_TYPOGRAPHY.body.family.split(',')[0]}`, 48, 160);
  doc.setFontSize(10);
  doc.setTextColor('#555');
  doc.text('Use the heading font for display type (h1/h2). Body font for paragraphs, captions, and UI.', 48, 200, { maxWidth: W - 96 });

  // ── Logo usage page (placeholder notes)
  doc.addPage();
  doc.setFontSize(22);
  doc.text('Logo usage', 48, 80);
  doc.setFontSize(11);
  doc.setTextColor('#333');
  [
    '· Maintain minimum clearspace equal to 25 % of the logo width.',
    '· Do not stretch, skew, or recolor the primary mark.',
    '· Use the monochrome variants on photography where full-color contrast fails.',
    '· Favicon version is optimized for 32 × 32 — do not scale the full logo down to this size.',
  ].forEach((line, i) => {
    doc.text(line, 48, 130 + i * 24, { maxWidth: W - 96 });
  });

  return doc.output('blob');
}

export async function downloadBrandKit({ ctx, palette, editedSVG }: DownloadInput) {
  const zip = new JSZip();
  const slug = slugify(ctx.brandName);
  const root = zip.folder(slug);
  if (!root) return;

  // Logo
  if (editedSVG) {
    const logoFolder = root.folder('logo');
    logoFolder?.file('primary.svg', editedSVG);
  } else {
    root.file(
      'logo/README.txt',
      'The editor had no SVG to export. Re-open the editor and save first.',
    );
  }

  // Mockups
  const mockFolder = root.folder('mockups');
  for (const template of MOCKUP_TEMPLATES) {
    const svg = mockupToSVG(ctx, template.id);
    if (svg) mockFolder?.file(`${template.id}.svg`, svg);
  }

  // Palette + typography
  root.file('palette.json', JSON.stringify(palette, null, 2));
  root.file('typography.json', JSON.stringify(DEFAULT_TYPOGRAPHY, null, 2));

  // Guidelines PDF
  const pdfBlob = buildGuidelinesPDF(ctx, palette);
  root.file('guidelines.pdf', pdfBlob);

  // README
  root.file(
    'README.txt',
    [
      `${ctx.brandName} — brand kit`,
      '',
      `Generated by BrandingOS Logo Maker on ${new Date().toISOString().slice(0, 10)}.`,
      '',
      'Contents:',
      '  logo/primary.svg — source of truth, editable in any vector tool',
      '  mockups/*.svg    — preview mockups (business card, t-shirt, etc.)',
      '  palette.json     — primary, secondary, accents, neutrals',
      '  typography.json  — heading + body font specs',
      '  guidelines.pdf   — A4 print-ready brand guidelines',
      '',
      'Commercial use: fonts are Google Fonts (Inter, Space Grotesk) — free for commercial use.',
    ].join('\n'),
  );

  const blob = await zip.generateAsync({ type: 'blob' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${slug}-brand-kit.zip`;
  a.click();
  URL.revokeObjectURL(url);
}
