/**
 * The palette as things a developer or a designer can actually USE.
 *
 * The Colors download used to be 300+ image files and nothing a
 * stylesheet could read (D37). A palette that cannot be pasted into
 * code gets re-typed by hand, and re-typed hexes drift — which is how a
 * brand ends up with two Irises. So every colour bundle now carries the
 * same six machine-readable forms:
 *
 *   tokens.css           CSS custom properties (`--brand-iris-500`)
 *   tokens.scss          SCSS variables + a `$brand-colors` map
 *   tailwind.colors.js   a `theme.extend.colors` snippet
 *   tokens.json          W3C Design Tokens (DTCG) — `$type` / `$value`
 *   figma.tokens.json    Tokens Studio for Figma
 *   palette.ase          Adobe Swatch Exchange — Illustrator / Photoshop
 *
 * plus a flat SVG/PNG swatch per colour.
 *
 * Everything here is a PURE BUILDER: string in, string or Blob out, no
 * DOM except the shared rasterizer. That is what makes it testable and
 * what keeps `colorPaletteExport` free to import the maths from one
 * place. (This module imports FROM `colorPaletteExport`; the zip
 * builders there reach back through a dynamic import so the two never
 * form a cycle.)
 */
import {
  buildShadeRows,
  contrastReport,
  formatCmyk,
  formatHsl,
  formatRgb,
  normalizeHex,
  rasterizeSvg,
  slugify,
  triggerBlobDownload,
  usageProportions,
  type BundleDepth,
  type PaletteColor,
} from './colorPaletteExport';

/* ─── Naming ──────────────────────────────────────────────── */

/** A token name is a slug, and it must be unique inside one file — two
 *  colours called "Rose" would otherwise silently overwrite each other
 *  in every map, object and JSON group below. */
export function tokenNames(colors: PaletteColor[]): string[] {
  const used = new Set<string>();
  return colors.map((c) => {
    const base = slugify(c.name).replace(/^-+|-+$/g, '') || 'color';
    let name = base;
    let n = 2;
    while (used.has(name)) {
      name = `${base}-${n}`;
      n += 1;
    }
    used.add(name);
    return name;
  });
}

/** Role aliases (`--brand-primary`) — the first colour holding a role
 *  owns the alias, so `var(--brand-primary)` is never ambiguous. */
function roleAliases(colors: PaletteColor[], names: string[]): { alias: string; token: string }[] {
  const taken = new Set<string>();
  const out: { alias: string; token: string }[] = [];
  colors.forEach((c, i) => {
    const alias = slugify(c.role);
    if (taken.has(alias)) return;
    taken.add(alias);
    out.push({ alias, token: names[i] });
  });
  return out;
}

/* ─── CSS ─────────────────────────────────────────────────── */

export function buildCssVariables(colors: PaletteColor[], brandName: string): string {
  const names = tokenNames(colors);
  const lines: string[] = [
    `/* ${brandName} — brand colours as CSS custom properties.`,
    ` * Generated by BrandingOS. Every value is the brand's own hex;`,
    ` * the numbered steps are the shade ladder, with the brand colour`,
    ` * itself sitting on one of the rungs verbatim. */`,
    ':root {',
  ];
  colors.forEach((c, i) => {
    const token = names[i];
    lines.push(`  /* ${c.name} — ${c.role} */`);
    lines.push(`  --brand-${token}: ${normalizeHex(c.hex)};`);
    lines.push(`  --brand-${token}-rgb: ${formatRgb(c.hex).split(' ').join(', ')};`);
    for (const row of buildShadeRows(c.hex, c.name)) {
      lines.push(`  --brand-${token}-${row.step}: ${normalizeHex(row.hex)};`);
    }
  });
  const aliases = roleAliases(colors, names);
  if (aliases.length > 0) {
    lines.push('');
    lines.push('  /* Role aliases */');
    for (const { alias, token } of aliases) {
      lines.push(`  --brand-${alias}: var(--brand-${token});`);
    }
  }
  lines.push('}');
  return `${lines.join('\n')}\n`;
}

/* ─── SCSS ────────────────────────────────────────────────── */

export function buildScssVariables(colors: PaletteColor[], brandName: string): string {
  const names = tokenNames(colors);
  const lines: string[] = [`// ${brandName} — brand colours. Generated by BrandingOS.`, ''];
  colors.forEach((c, i) => {
    lines.push(`// ${c.name} — ${c.role}`);
    lines.push(`$brand-${names[i]}: ${normalizeHex(c.hex)};`);
    for (const row of buildShadeRows(c.hex, c.name)) {
      lines.push(`$brand-${names[i]}-${row.step}: ${normalizeHex(row.hex)};`);
    }
    lines.push('');
  });
  lines.push('$brand-colors: (');
  colors.forEach((c, i) => {
    lines.push(`  "${names[i]}": $brand-${names[i]},`);
  });
  lines.push(');');
  return `${lines.join('\n')}\n`;
}

/* ─── Tailwind ────────────────────────────────────────────── */

export function buildTailwindConfig(colors: PaletteColor[], brandName: string): string {
  const names = tokenNames(colors);
  const entries = colors.map((c, i) => {
    const steps = buildShadeRows(c.hex, c.name)
      .map((row) => `        ${row.step}: '${normalizeHex(row.hex)}',`)
      .join('\n');
    return [
      `      '${names[i]}': {`,
      `        DEFAULT: '${normalizeHex(c.hex)}',`,
      steps,
      '      },',
    ].join('\n');
  });
  return [
    `// ${brandName} — paste into tailwind.config.js (theme.extend.colors).`,
    '// Generated by BrandingOS.',
    'module.exports = {',
    '  theme: {',
    '    extend: {',
    '      colors: {',
    ...entries,
    '      },',
    '    },',
    '  },',
    '};',
    '',
  ].join('\n');
}

/* ─── W3C design tokens (DTCG) ────────────────────────────── */

export function buildDesignTokensJson(colors: PaletteColor[], brandName: string): string {
  const names = tokenNames(colors);
  const group: Record<string, unknown> = {};
  colors.forEach((c, i) => {
    const shades: Record<string, unknown> = {};
    for (const row of buildShadeRows(c.hex, c.name)) {
      shades[String(row.step)] = {
        $type: 'color',
        $value: normalizeHex(row.hex),
        ...(row.isBase ? { $description: 'The brand colour itself.' } : {}),
      };
    }
    group[names[i]] = {
      $type: 'color',
      $value: normalizeHex(c.hex),
      $description: `${c.name} — ${c.role}`,
      ...shades,
    };
  });
  return `${JSON.stringify(
    {
      $description: `${brandName} brand colours. Generated by BrandingOS.`,
      color: group,
    },
    null,
    2,
  )}\n`;
}

/* ─── Tokens Studio (Figma) ───────────────────────────────── */

export function buildFigmaTokensJson(colors: PaletteColor[], brandName: string): string {
  const names = tokenNames(colors);
  const brand: Record<string, unknown> = {};
  colors.forEach((c, i) => {
    const node: Record<string, unknown> = {
      value: normalizeHex(c.hex),
      type: 'color',
      description: `${c.name} — ${c.role}`,
    };
    for (const row of buildShadeRows(c.hex, c.name)) {
      node[String(row.step)] = { value: normalizeHex(row.hex), type: 'color' };
    }
    brand[names[i]] = node;
  });
  return `${JSON.stringify(
    { global: { brand }, $themes: [], $metadata: { source: `${brandName} · BrandingOS` } },
    null,
    2,
  )}\n`;
}

/* ─── Adobe Swatch Exchange (.ase) ────────────────────────── */

/**
 * A minimal, correct ASE writer.
 *
 * The format is big-endian and fixed:
 *   "ASEF" · uint16 major(1) · uint16 minor(0) · uint32 blockCount
 *   per block: uint16 type · uint32 length · payload
 *   colour block (type 0x0001): uint16 nameLen (UTF-16 units, INCLUDING
 *     the terminating NUL) · name as UTF-16BE · NUL · "RGB " ·
 *     3 × float32 (0…1) · uint16 colourType (2 = normal)
 *
 * `nameLen` counting the terminator is the detail Illustrator refuses
 * the file over, so it is asserted in the tests by reading the bytes
 * back rather than trusted.
 */
export function buildAseBlob(colors: PaletteColor[]): Blob | null {
  if (colors.length === 0) return null;
  const names = tokenNames(colors);
  const encoded = colors.map((c, i) => {
    // ASE names are UTF-16; a code point outside the BMP would need a
    // surrogate pair, which `for…of` + charCodeAt handles naturally
    // because we walk the UTF-16 units of the JS string directly.
    const label = c.name || names[i];
    const units: number[] = [];
    for (let k = 0; k < label.length; k += 1) units.push(label.charCodeAt(k));
    return { units, hex: normalizeHex(c.hex) };
  });
  const blockLengths = encoded.map(
    ({ units }) => 2 + (units.length + 1) * 2 + 4 + 12 + 2,
  );
  const total =
    12 + blockLengths.reduce((sum, len) => sum + 6 + len, 0);
  const buf = new ArrayBuffer(total);
  const view = new DataView(buf);
  let o = 0;
  const u8 = (v: number) => {
    view.setUint8(o, v);
    o += 1;
  };
  const u16 = (v: number) => {
    view.setUint16(o, v, false);
    o += 2;
  };
  const u32 = (v: number) => {
    view.setUint32(o, v, false);
    o += 4;
  };
  const f32 = (v: number) => {
    view.setFloat32(o, v, false);
    o += 4;
  };
  for (const ch of 'ASEF') u8(ch.charCodeAt(0));
  u16(1);
  u16(0);
  u32(encoded.length);
  encoded.forEach(({ units, hex }, i) => {
    u16(0x0001);
    u32(blockLengths[i]);
    u16(units.length + 1);
    for (const unit of units) u16(unit);
    u16(0);
    for (const ch of 'RGB ') u8(ch.charCodeAt(0));
    const v = hex.slice(1);
    f32(parseInt(v.slice(0, 2), 16) / 255);
    f32(parseInt(v.slice(2, 4), 16) / 255);
    f32(parseInt(v.slice(4, 6), 16) / 255);
    u16(2);
  });
  return new Blob([buf], { type: 'application/octet-stream' });
}

/* ─── Flat swatches ───────────────────────────────────────── */

const SWATCH_W = 800;
const SWATCH_H = 800;

/** A plain, full-bleed swatch — the file a designer drops into a deck.
 *  The specs ride along the bottom so the file is self-describing. */
export function buildSwatchSvg(color: PaletteColor): string {
  const hex = normalizeHex(color.hex);
  const report = contrastReport(hex);
  const fg = report.onWhite.ratio >= report.onBlack.ratio ? '#FFFFFF' : '#111113';
  const esc = (v: string) =>
    v
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;');
  const mono = 'JetBrains Mono, ui-monospace, SFMono-Regular, monospace';
  const sans = 'Inter, system-ui, sans-serif';
  return [
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${SWATCH_W} ${SWATCH_H}" width="${SWATCH_W}" height="${SWATCH_H}">`,
    `<rect width="${SWATCH_W}" height="${SWATCH_H}" fill="${hex}"/>`,
    `<text x="56" y="86" fill="${fg}" font-family="${sans}" font-size="22" font-weight="600" letter-spacing="4">${esc(color.role.toUpperCase())}</text>`,
    `<text x="56" y="${SWATCH_H - 210}" fill="${fg}" font-family="${sans}" font-size="72" font-weight="600">${esc(color.name)}</text>`,
    `<text x="56" y="${SWATCH_H - 148}" fill="${fg}" font-family="${mono}" font-size="30" letter-spacing="2">${hex}</text>`,
    `<text x="56" y="${SWATCH_H - 100}" fill="${fg}" font-family="${mono}" font-size="20" opacity="0.85">RGB ${formatRgb(hex)}   CMYK ${formatCmyk(hex)}</text>`,
    `<text x="56" y="${SWATCH_H - 66}" fill="${fg}" font-family="${mono}" font-size="20" opacity="0.85">HSL ${esc(formatHsl(hex))}</text>`,
    `<text x="56" y="${SWATCH_H - 32}" fill="${fg}" font-family="${mono}" font-size="20" opacity="0.85">on white ${report.onWhite.ratio.toFixed(2)}:1 ${report.onWhite.level}   on black ${report.onBlack.ratio.toFixed(2)}:1 ${report.onBlack.level}</text>`,
    '</svg>',
  ].join('');
}

export async function buildSwatchPng(color: PaletteColor): Promise<Blob | null> {
  const { png } = await rasterizeSvg(buildSwatchSvg(color), SWATCH_W, SWATCH_H);
  return png;
}

/* ─── Bundling ────────────────────────────────────────────── */

export type TokenFile = { path: string; text: string };

/** Every text-shaped token file, in one call. */
export function buildTokenFiles(colors: PaletteColor[], brandName: string): TokenFile[] {
  return [
    { path: 'tokens.css', text: buildCssVariables(colors, brandName) },
    { path: 'tokens.scss', text: buildScssVariables(colors, brandName) },
    { path: 'tailwind.colors.js', text: buildTailwindConfig(colors, brandName) },
    { path: 'tokens.json', text: buildDesignTokensJson(colors, brandName) },
    { path: 'figma.tokens.json', text: buildFigmaTokensJson(colors, brandName) },
  ];
}

/** The README that travels with a colour bundle — what is in the zip,
 *  what each colour is FOR, and how it behaves on the two grounds. */
export function buildColorsReadme(
  colors: PaletteColor[],
  brandName: string,
  depth: BundleDepth = 'lean',
): string {
  const rows = colors.map((c) => {
    const hex = normalizeHex(c.hex);
    const r = contrastReport(hex);
    return `| ${c.name} | ${c.role} | \`${hex}\` | ${formatRgb(hex)} | ${formatCmyk(hex)} | ${formatHsl(hex)} | ${r.onWhite.ratio.toFixed(2)}:1 ${r.onWhite.level} | ${r.onBlack.ratio.toFixed(2)}:1 ${r.onBlack.level} |`;
  });
  const usage = usageProportions(colors)
    .filter((u) => u.pct > 0)
    .map((u) => `${u.color.name} ${u.pct}%`)
    .join(' · ');
  return [
    `# ${brandName} — colour`,
    '',
    `${colors.length} brand colour${colors.length === 1 ? '' : 's'}. The generated grey ladder is NOT part of this bundle — it belongs to no brand.`,
    '',
    '## The palette',
    '',
    '| Name | Role | HEX | RGB | CMYK | HSL | On white | On black |',
    '| --- | --- | --- | --- | --- | --- | --- | --- |',
    ...rows,
    '',
    '## Proportion',
    '',
    usage ? `Suggested usage split: ${usage}.` : 'Add a colour to see a usage split.',
    '',
    '## What is in here',
    '',
    '- `<Colour>/` — a full-bleed swatch as SVG and PNG, plus a `Shades/` ladder.',
    '  Every ladder carries the brand colour itself on one of its rungs, verbatim,',
    '  so a shade scale can never quietly replace the colour it was drawn from.',
    '- `tokens/tokens.css` — CSS custom properties, including `--brand-primary` role aliases.',
    '- `tokens/tokens.scss` — SCSS variables and a `$brand-colors` map.',
    '- `tokens/tailwind.colors.js` — paste into `theme.extend.colors`.',
    '- `tokens/tokens.json` — W3C Design Tokens (DTCG).',
    '- `tokens/figma.tokens.json` — Tokens Studio for Figma.',
    '- `tokens/palette.ase` — Adobe Swatch Exchange, for Illustrator and Photoshop.',
    '',
    depth === 'full'
      ? 'This is the FULL bundle: JPG and Illustrator-compatible `.ai` files are included alongside the SVG and PNG.'
      : 'This is the standard bundle — SVG and PNG. Choose “Full bundle” in the download menu if you also need JPG and `.ai`.',
    '',
    'Contrast ratios are WCAG 2.1 against pure white and pure black. AA needs 4.5:1 for body text (3:1 at 24px or larger); AAA needs 7:1.',
    '',
  ].join('\n');
}

/** Tokens-only zip — the developer handoff, on its own. */
export async function buildTokensZip(
  colors: PaletteColor[],
  brandName: string,
): Promise<Blob> {
  const { default: JSZip } = await import('jszip');
  const zip = new JSZip();
  for (const { path, text } of buildTokenFiles(colors, brandName)) {
    zip.file(path, text);
  }
  const ase = buildAseBlob(colors);
  if (ase) zip.file('palette.ase', ase);
  zip.file('README.md', buildColorsReadme(colors, brandName));
  return zip.generateAsync({ type: 'blob' });
}

export async function downloadTokens(colors: PaletteColor[], brandName: string): Promise<void> {
  const blob = await buildTokensZip(colors, brandName);
  triggerBlobDownload(blob, `${slugify(brandName)}-color-tokens.zip`);
}
