/**
 * LogoFilesModule — premium, brand-aware logo variant system.
 *
 * Variants are generated by `generateLogoVariants(brand)` in
 * `src/shared/color/brandRules.ts`, which inspects the brand's color
 * strategy (1 / 2 / 3+ colors) and produces a structured catalogue across
 * five groups: Master · Monochrome · Backgrounds · Configurations ·
 * Applications. This file is the presentation + download layer.
 */
import { useState, useMemo, useCallback } from 'react';
import {
  Download,
  Check,
  AlertTriangle,
  Info,
  Package,
  Palette,
  Moon,
  Sun,
  Sparkles,
  Layers,
  Grid3x3,
  Smartphone,
  ImageIcon,
  Loader2,
  Upload,
} from 'lucide-react';
import {
  generateLogoVariants,
  analyzeBrandColors,
  type LogoVariant,
  type LogoVariantGroup,
  type BrandColorAnalysis,
} from '../engine/brandRules';
import type { Brand } from '@/shared/types/brand';
import { toast } from 'sonner';

interface LogoFilesModuleProps {
  brand: Brand;
}

// ── Download primitives ────────────────────────────────────────────────

function triggerDownload(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

function loadImage(src: string): Promise<HTMLImageElement> {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.crossOrigin = 'anonymous';
    img.onload = () => resolve(img);
    img.onerror = reject;
    img.src = src;
  });
}

/**
 * Rasterize a logo variant to a PNG blob. Handles aspect hint
 * (horizontal / stacked / square / auto), preserves the logo's native
 * aspect ratio, and applies the variant's CSS filter.
 */
async function rasterizeVariant(
  variant: LogoVariant,
  targetSize: number,
): Promise<Blob> {
  if (!variant.logoSrc) throw new Error('Variant has no source image');
  const img = await loadImage(variant.logoSrc);
  const ratio = img.width / img.height;

  let cw: number;
  let ch: number;
  const padding = 0.2;

  if (variant.aspectHint === 'square') {
    cw = targetSize;
    ch = targetSize;
  } else if (variant.aspectHint === 'horizontal') {
    cw = targetSize;
    ch = Math.round(targetSize / Math.max(ratio, 2));
  } else if (variant.aspectHint === 'stacked') {
    cw = Math.round(targetSize * 0.9);
    ch = targetSize;
  } else if (ratio >= 2) {
    cw = targetSize;
    ch = Math.round((targetSize / ratio) * (1 + padding * 2));
  } else if (ratio >= 1) {
    cw = targetSize;
    ch = Math.round((targetSize / ratio) * (1 + padding));
  } else {
    ch = targetSize;
    cw = Math.round(targetSize * ratio * (1 + padding));
    if (cw < targetSize * 0.6) cw = targetSize;
  }

  const canvas = document.createElement('canvas');
  canvas.width = cw;
  canvas.height = ch;
  const ctx = canvas.getContext('2d');
  if (!ctx) throw new Error('Canvas 2D unavailable');

  if (variant.bgColor && variant.bgColor !== 'transparent') {
    ctx.fillStyle = variant.bgColor;
    ctx.fillRect(0, 0, cw, ch);
  }

  const maxW = cw * (1 - padding * 2);
  const maxH = ch * (1 - padding * 2);
  const scale = Math.min(maxW / img.width, maxH / img.height);
  const dw = img.width * scale;
  const dh = img.height * scale;
  const dx = (cw - dw) / 2;
  const dy = (ch - dh) / 2;

  if (variant.logoFilter) ctx.filter = variant.logoFilter;
  ctx.drawImage(img, dx, dy, dw, dh);
  ctx.filter = 'none';

  return new Promise((resolve, reject) => {
    canvas.toBlob(
      (blob) => (blob ? resolve(blob) : reject(new Error('toBlob failed'))),
      'image/png',
    );
  });
}

async function buildVariantPdf(variant: LogoVariant, brand: Brand): Promise<Blob> {
  const { default: jsPDF } = await import('jspdf');
  const img = await loadImage(variant.logoSrc);
  const ratio = img.width / img.height;
  const pdfW = 300;
  const pdfH = ratio > 1.5 ? (pdfW / ratio) * 1.5 : pdfW;
  const pdf = new jsPDF({
    orientation: ratio > 1.2 ? 'landscape' : 'portrait',
    unit: 'mm',
    format: [pdfW, pdfH],
  });

  if (variant.bgColor !== 'transparent') {
    pdf.setFillColor(variant.bgColor);
    pdf.rect(0, 0, pdfW, pdfH, 'F');
  }

  const blob = await rasterizeVariant(variant, 4000);
  const dataUrl: string = await new Promise((resolve) => {
    const reader = new FileReader();
    reader.onloadend = () => resolve(reader.result as string);
    reader.readAsDataURL(blob);
  });

  const logoW = pdfW * 0.5;
  const logoH = logoW / ratio;
  const lx = (pdfW - logoW) / 2;
  const ly = (pdfH - logoH) / 2;
  pdf.addImage(dataUrl, 'PNG', lx, ly, logoW, logoH);

  pdf.setFontSize(6);
  pdf.setTextColor(150);
  pdf.text(`${brand.name} — ${variant.name}`, 8, pdfH - 8);
  pdf.text(variant.recommendedUse, 8, pdfH - 4);
  pdf.text(
    `${variant.bgColor} · ${variant.contrastScore.toFixed(1)}:1`,
    pdfW - 8,
    pdfH - 4,
    { align: 'right' },
  );

  return pdf.output('blob');
}

async function fetchSvgText(url: string): Promise<string | null> {
  if (!url || url.startsWith('data:')) return null;
  try {
    const resp = await fetch(url);
    const text = await resp.text();
    if (!text.trim().startsWith('<')) return null;
    return text;
  } catch {
    return null;
  }
}

// ── Presentational primitives ──────────────────────────────────────────

const GROUP_META: Record<
  LogoVariantGroup,
  { label: string; icon: React.ElementType; description: string }
> = {
  master: {
    label: 'Master',
    icon: Sparkles,
    description: 'The canonical forms of the logo. Start here.',
  },
  monochrome: {
    label: 'Monochrome',
    icon: Layers,
    description: 'Single-color reductions — black, white, inverse.',
  },
  background: {
    label: 'On Backgrounds',
    icon: Palette,
    description: 'Variants tuned to specific surface colors.',
  },
  configuration: {
    label: 'Configurations',
    icon: Grid3x3,
    description: 'Structural layouts — horizontal, stacked, icon, wordmark.',
  },
  application: {
    label: 'Applications',
    icon: Smartphone,
    description: 'Product-surface ready — favicons, app icons, profile pictures, print.',
  },
};

const ALL_GROUPS: LogoVariantGroup[] = [
  'master',
  'monochrome',
  'background',
  'configuration',
  'application',
];

type UsageFilter = 'all' | 'digital' | 'print' | 'dark' | 'light' | 'social';

const USAGE_FILTERS: { key: UsageFilter; label: string; icon?: React.ElementType }[] = [
  { key: 'all', label: 'All usage' },
  { key: 'digital', label: 'Digital' },
  { key: 'print', label: 'Print' },
  { key: 'light', label: 'Light bg', icon: Sun },
  { key: 'dark', label: 'Dark bg', icon: Moon },
  { key: 'social', label: 'Social' },
];

function matchesUsage(v: LogoVariant, filter: UsageFilter): boolean {
  if (filter === 'all') return true;
  if (filter === 'digital') return !!v.forDigital;
  if (filter === 'print') return !!v.forPrint;
  if (filter === 'dark') return v.bgCompatibility === 'dark' || (v.tags ?? []).includes('dark');
  if (filter === 'light') return v.bgCompatibility === 'light' || (v.tags ?? []).includes('light');
  if (filter === 'social') return (v.tags ?? []).includes('social');
  return true;
}

function ContrastBadge({ score }: { score: number }) {
  if (score === 0) {
    return (
      <span className="inline-flex items-center gap-1 text-[10px] font-medium text-muted-foreground">
        <Info className="h-3 w-3" /> Transparent
      </span>
    );
  }
  const level = score >= 4.5 ? 'pass' : score >= 3 ? 'warn' : 'fail';
  const color =
    level === 'pass'
      ? 'text-emerald-600 dark:text-emerald-400'
      : level === 'warn'
      ? 'text-amber-600 dark:text-amber-400'
      : 'text-red-500 dark:text-red-400';
  const Icon = level === 'pass' ? Check : level === 'warn' ? Info : AlertTriangle;
  return (
    <span className={`inline-flex items-center gap-0.5 text-[10px] font-semibold ${color}`}>
      <Icon className="h-3 w-3" /> {score.toFixed(1)}:1
    </span>
  );
}

function UsageTag({ children }: { children: React.ReactNode }) {
  return (
    <span className="inline-flex items-center rounded-full border border-border/70 bg-background/60 px-1.5 py-0.5 text-[9px] font-medium uppercase tracking-wide text-muted-foreground">
      {children}
    </span>
  );
}

// Transparency checker — inline so it renders consistently with the app's
// neutral theme regardless of the surrounding surface.
const TRANSPARENCY_PATTERN =
  'repeating-conic-gradient(#e5e5e5 0% 25%, transparent 0% 50%) 0 0 / 14px 14px';

// ── Strategy summary card ──────────────────────────────────────────────

function StrategyCard({
  analysis,
  variantCount,
  onBulkDownload,
  isBulkDownloading,
  downloadSize,
  onDownloadSizeChange,
}: {
  analysis: BrandColorAnalysis;
  variantCount: number;
  onBulkDownload: () => void;
  isBulkDownloading: boolean;
  downloadSize: number;
  onDownloadSizeChange: (n: number) => void;
}) {
  const strategyLabel =
    analysis.strategy === 'single'
      ? 'Single-color system'
      : analysis.strategy === 'dual'
      ? 'Dual-color system'
      : 'Full palette system';

  const strategyDescription =
    analysis.strategy === 'single'
      ? 'One brand color. Monochrome variants do the heavy lifting — black, white, and inverse carry the brand across every surface.'
      : analysis.strategy === 'dual'
      ? 'Two brand colors working together. Full-color variants on light and dark, plus a secondary-color inverse for accent surfaces.'
      : 'Three or more palette colors. Full-color masters, reduced-palette fallbacks, and accent-safe backgrounds ready for campaigns.';

  return (
    <div className="relative overflow-hidden rounded-2xl border border-border bg-gradient-to-br from-background via-background to-muted/30 p-5">
      <div className="flex flex-col gap-5 md:flex-row md:items-start md:justify-between">
        <div className="flex-1 space-y-3">
          <div className="flex items-center gap-2">
            <div className="inline-flex h-7 w-7 items-center justify-center rounded-lg bg-primary/10 text-primary">
              <Sparkles className="h-3.5 w-3.5" />
            </div>
            <span className="text-[11px] font-semibold uppercase tracking-wider text-muted-foreground">
              Brand logic engine
            </span>
          </div>
          <div>
            <h3 className="text-lg font-semibold leading-tight">{strategyLabel}</h3>
            <p className="mt-1 max-w-xl text-[13px] leading-relaxed text-muted-foreground">
              {strategyDescription}
            </p>
          </div>

          {/* Color chips */}
          <div className="flex flex-wrap items-center gap-2 pt-1">
            {analysis.colors.map((c) => (
              <div
                key={c.role}
                className="flex items-center gap-1.5 rounded-full border border-border bg-card/60 py-1 pl-1 pr-2.5"
              >
                <span
                  className="h-4 w-4 rounded-full ring-1 ring-inset ring-black/10"
                  style={{ backgroundColor: c.hex }}
                />
                <span className="text-[11px] font-medium capitalize">{c.role}</span>
                <span className="text-[10px] font-mono uppercase text-muted-foreground">
                  {c.hex}
                </span>
              </div>
            ))}
            <span className="inline-flex items-center gap-1 rounded-full bg-muted/60 px-2.5 py-1 text-[11px] font-medium text-muted-foreground">
              <Layers className="h-3 w-3" />
              {variantCount} variants · {ALL_GROUPS.length} groups
            </span>
          </div>
        </div>

        {/* Bulk download controls */}
        <div className="flex flex-col items-stretch gap-2 md:w-64">
          <div className="flex items-center justify-between rounded-lg border border-border bg-card px-3 py-2">
            <span className="text-[11px] font-medium text-muted-foreground">PNG size</span>
            <select
              value={downloadSize}
              onChange={(e) => onDownloadSizeChange(Number(e.target.value))}
              className="bg-transparent text-xs font-medium outline-none"
            >
              <option value={1024}>1024px · Web</option>
              <option value={2048}>2048px · HD</option>
              <option value={4000}>4000px · Print</option>
              <option value={6000}>6000px · Ultra</option>
            </select>
          </div>
          <button
            onClick={onBulkDownload}
            disabled={isBulkDownloading}
            className="group relative flex items-center justify-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground shadow-sm transition-all hover:bg-primary/90 disabled:opacity-60"
          >
            {isBulkDownloading ? (
              <Loader2 className="h-4 w-4 animate-spin" />
            ) : (
              <Package className="h-4 w-4" />
            )}
            {isBulkDownloading ? 'Packaging…' : 'Download Full Kit (ZIP)'}
          </button>
          <p className="text-center text-[10px] text-muted-foreground">
            Organized by group · SVG + PNG + PDF per variant
          </p>
        </div>
      </div>
    </div>
  );
}

// ── Variant card ───────────────────────────────────────────────────────

function VariantCard({
  variant,
  brand,
  downloadSize,
}: {
  variant: LogoVariant;
  brand: Brand;
  downloadSize: number;
}) {
  const [busy, setBusy] = useState<string | null>(null);

  const isPlaceholder = variant.hasSourceAsset === false && variant.requiresSource === 'icon' && !variant.isValid;
  const tags = variant.tags ?? [];

  const handleDownload = useCallback(
    async (format: 'SVG' | 'PNG' | 'PDF') => {
      const slug = brand.slug || brand.name.toLowerCase().replace(/\s+/g, '-');
      const baseName = `${slug}-${variant.id}`;
      try {
        setBusy(format);
        if (format === 'SVG') {
          const svgText = await fetchSvgText(variant.logoSrc);
          if (!svgText) {
            toast.error('No SVG source available — try PNG instead.');
            return;
          }
          triggerDownload(
            new Blob([svgText], { type: 'image/svg+xml' }),
            `${baseName}.svg`,
          );
          toast.success(`Downloaded ${variant.name} (SVG)`);
          return;
        }
        if (format === 'PNG') {
          const blob = await rasterizeVariant(variant, downloadSize);
          triggerDownload(blob, `${baseName}-${downloadSize}.png`);
          toast.success(`Downloaded ${variant.name} (${downloadSize}px PNG)`);
          return;
        }
        if (format === 'PDF') {
          const blob = await buildVariantPdf(variant, brand);
          triggerDownload(blob, `${baseName}.pdf`);
          toast.success(`Downloaded ${variant.name} (PDF)`);
          return;
        }
      } catch (err) {
        console.error(err);
        toast.error(`${format} export failed`);
      } finally {
        setBusy(null);
      }
    },
    [variant, brand, downloadSize],
  );

  const isSquare = variant.aspectHint === 'square';
  const aspectClass = isSquare ? 'aspect-square' : 'aspect-[16/10]';
  const isProfile = variant.type === 'profile-circle';
  const isAppIcon = variant.type === 'app-icon';

  return (
    <div
      className={`group flex flex-col overflow-hidden rounded-xl border bg-card transition-all ${
        variant.isValid
          ? 'border-border hover:border-primary/40 hover:shadow-md'
          : 'border-amber-300/60 dark:border-amber-700/50'
      }`}
    >
      {/* Preview */}
      <div
        className={`relative flex items-center justify-center overflow-hidden ${aspectClass}`}
        style={{
          backgroundColor: variant.bgColor === 'transparent' ? undefined : variant.bgColor,
          backgroundImage:
            variant.bgColor === 'transparent' ? TRANSPARENCY_PATTERN : undefined,
        }}
      >
        {isPlaceholder ? (
          <div className="flex flex-col items-center gap-2 px-4 text-center">
            <div className="flex h-10 w-10 items-center justify-center rounded-full bg-muted text-muted-foreground">
              <Upload className="h-4 w-4" />
            </div>
            <p className="text-[11px] font-medium text-muted-foreground">
              Upload an icon asset
            </p>
          </div>
        ) : (
          <div
            className={`flex items-center justify-center ${
              isProfile
                ? 'h-[72%] w-[72%] rounded-full'
                : isAppIcon
                ? 'h-[72%] w-[72%] rounded-[22%]'
                : 'h-[70%] w-[70%]'
            }`}
            style={{
              backgroundColor:
                isProfile || isAppIcon ? variant.bgColor : undefined,
            }}
          >
            <img
              src={variant.logoSrc}
              alt={variant.name}
              className="max-h-full max-w-full object-contain"
              style={{ filter: variant.logoFilter || 'none' }}
            />
          </div>
        )}

        {/* Top-left: warnings */}
        {variant.warnings.length > 0 && (
          <div className="absolute left-2 top-2 flex h-6 w-6 items-center justify-center rounded-full bg-amber-500/90 text-white shadow-sm">
            <AlertTriangle className="h-3 w-3" />
          </div>
        )}

        {/* Top-right: contrast pill */}
        <div className="absolute right-2 top-2 rounded-full bg-background/85 px-1.5 py-0.5 shadow-sm backdrop-blur">
          <ContrastBadge score={variant.contrastScore} />
        </div>

        {/* Bottom-left: min-size hint */}
        {variant.minSize && (
          <div className="absolute bottom-2 left-2 rounded-full bg-background/85 px-1.5 py-0.5 text-[9px] font-semibold text-muted-foreground shadow-sm backdrop-blur">
            ≥ {variant.minSize}px
          </div>
        )}

        {/* Bottom-right: print/digital dots */}
        <div className="absolute bottom-2 right-2 flex items-center gap-1">
          {variant.forDigital && (
            <span
              className="h-1.5 w-1.5 rounded-full bg-sky-500"
              title="Digital-ready"
            />
          )}
          {variant.forPrint && (
            <span
              className="h-1.5 w-1.5 rounded-full bg-purple-500"
              title="Print-ready"
            />
          )}
        </div>
      </div>

      {/* Info */}
      <div className="flex flex-1 flex-col gap-2 p-3.5">
        <div className="flex items-start justify-between gap-2">
          <div className="min-w-0 flex-1">
            <h4 className="truncate text-[13px] font-semibold leading-tight">
              {variant.name}
            </h4>
            <p className="mt-0.5 line-clamp-2 text-[11px] leading-snug text-muted-foreground">
              {variant.recommendedUse}
            </p>
          </div>
        </div>

        {tags.length > 0 && (
          <div className="flex flex-wrap gap-1">
            {tags.slice(0, 4).map((t) => (
              <UsageTag key={t}>{t}</UsageTag>
            ))}
          </div>
        )}

        {variant.warnings.length > 0 && (
          <p className="rounded-md bg-amber-50 px-2 py-1 text-[10px] leading-snug text-amber-700 dark:bg-amber-900/20 dark:text-amber-300">
            {variant.warnings[0]}
          </p>
        )}

        {/* Download row */}
        <div className="mt-auto flex gap-1 pt-1">
          {variant.downloadFormats.includes('SVG') && (
            <button
              onClick={() => handleDownload('SVG')}
              disabled={busy !== null}
              className="flex flex-1 items-center justify-center gap-1 rounded-md bg-primary px-2 py-1.5 text-[10px] font-semibold text-primary-foreground transition-colors hover:bg-primary/90 disabled:opacity-50"
            >
              {busy === 'SVG' ? (
                <Loader2 className="h-2.5 w-2.5 animate-spin" />
              ) : (
                <Download className="h-2.5 w-2.5" />
              )}
              SVG
            </button>
          )}
          {variant.downloadFormats.includes('PNG') && (
            <button
              onClick={() => handleDownload('PNG')}
              disabled={busy !== null}
              className="flex flex-1 items-center justify-center gap-1 rounded-md bg-muted px-2 py-1.5 text-[10px] font-semibold text-foreground transition-colors hover:bg-muted/70 disabled:opacity-50"
            >
              {busy === 'PNG' ? (
                <Loader2 className="h-2.5 w-2.5 animate-spin" />
              ) : (
                <Download className="h-2.5 w-2.5" />
              )}
              PNG
            </button>
          )}
          {variant.downloadFormats.includes('PDF') && (
            <button
              onClick={() => handleDownload('PDF')}
              disabled={busy !== null}
              className="flex flex-1 items-center justify-center gap-1 rounded-md border border-border bg-background px-2 py-1.5 text-[10px] font-semibold text-foreground transition-colors hover:bg-muted disabled:opacity-50"
            >
              {busy === 'PDF' ? (
                <Loader2 className="h-2.5 w-2.5 animate-spin" />
              ) : (
                <Download className="h-2.5 w-2.5" />
              )}
              PDF
            </button>
          )}
        </div>
      </div>
    </div>
  );
}

// ── Group section ─────────────────────────────────────────────────────

function GroupSection({
  group,
  variants,
  brand,
  downloadSize,
}: {
  group: LogoVariantGroup;
  variants: LogoVariant[];
  brand: Brand;
  downloadSize: number;
}) {
  if (variants.length === 0) return null;
  const meta = GROUP_META[group];
  const Icon = meta.icon;

  return (
    <section className="space-y-3">
      <div className="flex items-baseline justify-between gap-4 border-b border-border/60 pb-2">
        <div className="flex items-center gap-2">
          <div className="flex h-7 w-7 items-center justify-center rounded-lg bg-muted text-foreground/70">
            <Icon className="h-3.5 w-3.5" />
          </div>
          <div>
            <h3 className="text-sm font-semibold leading-tight">{meta.label}</h3>
            <p className="text-[11px] leading-tight text-muted-foreground">
              {meta.description}
            </p>
          </div>
        </div>
        <span className="text-[11px] font-medium text-muted-foreground">
          {variants.length} {variants.length === 1 ? 'variant' : 'variants'}
        </span>
      </div>
      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
        {variants.map((v) => (
          <VariantCard
            key={v.id}
            variant={v}
            brand={brand}
            downloadSize={downloadSize}
          />
        ))}
      </div>
    </section>
  );
}

// ── Bulk ZIP builder ──────────────────────────────────────────────────

async function buildLogoKitZip(
  brand: Brand,
  variants: LogoVariant[],
  pngSize: number,
  onProgress: (label: string, pct: number) => void,
): Promise<Blob> {
  const { default: JSZip } = await import('jszip');
  const zip = new JSZip();
  const slug = brand.slug || brand.name.toLowerCase().replace(/\s+/g, '-');

  const groups: Record<string, typeof zip> = {};
  for (const group of ALL_GROUPS) {
    groups[group] = zip.folder(group)!;
  }

  const total = variants.length;
  let done = 0;

  for (const variant of variants) {
    const group = (variant.group ?? 'master') as LogoVariantGroup;
    const folder = groups[group] || zip;
    const variantFolder = folder.folder(variant.id)!;
    onProgress(variant.name, Math.round((done / total) * 100));

    // PNG (always)
    if (variant.isValid || variant.hasSourceAsset !== false) {
      try {
        const blob = await rasterizeVariant(variant, pngSize);
        variantFolder.file(`${slug}-${variant.id}-${pngSize}.png`, blob);
      } catch (err) {
        console.warn(`[LogoKit] PNG ${variant.id} failed`, err);
      }
    }

    // SVG (if source is an SVG url)
    if (variant.downloadFormats.includes('SVG')) {
      const svgText = await fetchSvgText(variant.logoSrc);
      if (svgText) {
        variantFolder.file(`${slug}-${variant.id}.svg`, svgText);
      }
    }

    // PDF (for print-ready variants only — keeps zip size reasonable)
    if (variant.downloadFormats.includes('PDF') && variant.forPrint) {
      try {
        const blob = await buildVariantPdf(variant, brand);
        variantFolder.file(`${slug}-${variant.id}.pdf`, blob);
      } catch (err) {
        console.warn(`[LogoKit] PDF ${variant.id} failed`, err);
      }
    }

    done += 1;
  }

  // README
  const readme = [
    `${brand.name} — Logo Kit`,
    ''.padEnd(`${brand.name} — Logo Kit`.length, '='),
    '',
    `Generated by BrandOS on ${new Date().toISOString().slice(0, 10)}`,
    '',
    `Variants: ${variants.length}`,
    `PNG size: ${pngSize}px`,
    '',
    'Folder structure:',
    ...ALL_GROUPS.map((g) => {
      const count = variants.filter((v) => (v.group ?? 'master') === g).length;
      return `  ${g}/  — ${GROUP_META[g].description} (${count})`;
    }),
    '',
    'Each variant folder contains:',
    '  • SVG — vector source (when available, infinite resolution)',
    '  • PNG — rendered at the selected size',
    '  • PDF — print-ready (for variants flagged as print)',
    '',
    'Brand colors:',
    ...(analyzeBrandColors(brand).colors.map((c) => `  ${c.role.padEnd(10)} ${c.hex}`)),
  ].join('\n');
  zip.file('README.txt', readme);

  onProgress('Finalizing…', 98);
  return zip.generateAsync({ type: 'blob' });
}

// ── Main module ───────────────────────────────────────────────────────

export function LogoFilesModule({ brand }: LogoFilesModuleProps) {
  const [groupFilter, setGroupFilter] = useState<LogoVariantGroup | 'all'>('all');
  const [usageFilter, setUsageFilter] = useState<UsageFilter>('all');
  const [downloadSize, setDownloadSize] = useState(2048);
  const [bulkBusy, setBulkBusy] = useState(false);

  const analysis = useMemo(() => analyzeBrandColors(brand), [brand]);
  const allVariants = useMemo(() => generateLogoVariants(brand), [brand]);

  const filteredVariants = useMemo(() => {
    return allVariants.filter((v) => {
      if (groupFilter !== 'all' && (v.group ?? 'master') !== groupFilter) return false;
      if (!matchesUsage(v, usageFilter)) return false;
      return true;
    });
  }, [allVariants, groupFilter, usageFilter]);

  const variantsByGroup = useMemo(() => {
    const byGroup: Record<LogoVariantGroup, LogoVariant[]> = {
      master: [],
      monochrome: [],
      background: [],
      configuration: [],
      application: [],
    };
    for (const v of filteredVariants) {
      const g = (v.group ?? 'master') as LogoVariantGroup;
      byGroup[g].push(v);
    }
    for (const g of ALL_GROUPS) {
      byGroup[g].sort((a, b) => (a.priority ?? 0) - (b.priority ?? 0));
    }
    return byGroup;
  }, [filteredVariants]);

  const handleBulkDownload = useCallback(async () => {
    if (allVariants.length === 0) return;
    setBulkBusy(true);
    const toastId = toast.loading('Packaging logo kit…');
    try {
      const slug = brand.slug || brand.name.toLowerCase().replace(/\s+/g, '-');
      const blob = await buildLogoKitZip(brand, allVariants, downloadSize, (label, pct) => {
        toast.loading(`${label} · ${pct}%`, { id: toastId });
      });
      triggerDownload(blob, `${slug}-logo-kit.zip`);
      toast.success(`Logo kit downloaded · ${allVariants.length} variants`, { id: toastId });
    } catch (err) {
      console.error(err);
      toast.error('Logo kit export failed', { id: toastId });
    } finally {
      setBulkBusy(false);
    }
  }, [brand, allVariants, downloadSize]);

  // Empty state — no logo uploaded
  if (!brand.logo) {
    return (
      <div className="space-y-6">
        <div>
          <h2 className="text-xl font-semibold">Logo Variants</h2>
          <p className="text-sm text-muted-foreground">
            Upload a logo to generate the full variant system.
          </p>
        </div>
        <div className="flex flex-col items-center justify-center gap-3 rounded-2xl border-2 border-dashed border-border py-20 text-center">
          <div className="flex h-12 w-12 items-center justify-center rounded-full bg-muted text-muted-foreground">
            <ImageIcon className="h-5 w-5" />
          </div>
          <div>
            <p className="font-medium">No logo yet</p>
            <p className="mt-1 text-sm text-muted-foreground">
              Add a logo in Brand Settings to generate a full brand-aware variant system.
            </p>
          </div>
        </div>
      </div>
    );
  }

  const groupTabs: { key: LogoVariantGroup | 'all'; label: string; count: number }[] = [
    { key: 'all', label: 'All', count: allVariants.length },
    ...ALL_GROUPS.map((g) => ({
      key: g,
      label: GROUP_META[g].label,
      count: allVariants.filter((v) => (v.group ?? 'master') === g).length,
    })),
  ];

  return (
    <div className="space-y-6">
      {/* Strategy card */}
      <StrategyCard
        analysis={analysis}
        variantCount={allVariants.length}
        onBulkDownload={handleBulkDownload}
        isBulkDownloading={bulkBusy}
        downloadSize={downloadSize}
        onDownloadSizeChange={setDownloadSize}
      />

      {/* Filters */}
      <div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between">
        {/* Group tabs */}
        <div className="flex flex-wrap gap-1.5">
          {groupTabs.map((t) => (
            <button
              key={t.key}
              onClick={() => setGroupFilter(t.key)}
              className={`inline-flex items-center gap-1.5 rounded-full border px-3 py-1.5 text-xs font-semibold transition-all ${
                groupFilter === t.key
                  ? 'border-primary bg-primary text-primary-foreground'
                  : 'border-border bg-background text-muted-foreground hover:bg-muted'
              }`}
            >
              {t.label}
              <span
                className={`rounded-full px-1.5 py-0.5 text-[10px] ${
                  groupFilter === t.key
                    ? 'bg-primary-foreground/20 text-primary-foreground'
                    : 'bg-muted text-muted-foreground'
                }`}
              >
                {t.count}
              </span>
            </button>
          ))}
        </div>

        {/* Usage chips */}
        <div className="flex flex-wrap gap-1">
          {USAGE_FILTERS.map((u) => {
            const Icon = u.icon;
            return (
              <button
                key={u.key}
                onClick={() => setUsageFilter(u.key)}
                className={`inline-flex items-center gap-1 rounded-md px-2 py-1 text-[11px] font-medium transition-all ${
                  usageFilter === u.key
                    ? 'bg-foreground text-background'
                    : 'text-muted-foreground hover:bg-muted'
                }`}
              >
                {Icon && <Icon className="h-3 w-3" />}
                {u.label}
              </button>
            );
          })}
        </div>
      </div>

      {/* Result count */}
      {filteredVariants.length === 0 ? (
        <div className="flex flex-col items-center gap-2 rounded-xl border border-dashed border-border py-16 text-center">
          <Info className="h-5 w-5 text-muted-foreground" />
          <p className="text-sm text-muted-foreground">
            No variants match the current filters.
          </p>
          <button
            onClick={() => {
              setGroupFilter('all');
              setUsageFilter('all');
            }}
            className="text-xs font-semibold text-primary underline-offset-2 hover:underline"
          >
            Clear filters
          </button>
        </div>
      ) : groupFilter === 'all' ? (
        <div className="space-y-8">
          {ALL_GROUPS.map((g) => (
            <GroupSection
              key={g}
              group={g}
              variants={variantsByGroup[g]}
              brand={brand}
              downloadSize={downloadSize}
            />
          ))}
        </div>
      ) : (
        <GroupSection
          group={groupFilter}
          variants={variantsByGroup[groupFilter]}
          brand={brand}
          downloadSize={downloadSize}
        />
      )}
    </div>
  );
}
