/**
 * The card icon library — a curated, categorized lucide subset the
 * IconLibraryPopover searches (reference: Chronicle's icon picker).
 * Curated on purpose: importing all of lucide for a search box would
 * drag ~1500 icons into the chunk; these ~150 named imports tree-shake.
 */
import {
  Anchor,
  ArrowDown,
  ArrowDownLeft,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  AtSign,
  Atom,
  Award,
  Baby,
  BadgeCheck,
  Bell,
  Bird,
  Bone,
  BookOpen,
  Bookmark,
  Brain,
  Briefcase,
  Bug,
  Building,
  Building2,
  Calculator,
  Calendar,
  Camera,
  ChartColumn,
  ChartLine,
  ChartPie,
  Check,
  Circle,
  CircleDot,
  Clapperboard,
  Clock,
  Cloud,
  CloudLightning,
  CloudMoon,
  CloudRain,
  CloudSnow,
  CloudSun,
  Clover,
  Compass,
  CreditCard,
  Crown,
  Diamond,
  Disc,
  Dog,
  DollarSign,
  Droplet,
  Droplets,
  Eye,
  Feather,
  Film,
  Fish,
  Flag,
  Flame,
  Flower,
  Flower2,
  Footprints,
  Frown,
  Gamepad2,
  Gem,
  Ghost,
  Gift,
  Globe,
  Hammer,
  Hand,
  Handshake,
  Hash,
  Headphones,
  Heart,
  Hexagon,
  Home,
  Image,
  Infinity as InfinityIcon,
  Info,
  Key,
  Landmark,
  Laptop,
  Laugh,
  Leaf,
  Lightbulb,
  Link,
  Lock,
  Mail,
  MailOpen,
  Map as MapIcon,
  MapPin,
  Medal,
  Megaphone,
  Meh,
  MessageCircle,
  MessageSquare,
  Mic,
  Monitor,
  Moon,
  Mountain,
  MoveRight,
  Music,
  Music2,
  Nut,
  Origami,
  Package,
  Paintbrush,
  Palette,
  Pause,
  PenTool,
  Percent,
  PersonStanding,
  Phone,
  PhoneCall,
  Play,
  Plus,
  Puzzle,
  Radio,
  Rainbow,
  RefreshCw,
  Repeat,
  Rocket,
  RotateCcw,
  Rss,
  Ruler,
  Scale,
  Scissors,
  Send,
  Share2,
  Shell,
  Shield,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Skull,
  Smartphone,
  Smile,
  Snowflake,
  Sparkle,
  Sparkles,
  Speaker,
  Sprout,
  Square,
  Squirrel,
  Star,
  Sun,
  Tablet,
  Target,
  ThumbsDown,
  ThumbsUp,
  Tornado,
  TreeDeciduous,
  TreePine,
  TrendingDown,
  TrendingUp,
  Triangle,
  Trophy,
  Tv,
  Umbrella,
  User,
  UserPlus,
  Users,
  Video,
  Volume2,
  Wallet,
  Watch,
  Waves,
  Wifi,
  Wind,
  Wrench,
  X,
  Zap,
  type LucideIcon,
} from 'lucide-react';

export interface LibraryIcon {
  name: string;
  Icon: LucideIcon;
  /** Extra lowercase search words beyond the name itself. */
  keywords?: string[];
}

export interface IconCategory {
  category: string;
  icons: LibraryIcon[];
}

const icon = (name: string, Icon: LucideIcon, keywords?: string[]): LibraryIcon => ({
  name,
  Icon,
  keywords,
});

export const ICON_LIBRARY: IconCategory[] = [
  {
    category: 'Weather & Nature',
    icons: [
      icon('Nut', Nut, ['acorn', 'seed']),
      icon('Atom', Atom, ['science']),
      icon('Bird', Bird),
      icon('Bone', Bone),
      icon('Origami', Origami, ['paper', 'crane']),
      icon('Dog', Dog, ['pet']),
      icon('Flame', Flame, ['fire']),
      icon('Cloud', Cloud),
      icon('CloudRain', CloudRain, ['rain']),
      icon('CloudLightning', CloudLightning, ['storm']),
      icon('CloudMoon', CloudMoon, ['night']),
      icon('CloudSnow', CloudSnow, ['snow']),
      icon('CloudSun', CloudSun, ['day']),
      icon('Clover', Clover, ['luck']),
      icon('Droplet', Droplet, ['water']),
      icon('Droplets', Droplets, ['water']),
      icon('Feather', Feather),
      icon('Fish', Fish),
      icon('Flower', Flower),
      icon('Flower2', Flower2, ['lotus']),
      icon('Leaf', Leaf, ['plant']),
      icon('Moon', Moon, ['night']),
      icon('Mountain', Mountain),
      icon('Rainbow', Rainbow),
      icon('Shell', Shell),
      icon('Snowflake', Snowflake, ['winter']),
      icon('Sprout', Sprout, ['plant', 'grow']),
      icon('Squirrel', Squirrel),
      icon('Sun', Sun, ['day']),
      icon('Tornado', Tornado),
      icon('TreeDeciduous', TreeDeciduous, ['tree']),
      icon('TreePine', TreePine, ['tree', 'palm']),
      icon('Umbrella', Umbrella),
      icon('Waves', Waves, ['sea', 'ocean']),
      icon('Wind', Wind),
      icon('Bug', Bug, ['insect']),
    ],
  },
  {
    category: 'Arrows',
    icons: [
      icon('ArrowUp', ArrowUp),
      icon('ArrowDown', ArrowDown),
      icon('ArrowLeft', ArrowLeft),
      icon('ArrowRight', ArrowRight),
      icon('ArrowUpRight', ArrowUpRight),
      icon('ArrowDownLeft', ArrowDownLeft),
      icon('MoveRight', MoveRight),
      icon('RefreshCw', RefreshCw, ['reload', 'sync']),
      icon('RotateCcw', RotateCcw, ['undo']),
      icon('Repeat', Repeat, ['loop']),
      icon('TrendingUp', TrendingUp, ['growth']),
      icon('TrendingDown', TrendingDown, ['decline']),
    ],
  },
  {
    category: 'Objects',
    icons: [
      icon('Home', Home, ['house']),
      icon('Building', Building),
      icon('Building2', Building2, ['office']),
      icon('Briefcase', Briefcase, ['work']),
      icon('Package', Package, ['box']),
      icon('Gift', Gift, ['present']),
      icon('ShoppingBag', ShoppingBag),
      icon('ShoppingCart', ShoppingCart),
      icon('Wallet', Wallet, ['money']),
      icon('CreditCard', CreditCard, ['payment']),
      icon('Key', Key),
      icon('Lock', Lock, ['secure']),
      icon('Bell', Bell, ['notification']),
      icon('BookOpen', BookOpen, ['read']),
      icon('Bookmark', Bookmark),
      icon('Camera', Camera, ['photo']),
      icon('Clock', Clock, ['time']),
      icon('Watch', Watch, ['time']),
      icon('Calendar', Calendar, ['date']),
      icon('Map', MapIcon),
      icon('MapPin', MapPin, ['location']),
      icon('Compass', Compass, ['direction']),
      icon('Globe', Globe, ['world']),
      icon('Lightbulb', Lightbulb, ['idea']),
      icon('Wrench', Wrench, ['tool']),
      icon('Hammer', Hammer, ['tool']),
      icon('Scissors', Scissors, ['cut']),
      icon('PenTool', PenTool, ['design']),
      icon('Paintbrush', Paintbrush, ['art']),
      icon('Palette', Palette, ['color', 'art']),
      icon('Ruler', Ruler, ['measure']),
    ],
  },
  {
    category: 'People & Faces',
    icons: [
      icon('User', User, ['person']),
      icon('Users', Users, ['team', 'group']),
      icon('UserPlus', UserPlus, ['invite']),
      icon('Smile', Smile, ['happy', 'face']),
      icon('Laugh', Laugh, ['face']),
      icon('Frown', Frown, ['sad', 'face']),
      icon('Meh', Meh, ['face']),
      icon('Heart', Heart, ['love']),
      icon('ThumbsUp', ThumbsUp, ['like']),
      icon('ThumbsDown', ThumbsDown, ['dislike']),
      icon('Eye', Eye, ['view']),
      icon('Brain', Brain, ['mind']),
      icon('Baby', Baby),
      icon('PersonStanding', PersonStanding, ['human']),
      icon('Footprints', Footprints, ['steps']),
      icon('Hand', Hand),
    ],
  },
  {
    category: 'Communication',
    icons: [
      icon('Mail', Mail, ['email']),
      icon('MailOpen', MailOpen, ['email']),
      icon('Send', Send, ['message']),
      icon('MessageCircle', MessageCircle, ['chat']),
      icon('MessageSquare', MessageSquare, ['chat']),
      icon('Phone', Phone, ['call']),
      icon('PhoneCall', PhoneCall, ['call']),
      icon('AtSign', AtSign, ['mention', 'email']),
      icon('Hash', Hash, ['tag']),
      icon('Link', Link, ['url']),
      icon('Share2', Share2, ['share']),
      icon('Megaphone', Megaphone, ['announce']),
      icon('Mic', Mic, ['voice']),
      icon('Rss', Rss, ['feed']),
      icon('Wifi', Wifi, ['network']),
      icon('Radio', Radio),
    ],
  },
  {
    category: 'Media',
    icons: [
      icon('Play', Play, ['video']),
      icon('Pause', Pause),
      icon('Music', Music, ['song']),
      icon('Music2', Music2, ['note']),
      icon('Headphones', Headphones, ['audio']),
      icon('Video', Video, ['camera']),
      icon('Film', Film, ['movie']),
      icon('Image', Image, ['photo', 'picture']),
      icon('Tv', Tv, ['screen']),
      icon('Monitor', Monitor, ['screen']),
      icon('Smartphone', Smartphone, ['phone']),
      icon('Tablet', Tablet),
      icon('Laptop', Laptop, ['computer']),
      icon('Speaker', Speaker, ['audio']),
      icon('Volume2', Volume2, ['sound']),
      icon('Disc', Disc, ['record']),
      icon('Clapperboard', Clapperboard, ['movie']),
      icon('Gamepad2', Gamepad2, ['game']),
    ],
  },
  {
    category: 'Business & Data',
    icons: [
      icon('ChartColumn', ChartColumn, ['chart', 'graph']),
      icon('ChartPie', ChartPie, ['chart']),
      icon('ChartLine', ChartLine, ['chart', 'graph']),
      icon('Target', Target, ['goal']),
      icon('Award', Award, ['prize']),
      icon('Trophy', Trophy, ['win']),
      icon('Medal', Medal, ['prize']),
      icon('Crown', Crown, ['king']),
      icon('Rocket', Rocket, ['launch']),
      icon('Flag', Flag, ['milestone']),
      icon('Zap', Zap, ['bolt', 'fast']),
      icon('DollarSign', DollarSign, ['money']),
      icon('Percent', Percent),
      icon('Calculator', Calculator, ['math']),
      icon('Landmark', Landmark, ['bank']),
      icon('Scale', Scale, ['balance', 'legal']),
      icon('Handshake', Handshake, ['deal']),
    ],
  },
  {
    category: 'Symbols',
    icons: [
      icon('Check', Check, ['done']),
      icon('X', X, ['close']),
      icon('Plus', Plus, ['add']),
      icon('Info', Info),
      icon('Sparkles', Sparkles, ['magic', 'ai']),
      icon('Sparkle', Sparkle, ['magic']),
      icon('Shield', Shield, ['secure']),
      icon('ShieldCheck', ShieldCheck, ['secure']),
      icon('BadgeCheck', BadgeCheck, ['verified']),
      icon('CircleDot', CircleDot),
      icon('Square', Square),
      icon('Circle', Circle),
      icon('Triangle', Triangle),
      icon('Diamond', Diamond),
      icon('Hexagon', Hexagon),
      icon('Infinity', InfinityIcon),
      icon('Anchor', Anchor),
      icon('Ghost', Ghost),
      icon('Skull', Skull),
      icon('Puzzle', Puzzle),
      icon('Gem', Gem, ['diamond']),
      icon('Star', Star, ['favorite']),
    ],
  },
];

const BY_NAME = new Map<string, LucideIcon>(
  ICON_LIBRARY.flatMap((c) => c.icons.map((i) => [i.name, i.Icon] as const)),
);

export function iconByName(name: string): LucideIcon | undefined {
  return BY_NAME.get(name);
}

/** The Emoji tab's curated set. */
export const EMOJI_SET = [
  '😀', '😄', '😊', '😉', '😍', '🤩', '😎', '🤔', '🙌', '👏', '👍', '💪', '🙏', '✌️',
  '❤️', '🧡', '💛', '💚', '💙', '💜', '🖤', '✨', '⭐', '🌟', '⚡', '🔥', '🌈', '☀️',
  '🌙', '🌍', '🌸', '🌿', '🍀', '🎉', '🎊', '🎯', '🏆', '🥇', '🚀', '💎',
  '💡', '📈', '📊', '💼', '📌', '🔔', '🎨', '🎵',
] as const;
