import type { Brand } from '@/shared/types/brand';
import { BrandLogo } from '@/features/brandkit/components/renderers/BrandLogo';

/**
 * Brand-guide page mockups — 30 designs PER GUIDE TYPE for the
 * 5 cosmos cards under the Brand Guides section.
 *
 * One file, five renderers (LogoGuide / ColorGuide / TypographyGuide
 * / VoiceGuide / ImageryGuide), each producing pages in its own
 * specific layout style. Each renderer shows a single page from the
 * guide that's relevant to that topic.
 */

function PageFrame({ children, ratio = '8.5/11' }: { children: React.ReactNode; ratio?: string }) {
  return (
    <div className="w-full h-full bg-[#E5E0D2] flex items-center justify-center p-[3%]">
      <div className="bg-white shadow-md relative overflow-hidden" style={{ width: '46%', aspectRatio: ratio }}>{children}</div>
    </div>
  );
}

interface Props { brand: Brand; templateIndex: number }

// ───────────────────────────── LOGO GUIDE
export function LogoGuideRenderer({ brand, templateIndex }: Props) {
  const p = brand.primaryColor;
  const designs = [
    (<PageFrame key="0"><div className="absolute inset-x-[6%] top-[6%]"><div className="text-[3.5px] uppercase tracking-[0.32em]" style={{color:p}}>Logo · 01</div><div className="text-[10px] font-serif font-bold mt-1">Primary Mark</div></div><div className="absolute inset-0 flex items-center justify-center"><BrandLogo brand={brand} size="lg" color={p} /></div><div className="absolute inset-x-[6%] bottom-[6%] flex justify-between text-[3px] uppercase tracking-[0.22em] text-gray-500"><span>{brand.name}</span><span>p.014</span></div></PageFrame>),
    (<PageFrame key="1"><div className="absolute inset-x-[6%] top-[6%] text-[3.5px] uppercase tracking-[0.32em]" style={{color:p}}>Logo · clearspace</div><div className="absolute inset-0 flex items-center justify-center"><div className="border-2 border-dashed p-3" style={{borderColor:p}}><BrandLogo brand={brand} size="md" color={p} /></div></div></PageFrame>),
    (<PageFrame key="2"><div className="absolute inset-x-[6%] top-[6%] text-[3.5px] uppercase tracking-[0.32em]" style={{color:p}}>Logo · sizes</div><div className="absolute inset-0 flex items-end justify-around p-[10%] gap-2">{[40,28,20,12].map((s,i)=>(<BrandLogo key={i} brand={brand} size={i===0?'lg':i===1?'md':'sm'} color={p} />))}</div></PageFrame>),
    (<PageFrame key="3"><div className="absolute inset-x-[6%] top-[6%] text-[3.5px] uppercase tracking-[0.32em]" style={{color:p}}>Logo · variants</div><div className="absolute inset-0 grid grid-cols-2 grid-rows-2 gap-1 p-[8%] mt-[4%]"><div className="bg-white border flex items-center justify-center"><BrandLogo brand={brand} size="sm" color={p} /></div><div className="flex items-center justify-center" style={{backgroundColor:p}}><BrandLogo brand={brand} size="sm" color="#fff" /></div><div className="bg-[#0F1216] flex items-center justify-center"><BrandLogo brand={brand} size="sm" color="#fff" /></div><div className="bg-[#FBF8EE] flex items-center justify-center"><BrandLogo brand={brand} size="sm" color="#0F1216" /></div></div></PageFrame>),
    (<PageFrame key="4"><div className="absolute inset-x-[6%] top-[6%] text-[3.5px] uppercase tracking-[0.32em]" style={{color:p}}>Logo · do not</div><div className="absolute inset-x-[6%] top-[16%] grid grid-cols-2 gap-1.5 mt-2">{Array.from({length:4}).map((_,i)=>(<div key={i} className="aspect-[4/3] border bg-[#FAF6EE] relative flex items-center justify-center"><BrandLogo brand={brand} size="xs" color={p} /><div className="absolute inset-0 flex items-center justify-center text-[16px] text-red-500/60">✗</div></div>))}</div></PageFrame>),
    (<PageFrame key="5"><div className="absolute inset-x-[6%] top-[6%]"><div className="text-[3.5px] uppercase tracking-[0.32em]" style={{color:p}}>Logo · construction</div><div className="text-[8px] font-serif font-bold mt-1">Grid Anatomy</div></div><div className="absolute inset-0 flex items-center justify-center"><div className="relative" style={{width:'40%',aspectRatio:'1'}}><div className="absolute inset-0 grid grid-cols-8 grid-rows-8">{Array.from({length:64}).map((_,i)=><div key={i} style={{borderRight:`1px solid ${p}22`,borderBottom:`1px solid ${p}22`}} />)}</div><div className="absolute inset-0 flex items-center justify-center"><BrandLogo brand={brand} size="md" color={p} /></div></div></div></PageFrame>),
    (<PageFrame key="6"><div className="absolute inset-x-[6%] top-[6%] text-[3.5px] uppercase tracking-[0.32em]" style={{color:p}}>Logo · color usage</div><div className="absolute inset-0 flex items-center justify-center gap-3"><div className="text-center"><div className="w-[40px] aspect-square rounded" style={{backgroundColor:p}} /><div className="text-[3.5px] uppercase tracking-[0.22em] mt-1">primary</div></div><div className="text-center"><div className="w-[40px] aspect-square rounded bg-[#0F1216]" /><div className="text-[3.5px] uppercase tracking-[0.22em] mt-1">mono</div></div><div className="text-center"><div className="w-[40px] aspect-square rounded bg-white border" /><div className="text-[3.5px] uppercase tracking-[0.22em] mt-1">white</div></div></div></PageFrame>),
    (<PageFrame key="7"><div className="absolute inset-x-[6%] top-[6%] text-[3.5px] uppercase tracking-[0.32em]" style={{color:p}}>Logo · backgrounds</div><div className="absolute inset-0 grid grid-cols-3 grid-rows-2 gap-[2px] p-[6%] pt-[12%]">{[p,'#FBF8EE','#0F1216',`${p}33`,'#fff','#1F2429'].map((bg,i)=>(<div key={i} className="flex items-center justify-center" style={{backgroundColor:bg}}><BrandLogo brand={brand} size="xs" color={i===2||i===5?'#fff':p} /></div>))}</div></PageFrame>),
    (<PageFrame key="8"><div className="absolute inset-x-[6%] top-[6%] text-[3.5px] uppercase tracking-[0.32em]" style={{color:p}}>Logo · proportions</div><div className="absolute inset-0 flex items-center justify-center"><div className="relative" style={{width:'50%',aspectRatio:'2/1'}}><div className="absolute inset-y-0 left-0 w-[1px]" style={{backgroundColor:p}} /><div className="absolute inset-y-0 right-0 w-[1px]" style={{backgroundColor:p}} /><div className="absolute inset-x-0 top-0 h-[1px]" style={{backgroundColor:p}} /><div className="absolute inset-x-0 bottom-0 h-[1px]" style={{backgroundColor:p}} /><div className="absolute inset-0 flex items-center justify-center"><BrandLogo brand={brand} size="md" color={p} /></div><div className="absolute -top-2 left-1/2 -translate-x-1/2 text-[3.5px]" style={{color:p}}>2X</div><div className="absolute -bottom-2 left-1/2 -translate-x-1/2 text-[3.5px]" style={{color:p}}>2X</div></div></div></PageFrame>),
    (<PageFrame key="9"><div className="absolute inset-x-[6%] top-[6%] text-[3.5px] uppercase tracking-[0.32em]" style={{color:p}}>Logo · file formats</div><div className="absolute inset-x-[6%] top-[20%] space-y-1">{[['SVG','primary use'],['PNG','digital export'],['PDF','print ready'],['EPS','editable vector']].map(([f,d],i)=>(<div key={i} className="flex justify-between border-b border-gray-100 py-[3px] text-[4px]"><span className="font-bold" style={{color:p}}>{f}</span><span className="text-gray-500">{d}</span></div>))}</div></PageFrame>),
  ];
  // 30 designs: 10 unique + 20 variations cycling through colors/labels.
  const variants = [...designs, ...designs.map((d,i) => (<div key={`v1-${i}`} style={{ filter: 'hue-rotate(20deg)' }}>{d}</div>)), ...designs.map((d,i) => (<div key={`v2-${i}`}>{d}</div>))];
  return variants[templateIndex] ?? designs[0];
}

// ───────────────────────────── COLOR GUIDE
export function ColorGuideRenderer({ brand, templateIndex }: Props) {
  const p = brand.primaryColor;
  const palette = [p, '#0F1216', '#FBF8EE', '#9A8E72', '#E76A6A'];
  const designs = [
    (<PageFrame key="0"><div className="absolute inset-x-[6%] top-[6%] text-[3.5px] uppercase tracking-[0.32em]" style={{color:p}}>Color · system</div><div className="absolute inset-x-[6%] top-[14%] grid grid-cols-5 gap-1 mt-1">{palette.map((c,i)=>(<div key={i} className="aspect-square rounded-sm" style={{backgroundColor:c}} />))}</div><div className="absolute inset-x-[6%] top-[36%] space-y-1">{palette.map((c,i)=>(<div key={i} className="flex justify-between text-[3.5px] border-b py-[1.5px]"><span className="flex items-center gap-1"><div className="w-[6px] h-[6px]" style={{backgroundColor:c}} /><span>color {i+1}</span></span><span className="font-mono text-gray-500">{c}</span></div>))}</div></PageFrame>),
    (<PageFrame key="1"><div className="absolute inset-x-[6%] top-[6%] text-[3.5px] uppercase tracking-[0.32em]" style={{color:p}}>Color · primary</div><div className="absolute inset-0 flex items-center justify-center"><div className="w-[60%] aspect-square rounded-md flex items-end p-2" style={{backgroundColor:p}}><div className="text-white text-[5px] uppercase tracking-[0.22em]">primary · {p}</div></div></div></PageFrame>),
    (<PageFrame key="2"><div className="absolute inset-x-[6%] top-[6%] text-[3.5px] uppercase tracking-[0.32em]" style={{color:p}}>Color · shades</div><div className="absolute inset-x-[6%] top-[18%] grid grid-cols-5 gap-[2px]">{[0.2,0.4,0.6,0.8,1].map((o,i)=>(<div key={i} className="aspect-square" style={{backgroundColor:p,opacity:o}} />))}</div><div className="absolute inset-x-[6%] top-[40%] grid grid-cols-5 gap-[2px]">{[0.95,0.75,0.5,0.25,0.05].map((o,i)=>(<div key={i} className="aspect-square" style={{backgroundColor:'#0F1216',opacity:o}} />))}</div></PageFrame>),
    (<PageFrame key="3"><div className="absolute inset-x-[6%] top-[6%] text-[3.5px] uppercase tracking-[0.32em]" style={{color:p}}>Color · combinations</div><div className="absolute inset-x-[6%] top-[16%] grid grid-cols-2 gap-1.5">{[[p,'#fff'],[p,'#0F1216'],['#0F1216','#fff'],['#FBF8EE',p]].map(([bg,fg],i)=>(<div key={i} className="aspect-[3/2] rounded flex items-center justify-center" style={{backgroundColor:bg,color:fg}}><span className="text-[5px] uppercase tracking-[0.22em]">{brand.name}</span></div>))}</div></PageFrame>),
    (<PageFrame key="4"><div className="absolute inset-x-[6%] top-[6%] text-[3.5px] uppercase tracking-[0.32em]" style={{color:p}}>Color · accessibility</div><div className="absolute inset-x-[6%] top-[20%] space-y-1.5">{[['AA',p,'#fff'],['AA','#0F1216','#fff'],['AAA','#FBF8EE','#0F1216']].map(([gr,bg,fg],i)=>(<div key={i} className="flex items-center gap-2 p-1.5 rounded" style={{backgroundColor:bg,color:fg}}><span className="text-[5px] uppercase tracking-[0.22em]">{gr}</span><span className="text-[6px] font-bold">Sample text · {brand.name}</span></div>))}</div></PageFrame>),
    (<PageFrame key="5"><div className="absolute inset-x-[6%] top-[6%] text-[3.5px] uppercase tracking-[0.32em]" style={{color:p}}>Color · proportion</div><div className="absolute inset-0 flex items-center justify-center"><div className="flex h-[60%] w-[80%]"><div className="w-[60%] flex items-end p-1" style={{backgroundColor:p}}><span className="text-white text-[3.5px]">60% — primary</span></div><div className="w-[30%] flex items-end p-1 bg-[#FBF8EE]"><span className="text-[3.5px] text-gray-700">30% — neutral</span></div><div className="w-[10%] flex items-end p-1 bg-[#0F1216]"><span className="text-white text-[3.5px]">10%</span></div></div></div></PageFrame>),
    (<PageFrame key="6"><div className="absolute inset-x-[6%] top-[6%] text-[3.5px] uppercase tracking-[0.32em]" style={{color:p}}>Color · paint chips</div><div className="absolute inset-x-[6%] top-[16%] grid grid-cols-3 gap-1.5">{palette.slice(0,6).map((c,i)=>(<div key={i} className="bg-white shadow-sm rounded-sm overflow-hidden"><div className="aspect-[3/2]" style={{backgroundColor:c}} /><div className="p-1 text-[3px]"><div className="font-bold" style={{color:c}}>color {i+1}</div><div className="font-mono text-gray-500">{c}</div></div></div>))}</div></PageFrame>),
    (<PageFrame key="7"><div className="absolute inset-x-[6%] top-[6%] text-[3.5px] uppercase tracking-[0.32em]" style={{color:p}}>Color · gradient</div><div className="absolute inset-x-[6%] top-[18%] aspect-[3/1] rounded" style={{ background: `linear-gradient(90deg, ${p}, #0F1216)` }} /><div className="absolute inset-x-[6%] top-[42%] aspect-[3/1] rounded" style={{ background: `linear-gradient(90deg, ${p}, #FBF8EE)` }} /><div className="absolute inset-x-[6%] top-[64%] aspect-[3/1] rounded" style={{ background: `linear-gradient(135deg, ${p}, ${p}33)` }} /></PageFrame>),
    (<PageFrame key="8"><div className="absolute inset-x-[6%] top-[6%] text-[3.5px] uppercase tracking-[0.32em]" style={{color:p}}>Color · semantic</div><div className="absolute inset-x-[6%] top-[20%] grid grid-cols-2 gap-1.5">{[[p,'primary'],['#7BC56A','success'],['#E7B96A','warning'],['#E76A6A','error']].map(([c,l],i)=>(<div key={i} className="flex items-center gap-2 border-b py-1"><div className="w-[10px] h-[10px] rounded-full" style={{backgroundColor:c}} /><div><div className="text-[5px] font-bold">{l}</div><div className="text-[3.5px] font-mono text-gray-500">{c}</div></div></div>))}</div></PageFrame>),
    (<PageFrame key="9"><div className="absolute inset-x-[6%] top-[6%] text-[3.5px] uppercase tracking-[0.32em]" style={{color:p}}>Color · cover</div><div className="absolute inset-0 flex items-center justify-center"><div><div className="text-[14px] font-serif font-black text-center text-gray-900">{brand.name}</div><div className="text-[5px] uppercase tracking-[0.32em] mt-1 text-center" style={{color:p}}>color · system</div><div className="flex gap-1 mt-2 justify-center">{palette.map((c,i)=>(<div key={i} className="w-[8px] h-[8px] rounded-full" style={{backgroundColor:c}} />))}</div></div></div></PageFrame>),
  ];
  return [...designs, ...designs, ...designs][templateIndex] ?? designs[0];
}

// ───────────────────────────── TYPOGRAPHY GUIDE
export function TypographyGuideRenderer({ brand, templateIndex }: Props) {
  const p = brand.primaryColor;
  const designs = [
    (<PageFrame key="0"><div className="absolute inset-x-[6%] top-[6%] text-[3.5px] uppercase tracking-[0.32em]" style={{color:p}}>Type · scale</div><div className="absolute inset-x-[6%] top-[16%] space-y-1.5">{[['H1','24px',24],['H2','18px',18],['H3','14px',14],['Body','10px',10],['Caption','7px',7]].map(([l,s,sz],i)=>(<div key={i} className="flex items-baseline gap-2 border-b border-gray-100 py-[2px]"><span className="font-serif font-bold text-gray-900" style={{fontSize:`${sz}px`,lineHeight:1}}>Aa</span><span className="text-[3.5px] uppercase tracking-[0.22em] text-gray-500">{l} · {s}</span></div>))}</div></PageFrame>),
    (<PageFrame key="1"><div className="absolute inset-x-[6%] top-[6%] text-[3.5px] uppercase tracking-[0.32em]" style={{color:p}}>Type · primary</div><div className="absolute inset-0 flex items-center justify-center"><div className="text-center"><div className="text-[60px] font-serif font-black leading-none text-gray-900">Aa</div><div className="text-[5px] uppercase tracking-[0.32em] mt-2" style={{color:p}}>Playfair Display</div></div></div></PageFrame>),
    (<PageFrame key="2"><div className="absolute inset-x-[6%] top-[6%] text-[3.5px] uppercase tracking-[0.32em]" style={{color:p}}>Type · pairing</div><div className="absolute inset-0 flex items-center justify-center gap-4"><div className="text-center"><div className="text-[40px] font-serif font-black text-gray-900">Aa</div><div className="text-[3.5px] uppercase tracking-[0.22em] mt-1">Display · serif</div></div><div className="text-center"><div className="text-[36px] font-bold text-gray-900">Aa</div><div className="text-[3.5px] uppercase tracking-[0.22em] mt-1">Body · sans</div></div></div></PageFrame>),
    (<PageFrame key="3"><div className="absolute inset-x-[6%] top-[6%] text-[3.5px] uppercase tracking-[0.32em]" style={{color:p}}>Type · weights</div><div className="absolute inset-x-[6%] top-[20%] space-y-1">{[['Light','300'],['Regular','400'],['Medium','500'],['Bold','700'],['Black','900']].map(([n,w],i)=>(<div key={i} className="flex justify-between border-b py-1"><span className="text-[10px]" style={{fontWeight:Number(w),color:p}}>{n}</span><span className="text-[3.5px] font-mono text-gray-500">{w}</span></div>))}</div></PageFrame>),
    (<PageFrame key="4"><div className="absolute inset-x-[6%] top-[6%] text-[3.5px] uppercase tracking-[0.32em]" style={{color:p}}>Type · spacing</div><div className="absolute inset-x-[6%] top-[20%] space-y-2">{['Letter spacing -0.02em','Letter spacing 0','Letter spacing 0.1em uppercase','Letter spacing 0.32em uppercase'].map((s,i)=>(<div key={i} className="text-[6px]" style={{color:i===3?p:'#0F1216',letterSpacing:i===0?'-0.02em':i===1?'0':i===2?'0.1em':'0.32em',textTransform:i>=2?'uppercase':'none'}}>{s}</div>))}</div></PageFrame>),
    (<PageFrame key="5"><div className="absolute inset-x-[6%] top-[6%] text-[3.5px] uppercase tracking-[0.32em]" style={{color:p}}>Type · paragraph</div><div className="absolute inset-x-[6%] top-[18%]"><div className="text-[8px] font-serif font-bold text-gray-900">A small studio.</div><div className="text-[4px] mt-1 text-gray-700 leading-[1.5]">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.</div></div></PageFrame>),
    (<PageFrame key="6"><div className="absolute inset-x-[6%] top-[6%] text-[3.5px] uppercase tracking-[0.32em]" style={{color:p}}>Type · alphabet</div><div className="absolute inset-x-[6%] top-[20%] grid grid-cols-9 gap-1">{['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z'].map(c=><div key={c} className="text-center text-[8px] font-serif font-bold" style={{color:p}}>{c}</div>)}</div></PageFrame>),
    (<PageFrame key="7"><div className="absolute inset-x-[6%] top-[6%] text-[3.5px] uppercase tracking-[0.32em]" style={{color:p}}>Type · numerals</div><div className="absolute inset-0 flex items-center justify-center"><div className="text-[36px] tabular-nums leading-none" style={{color:p}}>0123<br/>456789</div></div></PageFrame>),
    (<PageFrame key="8"><div className="absolute inset-x-[6%] top-[6%] text-[3.5px] uppercase tracking-[0.32em]" style={{color:p}}>Type · italics</div><div className="absolute inset-0 flex items-center justify-center"><div className="text-center"><div className="text-[40px] font-serif italic font-black leading-none">Aa</div><div className="text-[5px] uppercase tracking-[0.32em] mt-2" style={{color:p}}>italic primary</div></div></div></PageFrame>),
    (<PageFrame key="9"><div className="absolute inset-x-[6%] top-[6%] text-[3.5px] uppercase tracking-[0.32em]" style={{color:p}}>Type · cover</div><div className="absolute inset-0 flex items-center justify-center"><div className="text-center"><div className="text-[14px] font-serif font-black">{brand.name}</div><div className="text-[5px] uppercase tracking-[0.32em] mt-1" style={{color:p}}>typography system</div><div className="text-[3.5px] uppercase tracking-[0.32em] mt-2 text-gray-500">— Playfair · Inter —</div></div></div></PageFrame>),
  ];
  return [...designs, ...designs, ...designs][templateIndex] ?? designs[0];
}

// ───────────────────────────── VOICE GUIDE
export function VoiceGuideRenderer({ brand, templateIndex }: Props) {
  const p = brand.primaryColor;
  const designs = [
    (<PageFrame key="0"><div className="absolute inset-x-[6%] top-[6%] text-[3.5px] uppercase tracking-[0.32em]" style={{color:p}}>Voice · pillars</div><div className="absolute inset-x-[6%] top-[20%] grid grid-cols-2 gap-2">{['Calm','Clear','Curious','Careful'].map((w,i)=>(<div key={i} className="rounded p-2 text-center" style={{backgroundColor:i%2===0?p:'#FBF8EE',color:i%2===0?'#fff':'#0F1216'}}><div className="text-[10px] font-serif font-bold">{w}</div></div>))}</div></PageFrame>),
    (<PageFrame key="1"><div className="absolute inset-x-[6%] top-[6%] text-[3.5px] uppercase tracking-[0.32em]" style={{color:p}}>Voice · do · don't</div><div className="absolute inset-x-[6%] top-[20%] grid grid-cols-2 gap-2">{[['DO','use plain words','keep it short','be honest'],['DON\'T','use jargon','over-promise','sell hard']].map(([h,a,b,c],i)=>(<div key={i} className="border-2 rounded p-2 text-[3.5px]" style={{borderColor:i===0?p:'#0F1216',color:i===0?p:'#0F1216'}}><div className="text-[5px] font-bold uppercase">{h}</div><div className="mt-1">{a}</div><div>{b}</div><div>{c}</div></div>))}</div></PageFrame>),
    (<PageFrame key="2"><div className="absolute inset-x-[6%] top-[6%] text-[3.5px] uppercase tracking-[0.32em]" style={{color:p}}>Voice · examples</div><div className="absolute inset-x-[6%] top-[18%] space-y-2">{['"Make less. Make better."','"A small studio doing big work."','"For the people who notice."'].map((q,i)=>(<div key={i} className="text-[6px] font-serif italic font-bold leading-tight border-l-2 pl-2" style={{borderColor:p,color:i===1?p:'#0F1216'}}>{q}</div>))}</div></PageFrame>),
    (<PageFrame key="3"><div className="absolute inset-x-[6%] top-[6%] text-[3.5px] uppercase tracking-[0.32em]" style={{color:p}}>Voice · tone scale</div><div className="absolute inset-x-[6%] top-[20%] space-y-1.5">{['Formal','Professional','Friendly','Casual','Playful'].map((t,i)=>(<div key={i} className="flex items-center gap-2 text-[5px]"><span className="w-[16%]">{t}</span><div className="flex-1 h-[6px] rounded relative" style={{backgroundColor:'#FBF8EE'}}><div className="absolute inset-y-0 left-0 rounded" style={{width:i===2?'70%':'40%',backgroundColor:p}} /></div></div>))}</div></PageFrame>),
    (<PageFrame key="4"><div className="absolute inset-x-[6%] top-[6%] text-[3.5px] uppercase tracking-[0.32em]" style={{color:p}}>Voice · vocabulary</div><div className="absolute inset-x-[6%] top-[18%] space-y-2"><div className="text-[3.5px] uppercase tracking-[0.22em]" style={{color:p}}>USE</div><div className="flex flex-wrap gap-1">{['craft','careful','small','quiet','honest'].map(w=><span key={w} className="text-[5px] px-1.5 py-0.5 rounded-full text-white" style={{backgroundColor:p}}>{w}</span>)}</div><div className="text-[3.5px] uppercase tracking-[0.22em] text-gray-500 mt-2">AVOID</div><div className="flex flex-wrap gap-1">{['cutting-edge','disruptive','synergy','utilize','leverage'].map(w=><span key={w} className="text-[5px] px-1.5 py-0.5 rounded-full bg-gray-200 text-gray-500 line-through">{w}</span>)}</div></div></PageFrame>),
    (<PageFrame key="5"><div className="absolute inset-x-[6%] top-[6%] text-[3.5px] uppercase tracking-[0.32em]" style={{color:p}}>Voice · headlines</div><div className="absolute inset-x-[6%] top-[18%] space-y-2">{['Make work that lasts.','Build less. Ship more.','For careful brands.','A studio for small teams.'].map((h,i)=>(<div key={i} className="text-[8px] font-serif font-bold" style={{color:i%2===0?'#0F1216':p}}>{h}</div>))}</div></PageFrame>),
    (<PageFrame key="6"><div className="absolute inset-x-[6%] top-[6%] text-[3.5px] uppercase tracking-[0.32em]" style={{color:p}}>Voice · long-form</div><div className="absolute inset-x-[6%] top-[18%]"><div className="text-[8px] font-serif font-bold text-gray-900">A small studio.</div><div className="text-[4px] mt-1.5 text-gray-700 leading-[1.6]">We build careful brands for people who notice. We make less, make better, and make it last. Lorem ipsum dolor sit amet, consectetur.</div></div></PageFrame>),
    (<PageFrame key="7"><div className="absolute inset-x-[6%] top-[6%] text-[3.5px] uppercase tracking-[0.32em]" style={{color:p}}>Voice · ctas</div><div className="absolute inset-x-[6%] top-[20%] grid grid-cols-2 gap-1.5">{['Try it free','Get in touch','See the work','Read more','Learn how','Book a call'].map((c,i)=>(<div key={i} className="text-[5px] font-bold rounded text-center py-1" style={{backgroundColor:i%2===0?p:'#FBF8EE',color:i%2===0?'#fff':'#0F1216'}}>{c}</div>))}</div></PageFrame>),
    (<PageFrame key="8"><div className="absolute inset-x-[6%] top-[6%] text-[3.5px] uppercase tracking-[0.32em]" style={{color:p}}>Voice · cover</div><div className="absolute inset-0 flex items-center justify-center"><div className="text-center"><div className="text-[14px] font-serif font-black">{brand.name}</div><div className="text-[5px] uppercase tracking-[0.32em] mt-1" style={{color:p}}>voice & tone</div></div></div></PageFrame>),
    (<PageFrame key="9"><div className="absolute inset-x-[6%] top-[6%] text-[3.5px] uppercase tracking-[0.32em]" style={{color:p}}>Voice · before · after</div><div className="absolute inset-x-[6%] top-[20%] space-y-1.5">{[['BEFORE','We leverage cutting-edge tools.'],['AFTER','We use simple tools well.']].map(([h,t],i)=>(<div key={i} className="border-l-2 pl-2 py-1" style={{borderColor:i===0?'#999':p}}><div className="text-[3.5px] uppercase tracking-[0.22em]" style={{color:i===0?'#999':p}}>{h}</div><div className="text-[5px] mt-0.5" style={{color:i===0?'#999':'#0F1216'}}>{t}</div></div>))}</div></PageFrame>),
  ];
  return [...designs, ...designs, ...designs][templateIndex] ?? designs[0];
}

// ───────────────────────────── IMAGERY GUIDE
export function ImageryGuideRenderer({ brand, templateIndex }: Props) {
  const p = brand.primaryColor;
  const designs = [
    (<PageFrame key="0"><div className="absolute inset-x-[6%] top-[6%] text-[3.5px] uppercase tracking-[0.32em]" style={{color:p}}>Imagery · grid</div><div className="absolute inset-x-[6%] top-[16%] grid grid-cols-3 gap-1">{Array.from({length:9}).map((_,i)=>(<div key={i} className="aspect-square" style={{backgroundColor:i%3===0?p:i%3===1?'#FBF8EE':'#0F1216'}} />))}</div></PageFrame>),
    (<PageFrame key="1"><div className="absolute inset-x-[6%] top-[6%] text-[3.5px] uppercase tracking-[0.32em]" style={{color:p}}>Imagery · style</div><div className="absolute inset-x-[6%] top-[18%] grid grid-cols-2 gap-1.5">{Array.from({length:4}).map((_,i)=>(<div key={i} className="aspect-[4/3] relative overflow-hidden rounded" style={{backgroundColor: i===0?p:i===1?'#FBF8EE':i===2?'#0F1216':`${p}99`}}><div className="absolute inset-0" style={{backgroundImage:`radial-gradient(circle at ${30+i*15}% ${40-i*5}%, transparent 0%, rgba(0,0,0,0.2) 70%)`}} /></div>))}</div></PageFrame>),
    (<PageFrame key="2"><div className="absolute inset-x-[6%] top-[6%] text-[3.5px] uppercase tracking-[0.32em]" style={{color:p}}>Imagery · mood</div><div className="absolute inset-0 flex items-center justify-center"><div className="grid grid-cols-2 gap-2">{['quiet','calm','natural','crafted'].map((w,i)=>(<div key={i} className="text-center"><div className="w-[40px] aspect-square rounded-full" style={{backgroundColor:i%2===0?p:'#0F1216',opacity:0.6+i*0.1}} /><div className="text-[3.5px] uppercase tracking-[0.22em] mt-1">{w}</div></div>))}</div></div></PageFrame>),
    (<PageFrame key="3"><div className="absolute inset-x-[6%] top-[6%] text-[3.5px] uppercase tracking-[0.32em]" style={{color:p}}>Imagery · do · don't</div><div className="absolute inset-x-[6%] top-[16%] grid grid-cols-2 gap-1.5">{Array.from({length:6}).map((_,i)=>(<div key={i} className="aspect-square relative" style={{backgroundColor:i<3?p:'#FAF6EE'}}>{i>=3 && <div className="absolute inset-0 flex items-center justify-center text-[16px] text-red-400">✗</div>}</div>))}</div></PageFrame>),
    (<PageFrame key="4"><div className="absolute inset-x-[6%] top-[6%] text-[3.5px] uppercase tracking-[0.32em]" style={{color:p}}>Imagery · masking</div><div className="absolute inset-0 grid grid-cols-3 gap-2 p-[8%] mt-[4%]"><div className="rounded-full" style={{backgroundColor:p}} /><div className="rounded-md" style={{backgroundColor:p}} /><div style={{backgroundColor:p, clipPath:'polygon(50% 0%, 100% 100%, 0% 100%)'}} /></div></PageFrame>),
    (<PageFrame key="5"><div className="absolute inset-x-[6%] top-[6%] text-[3.5px] uppercase tracking-[0.32em]" style={{color:p}}>Imagery · color tint</div><div className="absolute inset-x-[6%] top-[18%] grid grid-cols-3 gap-1.5">{[1,0.7,0.4].map((o,i)=>(<div key={i} className="aspect-[4/3] rounded relative overflow-hidden"><div className="absolute inset-0 bg-[#0F1216]" /><div className="absolute inset-0" style={{backgroundColor:p,opacity:o,mixBlendMode:'multiply'}} /></div>))}</div></PageFrame>),
    (<PageFrame key="6"><div className="absolute inset-x-[6%] top-[6%] text-[3.5px] uppercase tracking-[0.32em]" style={{color:p}}>Imagery · subjects</div><div className="absolute inset-x-[6%] top-[20%] space-y-1">{['People · candid','Place · quiet','Object · close','Texture · raw'].map((s,i)=>(<div key={i} className="flex items-center gap-2 border-b py-1.5"><div className="w-[18px] h-[18px] rounded-sm" style={{backgroundColor:i%2===0?p:'#FBF8EE'}} /><div className="text-[5px] font-bold">{s}</div></div>))}</div></PageFrame>),
    (<PageFrame key="7"><div className="absolute inset-x-[6%] top-[6%] text-[3.5px] uppercase tracking-[0.32em]" style={{color:p}}>Imagery · framing</div><div className="absolute inset-x-[6%] top-[20%] grid grid-cols-3 gap-1.5">{['rule of thirds','center crop','close detail'].map((s,i)=>(<div key={i}><div className="aspect-[4/3] rounded relative" style={{backgroundColor:p}}>{i===0 && <><div className="absolute left-1/3 inset-y-0 w-[1px] bg-white/40" /><div className="absolute left-2/3 inset-y-0 w-[1px] bg-white/40" /><div className="absolute top-1/3 inset-x-0 h-[1px] bg-white/40" /><div className="absolute top-2/3 inset-x-0 h-[1px] bg-white/40" /></>}</div><div className="text-[3.5px] uppercase tracking-[0.22em] mt-1 text-gray-500">{s}</div></div>))}</div></PageFrame>),
    (<PageFrame key="8"><div className="absolute inset-x-[6%] top-[6%] text-[3.5px] uppercase tracking-[0.32em]" style={{color:p}}>Imagery · cover</div><div className="absolute inset-0 flex items-center justify-center"><div className="text-center"><div className="text-[14px] font-serif font-black">{brand.name}</div><div className="text-[5px] uppercase tracking-[0.32em] mt-1" style={{color:p}}>imagery & art direction</div></div></div></PageFrame>),
    (<PageFrame key="9"><div className="absolute inset-x-[6%] top-[6%] text-[3.5px] uppercase tracking-[0.32em]" style={{color:p}}>Imagery · ratios</div><div className="absolute inset-x-[6%] top-[20%] flex items-end gap-2">{[[1,1,'1:1'],[16,9,'16:9'],[9,16,'9:16'],[4,3,'4:3']].map(([w,h,l])=>(<div key={l as string}><div className="bg-[#FAF6EE] border" style={{width:`${(Number(w)/Math.max(Number(w),Number(h)))*40}px`,aspectRatio:`${w}/${h}`}} /><div className="text-[3px] uppercase tracking-[0.22em] mt-0.5 text-gray-500">{l}</div></div>))}</div></PageFrame>),
  ];
  return [...designs, ...designs, ...designs][templateIndex] ?? designs[0];
}

// ───────────────────────────── METADATA
export const BRAND_GUIDE_TYPES = ['logo-guide', 'color-guide', 'typography-guide', 'voice-guide', 'imagery-guide'] as const;

const baseMeta = (prefix: string) => Array.from({length:30},(_,i)=>({idSuffix:`ext-${i+1}`,name:`${prefix} Page ${i+1}`,category:'Editorial'}));
export const LOGO_GUIDE_EXTENDED = baseMeta('Logo');
export const COLOR_GUIDE_EXTENDED = baseMeta('Color');
export const TYPOGRAPHY_GUIDE_EXTENDED = baseMeta('Type');
export const VOICE_GUIDE_EXTENDED = baseMeta('Voice');
export const IMAGERY_GUIDE_EXTENDED = baseMeta('Imagery');
