import type { Brand } from '@/shared/types/brand';
import { BrandLogo } from '@/features/brandkit/components/renderers/BrandLogo';

/**
 * Envelope — Wave 2: 100 new designs (idx 0-99). #10 envelope
 * landscape (~9.5 × 4) compressed to ~2.2:1 to read in the cosmos
 * variant tile.
 *
 * Curated across 8 movements: Apple, Brutalist, Swiss/Vignelli,
 * Bento, Glassmorphism, Gradient mesh, Pentagram, Editorial mixed.
 */
interface Props { brand: Brand; templateIndex: number }

function E({ children, bg = '#FBF8EE', border = '#D8D2C2' }: { children: React.ReactNode; bg?: string; border?: string }) {
  return (
    <div className="w-full h-full bg-[#E5E0D2] flex items-center justify-center p-[6%]">
      <div className="shadow-md relative overflow-hidden border" style={{ width: '92%', aspectRatio: '2.2 / 1', backgroundColor: bg, borderColor: border }}>{children}</div>
    </div>
  );
}

export function EnvelopeExtended2Renderer({ brand, templateIndex }: Props) {
  const p = brand.primaryColor;
  const s = brand.secondaryColor || '#0F1216';
  const init = brand.name.charAt(0).toUpperCase();
  const N = brand.name.toUpperCase();
  const lower = brand.name.toLowerCase();

  const designs: React.ReactNode[] = [
    // ─── APPLE-LIKE (15)
    (<E><div className="absolute inset-0 flex items-center justify-center"><div className="text-center"><div className="text-[10px] font-light text-gray-900">Jane Smith</div><div className="text-[3.5px] uppercase tracking-[0.32em] mt-0.5 text-gray-500">567 Recipient Ave</div></div></div></E>),
    (<E><div className="absolute left-[5%] top-1/2 -translate-y-1/2"><BrandLogo brand={brand} size="xs" /></div><div className="absolute right-[5%] top-1/2 -translate-y-1/2 text-right"><div className="text-[7px] font-medium text-gray-900">Jane Smith</div><div className="text-[3.5px] mt-0.5 text-gray-500">jane@{lower}.com</div></div></E>),
    (<E><div className="absolute left-[5%] top-[15%] text-[3.5px] uppercase tracking-[0.32em] text-gray-400">{brand.name}</div><div className="absolute right-[5%] bottom-[15%] text-right"><div className="text-[8px] font-light text-gray-900">Jane Smith</div></div></E>),
    (<E bg="#F5F5F7"><div className="absolute inset-[8%] rounded-md bg-white flex items-center justify-between px-3"><BrandLogo brand={brand} size="xs" /><div className="text-right text-[3.5px] text-gray-700"><div className="font-medium">To: Jane Smith</div><div className="text-gray-500">567 Ave · NY</div></div></div></E>),
    (<E><div className="absolute left-[5%] top-[15%] flex items-center gap-1"><div className="w-[5px] h-[5px] rounded-full" style={{backgroundColor:p}} /><span className="text-[3.5px] uppercase tracking-[0.32em] text-gray-700">{brand.name} · live</span></div><div className="absolute left-[5%] bottom-[15%] text-[5px] font-light">Jane Smith</div></E>),
    (<E><div className="absolute inset-0 flex items-center px-[7%]"><div className="text-[3px] uppercase tracking-[0.5em] text-gray-400">— from {brand.name} —</div><div className="ml-auto text-right text-[7px] font-light">Jane Smith</div></div></E>),
    (<E><div className="absolute left-[5%] top-[15%] right-[5%] flex justify-between items-center text-[3.5px] uppercase tracking-[0.32em] text-gray-400"><span>{brand.name}</span><span>014 / spring 2026</span></div><div className="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 text-center"><div className="text-[10px] font-light">Jane Smith</div></div></E>),
    (<E bg="#FAFAFA"><div className="absolute inset-x-[5%] top-1/2 -translate-y-1/2 flex justify-between items-center"><div><BrandLogo brand={brand} size="xs" /></div><div className="flex-1 mx-2 h-[1px] bg-gray-300" /><div className="text-right"><div className="text-[7px] font-medium">Jane Smith</div></div></div></E>),
    (<E><div className="absolute inset-0 flex items-center justify-center"><BrandLogo brand={brand} size="md" color={p} /></div></E>),
    (<E><div className="absolute inset-x-[5%] top-1/2 -translate-y-1/2 grid grid-cols-3 items-center"><div className="text-[3.5px] uppercase tracking-[0.32em] text-gray-500">{brand.name}</div><div className="text-center"><div className="text-[7px] font-medium">Jane Smith</div></div><div className="text-right text-[3.5px] uppercase tracking-[0.32em] text-gray-400">→ NY</div></div></E>),
    (<E bg="#F2F2F7"><div className="absolute inset-[6%] bg-white rounded-lg shadow-sm flex items-center px-3"><div className="text-[3.5px] uppercase tracking-[0.32em] text-gray-400">to:</div><div className="ml-2 text-[7px] font-medium">Jane Smith</div><div className="ml-auto text-[3.5px] uppercase tracking-[0.32em]" style={{color:p}}>{brand.name}</div></div></E>),
    (<E><div className="absolute left-[5%] top-[15%]"><div className="text-[3.5px] uppercase tracking-[0.32em] text-gray-400">No.</div><div className="text-[10px] font-light tabular-nums" style={{color:p}}>014</div></div><div className="absolute right-[5%] bottom-[15%] text-right"><div className="text-[7px] font-medium">Jane Smith</div></div></E>),
    (<E><div className="absolute left-[5%] top-1/2 -translate-y-1/2 text-[3.5px] uppercase tracking-[0.4em] text-gray-400">{brand.name.toLowerCase()} → jane.smith</div></E>),
    (<E bg="#FBF8EE"><div className="absolute left-[5%] top-1/2 -translate-y-1/2"><div className="text-[3px] uppercase tracking-[0.4em] text-gray-400">{brand.name}</div></div><div className="absolute right-[5%] top-1/2 -translate-y-1/2 text-right"><div className="text-[8px] font-serif italic">Jane,</div></div></E>),
    (<E><div className="absolute left-[5%] top-[12%] text-[3.5px] uppercase tracking-[0.32em] text-gray-400">{brand.name} · 014</div><div className="absolute right-[5%] top-[12%] text-[3.5px] uppercase tracking-[0.32em]" style={{color:p}}>● delivered</div><div className="absolute inset-x-[5%] bottom-[12%] flex justify-between items-center"><div className="text-[7px] font-light">Jane Smith</div><div className="text-[3.5px] text-gray-500">567 Recipient · NY</div></div></E>),

    // ─── BRUTALIST (15)
    (<E bg="#FFEB3B" border="#000"><div className="absolute inset-0 p-[5%] font-mono"><div className="text-[5px] uppercase tracking-[0.22em] font-bold">{N} :: ENV_014</div><div className="text-[16px] font-extrabold leading-none mt-1">JANE.SMITH</div><div className="text-[3.5px] uppercase tracking-[0.22em] mt-1">→ 567_RECIPIENT_AVE</div></div></E>),
    (<E bg="#000" border="#000"><div className="absolute inset-0 p-[5%] font-mono text-[#39FF14]"><div className="text-[3.5px] uppercase tracking-[0.22em] opacity-70">root@{lower}:~$</div><div className="text-[10px] font-bold mt-1">deliver --to=jane</div><div className="text-[3.5px] uppercase tracking-[0.22em] mt-2 opacity-90">→ 567 RECIPIENT AVE NY</div></div></E>),
    (<E bg="#FF3B30" border="#000"><div className="absolute inset-0 p-[5%] text-white font-mono"><div className="text-[3.5px] uppercase tracking-[0.22em] opacity-90">!! URGENT</div><div className="text-[18px] font-extrabold leading-[0.92] mt-1">DELIVER NOW.</div><div className="absolute right-[5%] bottom-[15%] text-[3.5px] uppercase tracking-[0.22em]">→ JANE_S</div></div></E>),
    (<E bg="#FFEB3B" border="#000"><div className="absolute inset-0 grid grid-cols-2 font-mono"><div className="border-r-2 border-black p-2"><div className="text-[3.5px] uppercase tracking-[0.22em] font-bold">FROM</div><div className="text-[7px] font-extrabold mt-1">{N}</div></div><div className="p-2"><div className="text-[3.5px] uppercase tracking-[0.22em] font-bold text-right">TO</div><div className="text-[7px] font-extrabold mt-1 text-right">JANE.SMITH</div></div></div></E>),
    (<E bg="#fff" border="#000"><div className="absolute inset-0 font-mono p-[5%]" style={{borderTop:'10px solid #000',borderBottom:'10px solid #000'}}><div className="text-[5px] uppercase tracking-[0.22em] font-bold">{N} → JANE_SMITH</div><div className="text-[10px] font-extrabold mt-1">567 RECIPIENT</div></div></E>),
    (<E bg="#39FF14" border="#000"><div className="absolute inset-0 p-[5%] font-mono"><div className="text-[3.5px] uppercase tracking-[0.22em] font-bold">[STATUS: SENDING]</div><div className="text-[14px] font-extrabold mt-1 leading-none">→ JANE_S</div><div className="text-[3.5px] uppercase tracking-[0.22em] mt-1 font-bold">[████████□□]</div></div></E>),
    (<E bg="#fff" border="#000"><div className="absolute inset-0 grid grid-cols-3 font-mono"><div className="bg-black text-white p-1.5 text-[3.5px] uppercase tracking-[0.22em] font-bold">FROM:</div><div className="border-l-2 border-r-2 border-black p-1.5 text-[3.5px] uppercase tracking-[0.22em] font-bold">{brand.name.toUpperCase().slice(0,8)}</div><div className="bg-black text-white p-1.5 text-[3.5px] uppercase tracking-[0.22em] font-bold text-right">TO: JANE_S</div></div></E>),
    (<E bg="#fff" border="#000"><div className="absolute inset-0 p-[5%] font-mono"><div className="text-[3.5px] uppercase tracking-[0.22em] font-bold border-b-2 border-black pb-0.5">FILE: ENV_014.{lower}</div><div className="text-[12px] font-extrabold mt-2 leading-none">DEAR_JANE,</div><div className="absolute right-[5%] bottom-[15%] text-[3.5px] uppercase tracking-[0.22em] font-bold" style={{color:p}}>// EOF</div></div></E>),
    (<E bg="#FFEB3B" border="#000"><div className="absolute inset-0 flex items-center justify-center"><div className="-rotate-3 border-2 border-black px-2 py-0.5"><span className="text-[5px] uppercase tracking-[0.22em] font-mono font-bold">→ JANE.SMITH ({N})</span></div></div></E>),
    (<E bg="#fff" border="#000" ><div className="absolute inset-0" style={{ background: 'repeating-linear-gradient(0deg, #000 0 2px, #fff 2px 4px)' }}><div className="absolute inset-[12%] bg-white p-2 font-mono"><div className="text-[5px] uppercase tracking-[0.22em] font-bold">{N} ENV/014</div><div className="text-[10px] font-extrabold mt-1">DEAR JANE.</div></div></div></E>),
    (<E bg="#000" border="#000"><div className="absolute inset-0 p-[5%] text-yellow-300 font-mono"><div className="text-[5px] uppercase tracking-[0.22em] opacity-80">[parcel #014 · live]</div><div className="text-[16px] font-extrabold leading-none mt-1">→ JANE.S</div></div></E>),
    (<E bg="#fff" border="#000"><div className="absolute inset-0 p-[5%] grid grid-cols-3 grid-rows-2 gap-0 border-2 border-black font-mono">{['F','R','M','T','O','S'].map((c,i)=><div key={i} className="border border-black flex items-center justify-center text-[10px] font-extrabold" style={{backgroundColor:i===0||i===4?p:'#fff',color:i===0||i===4?'#fff':'#000'}}>{c}</div>)}</div></E>),
    (<E bg="#FFEB3B" border="#000"><div className="absolute inset-0 p-[5%] font-mono"><div className="grid grid-cols-2 gap-1"><div className="bg-black text-white p-1 text-[3.5px] uppercase">SENDER</div><div className="border-2 border-black p-1 text-[3.5px] uppercase text-right">RECIPIENT</div></div><div className="text-[10px] font-extrabold mt-2 leading-none">{N}</div><div className="text-[10px] font-extrabold leading-none">→ JANE.S</div></div></E>),
    (<E bg="#fff" border="#000"><div className="absolute inset-0 p-[5%] font-mono"><div className="text-[20px] font-extrabold leading-[0.85] uppercase">JANE,<br/><span style={{color:p}}>READ.</span></div></div></E>),
    (<E bg="#1F1F1F" border="#000"><div className="absolute inset-0 p-[5%] text-white font-mono"><div className="text-[3.5px] uppercase tracking-[0.32em] opacity-70">— terminal_envelope —</div><div className="text-[7px] mt-2"><span className="opacity-60">user@</span><span style={{color:p}}>{lower}</span></div><div className="text-[10px] font-extrabold mt-1">→ jane.smith</div></div></E>),

    // ─── SWISS / VIGNELLI (15)
    (<E><div className="absolute inset-x-[5%] top-[10%] right-[5%] flex justify-between items-end border-b-2 border-black pb-0.5"><span className="text-[3.5px] uppercase tracking-[0.32em] font-bold">{brand.name}</span><span className="text-[3.5px] uppercase tracking-[0.32em] text-gray-400">N° 014</span></div><div className="absolute inset-x-[5%] bottom-[15%] grid grid-cols-12 gap-1 text-[3.5px] uppercase tracking-[0.22em]"><span className="col-span-2 text-gray-400">to</span><span className="col-span-10">Jane Smith · 567 Recipient Ave · NY</span></div></E>),
    (<E><div className="absolute left-[5%] top-1/2 -translate-y-1/2 grid grid-cols-12 right-[5%] gap-x-1"><div className="col-span-2 text-[3.5px] uppercase tracking-[0.32em] text-gray-400">name</div><div className="col-span-4 text-[7px] font-bold">Jane Smith</div><div className="col-span-2 text-[3.5px] uppercase tracking-[0.32em] text-gray-400">addr</div><div className="col-span-4 text-[5px]">567 Recipient Ave</div></div></E>),
    (<E><div className="absolute left-[5%] top-1/2 -translate-y-1/2 right-[5%] flex justify-between items-center border-y-2 border-black py-0.5"><div className="text-[5px] uppercase tracking-[0.32em] font-bold">{brand.name}</div><div className="text-[5px] uppercase tracking-[0.32em] text-gray-400">N° 014</div><div className="text-[5px] uppercase tracking-[0.32em] font-bold">JANE SMITH</div></div></E>),
    (<E><div className="absolute left-[5%] top-1/2 -translate-y-1/2 right-[5%]"><div className="text-[3.5px] uppercase tracking-[0.4em] text-gray-400 mb-1">— official correspondence —</div><div className="grid grid-cols-2"><div><div className="text-[3.5px] uppercase tracking-[0.32em] text-gray-400">from</div><div className="text-[5px] font-bold mt-0.5">{brand.name}</div></div><div className="text-right"><div className="text-[3.5px] uppercase tracking-[0.32em] text-gray-400">to</div><div className="text-[5px] font-bold mt-0.5">Jane Smith</div></div></div></div></E>),
    (<E><div className="absolute left-[5%] right-[5%] top-[12%] grid grid-cols-12 text-[3.5px] uppercase tracking-[0.32em] font-bold border-b-2 border-black pb-0.5"><span className="col-span-3">{brand.name}</span><span className="col-span-6 text-center">CORRESPONDENCE 014</span><span className="col-span-3 text-right">2026</span></div><div className="absolute inset-x-[5%] bottom-[15%] text-center text-[7px] font-bold">Jane Smith — 567 Recipient Ave · NY</div></E>),
    (<E><div className="absolute left-[5%] top-[15%] bottom-[15%] w-[1px] bg-black" /><div className="absolute left-[7%] top-[15%]"><BrandLogo brand={brand} size="xs" /></div><div className="absolute left-[7%] bottom-[15%]"><div className="text-[3.5px] uppercase tracking-[0.32em] font-bold">{brand.name}</div></div><div className="absolute right-[5%] top-1/2 -translate-y-1/2 text-right"><div className="text-[8px] font-bold leading-none">Jane Smith</div><div className="text-[3.5px] uppercase tracking-[0.32em] mt-0.5" style={{color:p}}>VP</div></div></E>),
    (<E><div className="absolute inset-x-[5%] top-[12%] flex items-center"><span className="text-[3.5px] uppercase tracking-[0.32em] font-bold">{brand.name}</span><div className="flex-1 h-[1px] bg-black mx-2" /><span className="text-[3.5px] uppercase tracking-[0.32em] font-bold">→ JANE</span></div><div className="absolute inset-x-[5%] bottom-[12%] grid grid-cols-3 text-[3.5px] uppercase tracking-[0.32em] border-t border-black pt-0.5"><span>014</span><span className="text-center">2026</span><span className="text-right">{lower}.com</span></div></E>),
    (<E bg="#F5F2E8"><div className="absolute inset-x-[5%] top-1/2 -translate-y-1/2 text-center"><div className="text-[3.5px] uppercase tracking-[0.5em] text-gray-700">— {brand.name} —</div><div className="text-[7px] font-serif font-bold mt-1">Jane Smith</div></div></E>),
    (<E><div className="absolute inset-x-[5%] top-[12%] flex items-center gap-2"><div className="text-[10px] font-bold tabular-nums" style={{color:p}}>14</div><div className="text-[3.5px] uppercase tracking-[0.32em] text-gray-400">{brand.name} · spring 2026</div></div><div className="absolute inset-x-[5%] bottom-[12%] grid grid-cols-2 text-[3.5px] uppercase tracking-[0.32em]"><span>FROM · {brand.name}</span><span className="text-right">TO · JANE SMITH</span></div></E>),
    (<E><div className="absolute inset-x-[5%] top-[15%] grid grid-cols-12 gap-1"><div className="col-span-3 text-[3.5px] uppercase tracking-[0.32em] font-bold border-r border-black pr-1">{brand.name}</div><div className="col-span-6 text-[3.5px] uppercase tracking-[0.32em] text-center">N° 014</div><div className="col-span-3 text-[3.5px] uppercase tracking-[0.32em] text-right border-l border-black pl-1">2026</div></div><div className="absolute inset-x-[5%] bottom-[15%] text-center text-[7px] font-bold">JANE SMITH</div></E>),
    (<E><div className="absolute inset-0 flex items-center"><div className="w-[20%] h-full bg-black flex items-center justify-center"><span className="text-white text-[10px] font-bold">{init}</span></div><div className="flex-1 px-3"><div className="text-[3.5px] uppercase tracking-[0.32em] font-bold">{brand.name}</div><div className="text-[7px] font-bold mt-0.5">JANE SMITH</div><div className="text-[3.5px] uppercase tracking-[0.32em] text-gray-500">567 RECIPIENT AVE</div></div></div></E>),
    (<E><div className="absolute inset-x-[5%] top-[12%] grid grid-cols-12 gap-1"><div className="col-span-12 text-[3.5px] uppercase tracking-[0.32em] font-bold border-b-2 border-black pb-0.5">{brand.name} · ENVELOPE A · 014</div></div><div className="absolute inset-x-[5%] top-1/2 -translate-y-1/2 text-[7px] font-bold">JANE SMITH · 567 RECIPIENT AVE</div></E>),
    (<E><div className="absolute inset-x-[5%] top-[15%] flex items-baseline gap-2"><div className="text-[3.5px] uppercase tracking-[0.32em] font-bold">{brand.name}</div><div className="flex-1 h-[1px] bg-black" /><div className="text-[3.5px] uppercase tracking-[0.32em]">N° 014</div></div><div className="absolute inset-x-[5%] top-[40%] text-[7px] font-bold">Jane Smith</div><div className="absolute inset-x-[5%] bottom-[15%] text-[3.5px] uppercase tracking-[0.32em] text-gray-500">567 RECIPIENT AVE · NY 10010</div></E>),
    (<E><div className="absolute inset-x-[5%] top-[12%] text-[3.5px] uppercase tracking-[0.5em] font-bold border-b-2 border-black pb-0.5 text-center">{brand.name} CO. · CORRESPONDENCE</div><div className="absolute inset-x-[5%] bottom-[12%] text-[5px] uppercase tracking-[0.4em] text-center">→ JANE SMITH · 567 RECIPIENT AVE · NY</div></E>),
    (<E><div className="absolute inset-x-[5%] top-[12%] flex justify-between text-[3.5px] uppercase tracking-[0.32em] font-bold"><span>{brand.name}</span><span>014</span><span>JANE.S</span></div><div className="absolute inset-x-[5%] top-1/2 -translate-y-1/2 grid grid-cols-3 gap-2"><div className="border-2 border-black p-1 text-center"><div className="text-[3.5px] uppercase tracking-[0.32em]">FROM</div></div><div className="border-2 border-black p-1 text-center"><div className="text-[3.5px] uppercase tracking-[0.32em]">·</div></div><div className="border-2 border-black p-1 text-center"><div className="text-[3.5px] uppercase tracking-[0.32em]">TO</div></div></div></E>),

    // ─── BENTO / MODULAR (10)
    (<E bg="#F5F5F7"><div className="absolute inset-[6%] grid grid-cols-4 grid-rows-2 gap-1"><div className="row-span-2 rounded-md flex items-center justify-center" style={{backgroundColor:p}}><span className="text-white text-[10px] font-bold">{init}</span></div><div className="col-span-2 rounded-md bg-white flex items-center px-2"><span className="text-[7px] font-bold">Jane Smith</span></div><div className="rounded-md bg-[#0F1216]" /><div className="col-span-3 rounded-md bg-white flex items-center px-2"><span className="text-[3.5px] uppercase tracking-[0.32em] text-gray-500">567 Recipient Ave</span></div></div></E>),
    (<E bg="#FBF8EE"><div className="absolute inset-[5%] grid grid-cols-5 grid-rows-2 gap-1"><div className="rounded bg-white border flex items-center justify-center"><BrandLogo brand={brand} size="xs" /></div><div className="col-span-3 rounded bg-white border p-1.5 flex items-center"><span className="text-[7px] font-bold">Jane Smith</span></div><div className="rounded flex items-center justify-center" style={{backgroundColor:p}}><span className="text-white text-[3.5px] uppercase tracking-[0.32em]">VP</span></div><div className="col-span-5 rounded bg-[#0F1216] flex items-center px-2"><span className="text-white text-[3.5px] uppercase tracking-[0.32em] opacity-80">→ 567 RECIPIENT · NY</span></div></div></E>),
    (<E><div className="absolute inset-[6%] grid grid-cols-3 grid-rows-2 gap-1.5"><div className="row-span-2 rounded-2xl flex items-center justify-center" style={{backgroundColor:p}}><div className="text-white text-[5px] uppercase tracking-[0.32em]">{brand.name}</div></div><div className="col-span-2 rounded-2xl bg-[#FBF8EE] p-2"><div className="text-[7px] font-bold">Jane Smith</div></div><div className="col-span-2 rounded-2xl bg-white border p-2"><div className="text-[3.5px] uppercase tracking-[0.32em] text-gray-500">567 Recipient Ave · NY 10010</div></div></div></E>),
    (<E bg="#0F1216"><div className="absolute inset-[6%] grid grid-cols-4 grid-rows-2 gap-1"><div className="rounded flex items-center justify-center" style={{backgroundColor:p}}><BrandLogo brand={brand} size="xs" color="#fff" /></div><div className="col-span-3 rounded bg-[#1F2429] p-1.5 flex items-center"><span className="text-white text-[7px] font-bold">Jane Smith</span></div><div className="col-span-4 rounded bg-[#1F2429] p-1.5 flex items-center"><span className="text-white text-[3.5px] uppercase tracking-[0.32em] opacity-80">jane@{lower}.com · 567 RECIPIENT</span></div></div></E>),
    (<E bg="#F5F5F7"><div className="absolute inset-[5%] grid grid-cols-6 grid-rows-2 gap-1"><div className="col-span-2 row-span-2 rounded-xl bg-white border flex items-center justify-center"><BrandLogo brand={brand} size="md" color={p} /></div><div className="col-span-3 rounded-xl flex items-center justify-center" style={{backgroundColor:p}}><span className="text-white text-[7px] font-bold">Jane Smith</span></div><div className="rounded-xl bg-[#0F1216]" /><div className="col-span-4 rounded-xl bg-white border p-1.5"><span className="text-[3.5px] uppercase tracking-[0.32em] text-gray-500">567 RECIPIENT · NY</span></div></div></E>),
    (<E><div className="absolute inset-[6%] grid grid-cols-5 grid-rows-2 gap-1"><div className="col-span-2 rounded-xl bg-white border flex items-center justify-center"><span className="text-[5px] uppercase tracking-[0.32em]" style={{color:p}}>FROM · {brand.name}</span></div><div className="col-span-2 rounded-xl bg-white border flex items-center justify-center"><span className="text-[5px] uppercase tracking-[0.32em]" style={{color:p}}>TO · JANE</span></div><div className="rounded-xl flex items-center justify-center" style={{backgroundColor:p}}><span className="text-white text-[10px] font-bold">14</span></div><div className="col-span-5 rounded-xl bg-[#FBF8EE] p-1.5"><div className="text-[3.5px] uppercase tracking-[0.32em] text-gray-500">567 Recipient Ave · NY 10010</div></div></div></E>),
    (<E bg="#FBF8EE"><div className="absolute inset-[6%] grid grid-cols-3 grid-rows-2 gap-1"><div className="rounded-2xl bg-white border p-2"><div className="text-[3.5px] uppercase tracking-[0.32em]" style={{color:p}}>0/2</div><div className="text-[5px] font-bold mt-0.5">{brand.name}</div></div><div className="rounded-2xl bg-white border p-2"><div className="text-[3.5px] uppercase tracking-[0.32em]" style={{color:p}}>→</div></div><div className="rounded-2xl bg-white border p-2"><div className="text-[3.5px] uppercase tracking-[0.32em]" style={{color:p}}>2/2</div><div className="text-[5px] font-bold mt-0.5">Jane Smith</div></div><div className="col-span-3 rounded-2xl bg-[#0F1216] p-1.5"><span className="text-white text-[3.5px] uppercase tracking-[0.32em] opacity-80">567 RECIPIENT AVE</span></div></div></E>),
    (<E><div className="absolute inset-[6%] grid grid-cols-2 grid-rows-3 gap-1"><div className="row-span-3 rounded-2xl bg-[#FBF8EE] p-2 flex flex-col justify-between"><BrandLogo brand={brand} size="xs" /><div><div className="text-[3.5px] uppercase tracking-[0.32em]" style={{color:p}}>{brand.name}</div></div></div><div className="rounded-2xl bg-white border flex items-center justify-center"><span className="text-[5px] uppercase tracking-[0.32em] text-gray-500">to</span></div><div className="row-span-2 rounded-2xl flex items-center justify-center" style={{backgroundColor:p}}><div className="text-center text-white"><div className="text-[8px] font-bold">Jane Smith</div></div></div></div></E>),
    (<E bg="#0F1216"><div className="absolute inset-[6%] grid grid-cols-4 grid-rows-2 gap-1"><div className="col-span-3 rounded bg-[#1F2429] p-1.5 flex items-center"><span className="text-white text-[5px] uppercase tracking-[0.32em] opacity-90">{brand.name} → JANE.SMITH</span></div><div className="rounded flex items-center justify-center" style={{backgroundColor:p}}><span className="text-white text-[7px] font-bold">14</span></div><div className="col-span-4 rounded bg-[#1F2429] p-1.5 flex items-center"><span className="text-white text-[3.5px] uppercase tracking-[0.32em] opacity-70">567 RECIPIENT AVE · NY 10010 · USA</span></div></div></E>),
    (<E bg="#F5F5F7"><div className="absolute inset-[6%] grid grid-cols-3 grid-rows-2 gap-1.5"><div className="col-span-3 rounded-lg flex items-center justify-between px-2" style={{backgroundColor:p}}><BrandLogo brand={brand} size="xs" color="#fff" /><span className="text-white text-[3.5px] uppercase tracking-[0.32em]">{brand.name} · 014</span></div><div className="col-span-2 rounded-lg bg-white p-1.5"><div className="text-[7px] font-bold">Jane Smith</div></div><div className="rounded-lg bg-[#0F1216] flex items-center justify-center"><span className="text-white text-[3.5px] uppercase tracking-[0.32em]">→</span></div></div></E>),

    // ─── GLASSMORPHISM (10)
    (<E bg={p}><div className="absolute inset-0" style={{ background: `linear-gradient(135deg, ${p}, ${s})` }} /><div className="absolute inset-[6%] rounded-md backdrop-blur-md bg-white/30 border border-white/50 flex items-center justify-center"><div className="text-white text-[8px] font-light">Jane Smith · 567 Recipient</div></div></E>),
    (<E bg="#0F1216"><div className="absolute inset-0" style={{ background: `radial-gradient(80% 80% at 30% 50%, ${p} 0%, transparent 70%)` }} /><div className="absolute inset-[8%] rounded-2xl backdrop-blur-md bg-white/10 border border-white/20 flex items-center justify-between px-3"><BrandLogo brand={brand} size="xs" color="#fff" /><div className="text-right text-white"><div className="text-[7px] font-light">Jane Smith</div></div></div></E>),
    (<E><div className="absolute inset-0" style={{ background: `linear-gradient(180deg, ${p} 0%, ${p}99 100%)` }} /><div className="absolute inset-[8%] rounded-md backdrop-blur-lg bg-white/40 border border-white/60 flex items-center justify-center"><div className="text-center text-gray-900"><div className="text-[7px] font-bold">Jane Smith</div></div></div></E>),
    (<E><div className="absolute inset-0 grid grid-cols-3"><div style={{backgroundColor:p}} /><div className="bg-white" /><div style={{backgroundColor:s}} /></div><div className="absolute inset-[10%] rounded-md backdrop-blur-2xl bg-white/30 border border-white/50 flex items-center justify-center"><span className="text-[7px] font-bold text-white">Jane Smith</span></div></E>),
    (<E><div className="absolute inset-0" style={{ background: `conic-gradient(from 0deg, ${p}, ${s}, ${p})` }} /><div className="absolute inset-[8%] rounded-2xl backdrop-blur-3xl bg-white/40 border border-white/60 flex items-center justify-between px-3"><div className="text-[5px] uppercase tracking-[0.32em] text-gray-700">{brand.name} · 014</div><div className="text-[7px] font-light">Jane Smith</div></div></E>),
    (<E bg="#fff"><div className="absolute inset-0" style={{ background: `radial-gradient(circle at 80% 50%, ${p} 0%, transparent 60%)` }} /><div className="absolute inset-[8%] rounded-md backdrop-blur-md bg-white/50 border border-white/70 flex items-center justify-center"><div className="text-[7px] font-light text-gray-900">Jane Smith</div></div></E>),
    (<E bg="#1F1F1F"><div className="absolute inset-0" style={{ background: `radial-gradient(40% 80% at 30% 50%, ${p}AA 0%, transparent 100%), radial-gradient(40% 80% at 70% 50%, ${s}AA 0%, transparent 100%)` }} /><div className="absolute inset-[8%] rounded-2xl backdrop-blur-md bg-white/5 border border-white/15 flex items-center justify-center"><div className="text-white text-[7px] font-light">Jane Smith</div></div></E>),
    (<E><div className="absolute inset-0" style={{background:`linear-gradient(180deg, ${p}, ${p}AA, transparent)`,backgroundColor:'#FBF8EE'}} /><div className="absolute inset-[8%] rounded-md backdrop-blur-lg bg-white/40 border border-white/70 flex items-center px-3"><span className="text-[7px] font-medium">Jane Smith · 567 Recipient</span></div></E>),
    (<E bg="#fff"><div className="absolute -left-[10%] top-0 bottom-0 w-[60%] rounded-full" style={{ background: `radial-gradient(circle, ${p}55, transparent 70%)` }} /><div className="absolute right-[6%] top-1/2 -translate-y-1/2 left-[40%] rounded-md backdrop-blur-lg bg-white/60 border border-white/70 p-2"><div className="text-[3.5px] uppercase tracking-[0.32em]" style={{color:p}}>{brand.name}</div><div className="text-[7px] font-bold mt-0.5">Jane Smith</div></div></E>),
    (<E bg="#0F1216"><div className="absolute inset-0" style={{background:`linear-gradient(45deg, transparent 0%, ${p}55 50%, transparent 100%)`}} /><div className="absolute inset-[8%] rounded-md backdrop-blur-xl bg-white/10 border border-white/20 flex items-center justify-between px-3"><div className="text-white text-[3.5px] uppercase tracking-[0.32em] opacity-80">{brand.name}</div><div className="text-white text-[7px] font-light">Jane Smith</div></div></E>),

    // ─── GRADIENT MESH (10)
    (<E bg="#FBF8EE"><div className="absolute inset-0" style={{ background: `radial-gradient(120% 80% at 20% 50%, ${p} 0%, transparent 60%), radial-gradient(120% 80% at 80% 50%, ${s} 0%, transparent 60%), #FBF8EE` }} /><div className="absolute inset-0 flex items-center justify-center"><span className="text-[8px] font-light text-gray-900">Jane Smith</span></div></E>),
    (<E><div className="absolute inset-0" style={{background:`linear-gradient(135deg, ${p}, ${s})`}} /><div className="absolute inset-[6%] flex justify-between items-center"><BrandLogo brand={brand} size="xs" color="#fff" /><div className="text-right text-white"><div className="text-[7px] font-light">Jane Smith</div></div></div></E>),
    (<E><div className="absolute inset-0" style={{background:`conic-gradient(from 0deg at 30% 70%, ${p}, ${s}, ${p})`}} /><div className="absolute inset-x-[6%] bottom-[15%]"><div className="text-white text-[8px] font-bold">Jane Smith</div></div></E>),
    (<E><div className="absolute inset-0 flex"><div className="w-1/2" style={{background:`linear-gradient(180deg, ${p}, ${s})`}} /><div className="w-1/2 bg-white flex items-center pl-3"><span className="text-[7px] font-bold">Jane Smith</span></div></div></E>),
    (<E><div className="absolute inset-0" style={{background:`linear-gradient(105deg, ${p} 0%, ${p} 38%, white 38.5%, white 100%)`}} /><div className="absolute right-[6%] top-1/2 -translate-y-1/2 text-right"><div className="text-[7px] font-medium">Jane Smith</div></div></E>),
    (<E><div className="absolute inset-0" style={{background:`linear-gradient(180deg, ${p} 0%, ${p}66 50%, white 100%)`}} /><div className="absolute inset-x-[6%] top-1/2 -translate-y-1/2 text-white text-[7px] font-light">Jane Smith · 567 Recipient</div></E>),
    (<E bg="#0F1216"><div className="absolute -inset-[10%]" style={{background:`radial-gradient(circle at 30% 50%, ${p}, transparent 50%), radial-gradient(circle at 70% 50%, ${s}, transparent 50%)`,opacity:0.7}} /><div className="absolute inset-x-[6%] top-1/2 -translate-y-1/2 flex justify-between items-center"><BrandLogo brand={brand} size="xs" color="#fff" /><span className="text-white text-[7px] font-light">Jane Smith</span></div></E>),
    (<E><div className="absolute inset-0" style={{background:`linear-gradient(45deg, ${p}, transparent), linear-gradient(135deg, ${s}, transparent), #FBF8EE`}} /><div className="absolute inset-x-[6%] bottom-[15%]"><div className="text-[7px] font-light text-gray-900">Jane Smith</div></div></E>),
    (<E><div className="absolute inset-0" style={{background:`linear-gradient(225deg, ${p}, ${s}, ${p})`}} /><div className="absolute inset-[6%] rounded-md bg-black/30 backdrop-blur-sm border border-white/20 flex items-center justify-center"><div className="text-white text-[7px] font-light">Jane Smith</div></div></E>),
    (<E><div className="absolute inset-0" style={{background:`radial-gradient(ellipse at 50% 0%, ${p}, transparent 70%)`,backgroundColor:'#FBF8EE'}} /><div className="absolute inset-x-[6%] bottom-[15%] flex justify-between items-end"><BrandLogo brand={brand} size="xs" /><div className="text-right"><div className="text-[7px] font-medium">Jane Smith</div></div></div></E>),

    // ─── PENTAGRAM-FLEXIBLE (10)
    (<E><div className="absolute inset-x-[5%] top-[15%] grid grid-cols-12 gap-[1px]">{Array.from({length:12}).map((_,i)=><div key={i} className="h-[3px]" style={{backgroundColor:i<7?p:'#E5E0D2'}} />)}</div><div className="absolute inset-x-[5%] bottom-[15%]"><div className="text-[7px] font-bold">Jane Smith</div></div></E>),
    (<E><div className="absolute inset-x-[5%] top-[15%] grid grid-cols-8 gap-[1px]">{Array.from({length:8}).map((_,i)=><div key={i} className="aspect-square" style={{backgroundColor:[1,3,5].includes(i)?p:[0,2,4,6].includes(i)?'#0F1216':'#FBF8EE'}} />)}</div><div className="absolute inset-x-[5%] bottom-[15%]"><div className="text-[7px] font-bold">Jane Smith · 567 Recipient</div></div></E>),
    (<E><div className="absolute left-0 top-0 bottom-0 w-[6%]" style={{backgroundColor:p}} /><div className="absolute left-[6%] top-0 bottom-0 w-[6%] bg-[#0F1216]" /><div className="absolute left-[16%] top-1/2 -translate-y-1/2"><div className="text-[3.5px] uppercase tracking-[0.32em] font-bold">{brand.name}</div><div className="text-[7px] font-bold mt-0.5">Jane Smith</div></div></E>),
    (<E><div className="absolute inset-x-[5%] top-[15%] flex gap-1">{Array.from({length:5}).map((_,i)=><div key={i} className="h-[10px] flex-1" style={{backgroundColor:i===2?p:i%2===0?'#0F1216':'#FBF8EE'}} />)}</div><div className="absolute inset-x-[5%] bottom-[15%]"><div className="text-[7px] font-bold">Jane Smith · NY</div></div></E>),
    (<E><div className="absolute left-[5%] top-1/2 -translate-y-1/2 grid grid-cols-3 gap-1">{Array.from({length:3}).map((_,i)=><div key={i} className="w-[8px] aspect-square rounded-full" style={{backgroundColor:i===1?p:`${p}33`}} />)}</div><div className="absolute right-[5%] top-1/2 -translate-y-1/2"><div className="text-[7px] font-bold">Jane Smith</div></div></E>),
    (<E><div className="absolute inset-x-[5%] top-[15%] flex flex-wrap gap-1">{Array.from({length:18}).map((_,i)=><div key={i} className="w-[4px] h-[4px] rounded-full" style={{backgroundColor:i%4===0?p:i%4===1?'#0F1216':'#E5E0D2'}} />)}</div><div className="absolute inset-x-[5%] bottom-[15%]"><div className="text-[7px] font-bold">Jane Smith</div></div></E>),
    (<E><div className="absolute inset-x-[5%] top-[12%] h-[16px] grid grid-cols-12">{Array.from({length:12}).map((_,i)=>(<div key={i} className="border-r border-[#E5E0D2] last:border-r-0 flex items-end p-[1px]"><div className="w-full" style={{height:`${30+(i*7)%60}%`,backgroundColor:i===5?p:'#0F1216'}} /></div>))}</div><div className="absolute inset-x-[5%] bottom-[15%]"><div className="text-[7px] font-bold">Jane Smith</div></div></E>),
    (<E><div className="absolute inset-x-[5%] top-[15%] grid grid-cols-2 gap-1"><div className="aspect-[3/1]" style={{backgroundColor:p}} /><div className="aspect-[3/1] bg-[#0F1216]" /></div><div className="absolute inset-x-[5%] bottom-[15%] grid grid-cols-3 gap-1"><div className="aspect-square" style={{backgroundColor:`${p}66`}} /><div className="aspect-square bg-[#FBF8EE]" /><div className="aspect-square" style={{backgroundColor:p}} /></div></E>),
    (<E><div className="absolute inset-x-[5%] top-[12%] grid grid-cols-12 grid-rows-3 gap-[2px]">{Array.from({length:36}).map((_,i)=><div key={i} className="h-[3px]" style={{backgroundColor:[2,5,9,11,15,16,18,22,25,28,29].includes(i)?p:'transparent'}} />)}</div><div className="absolute inset-x-[5%] bottom-[15%] text-[3.5px] uppercase tracking-[0.32em] flex justify-between"><span>{brand.name}</span><span>Jane Smith</span></div></E>),
    (<E><div className="absolute inset-x-[5%] top-[15%] flex items-center gap-1.5"><div className="w-[16px] h-[16px] rounded-full flex items-center justify-center text-white text-[8px] font-bold" style={{backgroundColor:p}}>{init}</div><div className="text-[3.5px] uppercase tracking-[0.32em] font-bold">{brand.name} · ENVELOPE 014</div></div><div className="absolute inset-x-[5%] bottom-[15%] text-[7px] font-bold">→ Jane Smith · 567 Recipient</div></E>),

    // ─── EDITORIAL MIXED (15)
    (<E><div className="absolute inset-x-[5%] top-1/2 -translate-y-1/2"><div className="text-[14px] font-serif italic font-bold leading-none" style={{color:p}}>"</div><div className="text-[5px] mt-0.5 italic">— from {brand.name}</div></div><div className="absolute right-[5%] top-1/2 -translate-y-1/2 text-right"><div className="text-[7px] font-bold">Jane Smith</div></div></E>),
    (<E><div className="absolute right-0 top-0 w-[20%] h-full" style={{backgroundColor:p}} /><div className="absolute inset-x-[5%] right-[27%] top-1/2 -translate-y-1/2"><div className="text-[3.5px] uppercase tracking-[0.32em] text-gray-400">{brand.name} · 014</div><div className="text-[8px] font-serif font-bold mt-0.5">Jane Smith</div></div></E>),
    (<E><div className="absolute left-0 top-0 w-1/2 h-full bg-[#FBF8EE]" /><div className="absolute right-0 top-0 w-1/2 h-full bg-white" /><div className="absolute left-[10%] top-1/2 -translate-y-1/2"><div className="text-[5px] uppercase tracking-[0.32em] text-gray-500">FROM</div><div className="text-[7px] font-bold mt-0.5">{brand.name}</div></div><div className="absolute right-[10%] top-1/2 -translate-y-1/2 text-right"><div className="text-[5px] uppercase tracking-[0.32em] text-gray-500">TO</div><div className="text-[7px] font-bold mt-0.5">Jane Smith</div></div></E>),
    (<E><div className="absolute left-[5%] top-1/2 -translate-y-1/2 font-serif font-black leading-none" style={{color:`${p}11`,fontSize:'56px'}}>14</div><div className="absolute right-[5%] top-1/2 -translate-y-1/2 text-right"><div className="text-[7px] font-bold">Jane Smith</div></div></E>),
    (<E><div className="absolute inset-x-[5%] top-[20%] right-[5%] flex justify-between items-baseline"><div className="text-[10px] font-serif font-bold">An Envelope</div><div className="text-[3.5px] uppercase tracking-[0.32em] text-gray-400">№ 014</div></div><div className="absolute left-[5%] right-[5%] top-[55%] h-[1px]" style={{backgroundColor:p}} /><div className="absolute inset-x-[5%] bottom-[15%] text-[7px] font-bold">Jane Smith · 567 Recipient</div></E>),
    (<E><div className="absolute inset-x-[5%] top-1/2 -translate-y-1/2 grid grid-cols-3 gap-2 text-[3.5px]"><div><div className="uppercase tracking-[0.32em] text-gray-400">no.</div><div className="text-[7px] font-bold mt-0.5">14</div></div><div><div className="uppercase tracking-[0.32em] text-gray-400">to</div><div className="text-[5px] font-bold mt-0.5">Jane Smith</div></div><div className="text-right"><div className="uppercase tracking-[0.32em] text-gray-400">@</div><div className="text-[5px] font-mono mt-0.5">jane@{lower}</div></div></div></E>),
    (<E><div className="absolute inset-x-[5%] top-[15%] border-y-2 py-1 border-black"><div className="text-center text-[5px] uppercase tracking-[0.32em] font-bold">{brand.name} JOURNAL · ENVELOPE 014</div></div><div className="absolute inset-x-[5%] bottom-[15%] text-center text-[7px] font-bold">Jane Smith · 567 Recipient</div></E>),
    (<E bg="#FBF8EE"><div className="absolute left-[5%] top-1/2 -translate-y-1/2"><BrandLogo brand={brand} size="xs" /><div className="text-[3.5px] uppercase tracking-[0.32em] mt-0.5" style={{color:p}}>spring · 2026</div></div><div className="absolute right-[5%] top-1/2 -translate-y-1/2 text-right"><div className="text-[8px] font-serif font-bold">Jane Smith</div></div></E>),
    (<E><div className="absolute inset-0 flex items-center justify-center"><div className="text-center"><div className="text-[10px] font-serif italic font-light text-gray-900">{brand.name}</div><div className="h-[1px] mx-auto w-[40%] my-1" style={{backgroundColor:p}} /><div className="text-[5px] uppercase tracking-[0.4em] text-gray-500">— jane smith —</div></div></div></E>),
    (<E><div className="absolute left-[5%] top-1/2 -translate-y-1/2 flex items-center gap-1"><div className="w-[5px] h-[5px] rounded-full bg-[#7BC56A]" /><span className="text-[3.5px] uppercase tracking-[0.32em] text-gray-700">live · {brand.name.toLowerCase()}</span></div><div className="absolute right-[5%] top-1/2 -translate-y-1/2 text-right"><div className="text-[8px] font-medium">Jane Smith</div></div></E>),
    (<E><div className="absolute inset-x-[5%] top-1/2 -translate-y-1/2"><div className="text-[3.5px] uppercase tracking-[0.32em] text-gray-400">— from the desk of —</div><div className="text-[10px] font-serif italic font-bold mt-0.5" style={{color:p}}>Jane Smith</div></div></E>),
    (<E bg="#0F1216"><div className="absolute inset-x-[5%] top-[15%] flex items-center gap-1"><div className="w-[5px] h-[5px] rounded-full" style={{backgroundColor:p}} /><span className="text-[3.5px] uppercase tracking-[0.32em] text-white opacity-90">{brand.name} · 014</span></div><div className="absolute inset-x-[5%] bottom-[15%] text-white"><div className="text-[7px] font-light">Jane Smith</div></div></E>),
    (<E><div className="absolute inset-x-[5%] top-[15%] grid grid-cols-12"><div className="col-span-1 text-[3.5px] uppercase tracking-[0.32em] text-gray-400 self-end">A.</div><div className="col-span-11 text-[3.5px] uppercase tracking-[0.32em] font-bold border-b border-black pb-0.5">{brand.name} · ENVELOPE A · 014</div></div><div className="absolute inset-x-[5%] bottom-[15%] text-[7px] font-bold">Jane Smith · 567 Recipient Ave</div></E>),
    (<E><div className="absolute inset-x-[5%] top-1/2 -translate-y-1/2 flex items-end gap-2"><div className="text-[24px] font-serif font-black leading-none" style={{color:p}}>{init}.</div><div><div className="text-[3.5px] uppercase tracking-[0.32em] text-gray-400">an envelope from</div><div className="text-[5px] font-bold mt-0.5">{brand.name}</div></div></div><div className="absolute right-[5%] top-1/2 -translate-y-1/2 text-right"><div className="text-[5px] font-bold">→ Jane Smith</div></div></E>),
    (<E><div className="absolute inset-x-[5%] top-[15%] grid grid-cols-2 gap-2 text-[3.5px] uppercase tracking-[0.32em]"><div><div className="text-gray-400">{brand.name}</div><div className="text-gray-700">— a small studio</div></div><div className="text-right"><div className="text-gray-400">no. 014</div><div className="text-gray-700">— spring 2026</div></div></div><div className="absolute inset-x-[5%] bottom-[15%] text-center text-[7px] font-bold">Jane Smith · 567 Recipient Ave · NY</div></E>),
  ];

  return designs[templateIndex] ?? designs[0];
}

export const ENVELOPE_EXTENDED_2 = Array.from({ length: 100 }, (_, i) => ({
  idSuffix: `ext-${i + 31}`,
  name: `Wave 2 · ${String(i + 1).padStart(2, '0')}`,
  category: 'Modern',
}));
