import type { Brand } from '@/shared/types/brand';
import { BrandLogo } from '@/features/brandkit/components/renderers/BrandLogo';
import { Bind } from '../content/Bind';
import { defaultLetterContent, type LetterContent } from '../content/kinds';

/**
 * Letterhead — Wave 2: 100 new designs (idx 0-99).
 *
 * Curated across 8 movements:
 *   Apple HIG · Brutalism · Swiss/Vignelli · Bento · Glassmorphism
 *   Gradient mesh · Pentagram-flexible · Editorial mixed
 *
 * Each design renders a portrait A4-shaped sheet centered in a beige
 * background, then composes the page (header / body / footer) in a
 * style specific to the movement. Brand-aware via primaryColor /
 * BrandLogo / brand.name.
 */
interface Props {
  brand: Brand;
  templateIndex: number;
  /** Structured letter content. Absent → the brand-derived defaults. */
  content?: LetterContent;
}

function Page({ children }: { children: React.ReactNode }) {
  return (
    <div className="w-full h-full bg-[#E8E4D8] flex items-center justify-center p-[3%]">
      <div className="bg-white shadow-md relative overflow-hidden" style={{ width: '46%', aspectRatio: '8.5 / 11' }}>{children}</div>
    </div>
  );
}

function bodyLines(rows: number, color = '#D4D2CB', startW = 85) {
  return Array.from({ length: rows }).map((_, i) => (
    <div key={i} className="rounded-sm" style={{ height: '2px', background: color, width: `${startW - (i % 4) * 8}%` }} />
  ));
}

export function LetterheadExtended2Renderer({ brand, templateIndex, content }: Props) {
  const p = brand.primaryColor;
  const c = content ?? defaultLetterContent(brand);

  /**
   * The body of the letter.
   *
   * Every design in this family draws grey rules where copy goes, and
   * they all reach them through one function — so binding THAT gives the
   * whole family a real, editable body in one move rather than a hundred.
   * An empty body keeps the rules, because a blank letterhead should look
   * like a blank letterhead and not like a hole.
   */
  const body = (rows: number, color?: string, startW?: number) =>
    c.body.trim().length > 0 ? (
      <Bind
        path="body"
        value={c.body}
        fit="wrap"
        multiline
        className="block text-[3.5px] leading-[1.7] whitespace-pre-wrap"
        style={{ color: color ?? '#4B5563' }}
      />
    ) : (
      bodyLines(rows, color, startW)
    );
  const s = brand.secondaryColor || '#0F1216';
  const init = brand.name.charAt(0).toUpperCase();
  const N = brand.name.toUpperCase();
  const lower = brand.name.toLowerCase();

  const designs: React.ReactNode[] = [
    // ─── APPLE-LIKE (15)
    (<Page><div className="absolute inset-x-[7%] top-[10%]"><div className="text-[3.5px] uppercase tracking-[0.32em] text-gray-400">{brand.name}</div></div><div className="absolute inset-x-[7%] top-[24%] space-y-[2.5px]">{body(16)}</div><div className="absolute right-[7%] bottom-[6%] text-right text-[3px] uppercase tracking-[0.32em] text-gray-400">{lower}.com</div></Page>),
    (<Page><BrandLogo brand={brand} size="xs" /><div className="absolute inset-x-[7%] top-[16%] h-[1px] bg-[#D4D2CB]" /><div className="absolute inset-x-[7%] top-[20%] space-y-[2.5px]">{body(15)}</div></Page>),
    (<Page><div className="absolute left-[7%] top-[8%] flex items-center gap-1.5"><div className="w-[6px] h-[6px] rounded-full" style={{backgroundColor:p}} /><span className="text-[3.5px] uppercase tracking-[0.32em] text-gray-700">{brand.name} · live</span></div><div className="absolute inset-x-[7%] top-[22%] space-y-[2.5px]">{body(17)}</div></Page>),
    (<Page><div className="absolute inset-x-[8%] top-[12%]"><div className="text-[18px] font-light leading-none text-gray-900">Hello,</div></div><div className="absolute inset-x-[8%] top-[26%] space-y-[2.5px]">{body(15)}</div><div className="absolute right-[8%] bottom-[6%] text-right text-[3.5px] text-gray-500">— Jane Smith</div></Page>),
    (<Page><div className="absolute inset-x-[8%] top-[8%] flex items-center justify-between"><BrandLogo brand={brand} size="xs" /><span className="text-[3.5px] uppercase tracking-[0.32em] text-gray-400">2026</span></div><div className="absolute left-[8%] top-[18%] right-[8%] h-[1px] bg-[#F0EFEB]" /><div className="absolute inset-x-[8%] top-[22%] space-y-[2.5px]">{body(16)}</div></Page>),
    (<Page><div className="absolute left-[8%] top-[8%] right-[8%] grid grid-cols-3"><div className="text-[3.5px] uppercase tracking-[0.32em] text-gray-400">— Memo</div><div className="text-[3.5px] uppercase tracking-[0.32em] text-center" style={{color:p}}>{brand.name}</div><div className="text-[3.5px] uppercase tracking-[0.32em] text-right text-gray-400">P. 014</div></div><div className="absolute inset-x-[10%] top-[24%] space-y-[2.5px]">{body(15)}</div></Page>),
    (<Page><div className="absolute inset-x-[8%] top-[8%]"><div className="text-[3.5px] uppercase tracking-[0.4em] text-gray-400">FROM</div><div className="text-[10px] font-light text-gray-900 mt-1">Jane Smith</div><div className="text-[3.5px] uppercase tracking-[0.32em] text-gray-500">{brand.name} · vp ops</div></div><div className="absolute inset-x-[8%] top-[36%] space-y-[2.5px]">{body(14)}</div></Page>),
    (<Page><div className="absolute inset-x-[7%] top-[10%] text-center"><BrandLogo brand={brand} size="xs" /></div><div className="absolute inset-x-[10%] top-[20%] space-y-[2.5px]">{body(16)}</div><div className="absolute inset-x-[10%] bottom-[6%] text-center text-[3px] uppercase tracking-[0.4em] text-gray-400">— {brand.name} —</div></Page>),
    (<Page><div className="absolute right-[8%] top-[8%] text-right"><div className="text-[3.5px] uppercase tracking-[0.32em] text-gray-400">{brand.name}</div><div className="text-[3.5px] uppercase tracking-[0.32em] text-gray-400">N° 014</div></div><div className="absolute inset-x-[8%] top-[24%] space-y-[2.5px]">{body(16)}</div></Page>),
    (<Page><div className="absolute inset-x-[8%] top-[8%] flex items-baseline gap-1.5"><div className="text-[10px] font-light text-gray-900">{brand.name}</div><div className="text-[3.5px] uppercase tracking-[0.32em] text-gray-400">— a memo</div></div><div className="absolute inset-x-[8%] top-[20%] space-y-[2.5px]">{body(16)}</div></Page>),
    (<Page><div className="absolute left-[8%] top-[10%] right-[8%] flex items-end gap-2"><div className="text-[16px] font-light leading-none text-gray-900">14</div><div className="text-[3.5px] uppercase tracking-[0.32em] text-gray-400">memo · {brand.name}</div></div><div className="absolute inset-x-[8%] top-[24%] space-y-[2.5px]">{body(15)}</div></Page>),
    (<Page><div className="absolute inset-x-[8%] top-[10%]"><div className="text-[3.5px] uppercase tracking-[0.32em]" style={{color:p}}>{brand.name} · 014</div></div><div className="absolute inset-x-[8%] top-[20%] flex flex-col gap-[2px]">{body(18)}</div></Page>),
    (<Page><div className="absolute inset-x-[8%] top-[10%]"><div className="text-[10px] font-medium text-gray-900">A small note,</div></div><div className="absolute inset-x-[8%] top-[22%] space-y-[2.5px]">{body(15)}</div><div className="absolute inset-x-[8%] bottom-[5%] flex justify-between text-[3.5px] text-gray-500"><span>Jane Smith · VP</span><span style={{color:p}}>{brand.name}</span></div></Page>),
    (<Page><div className="absolute inset-x-[8%] top-[8%] grid grid-cols-2 gap-2 text-[3.5px]"><div><div className="uppercase tracking-[0.32em] text-gray-400">to</div><div className="mt-0.5">Acme team</div></div><div><div className="uppercase tracking-[0.32em] text-gray-400">from</div><div className="mt-0.5">{brand.name}</div></div></div><div className="absolute inset-x-[8%] top-[26%] space-y-[2.5px]">{body(15)}</div></Page>),
    (<Page><div className="absolute inset-x-[8%] top-[10%] text-center"><div className="text-[3.5px] uppercase tracking-[0.4em] text-gray-400">— {brand.name} —</div><div className="text-[10px] font-light text-gray-900 mt-1">An open letter.</div></div><div className="absolute inset-x-[10%] top-[28%] space-y-[2.5px]">{body(15)}</div></Page>),

    // ─── BRUTALIST (15)
    (<Page><div className="absolute inset-0 bg-[#FFEB3B] p-[6%] font-mono"><div className="text-[5px] uppercase tracking-[0.22em] font-bold">{N} :: MEMO_014</div><div className="text-[14px] font-extrabold mt-1 leading-none">URGENT.</div><div className="mt-3 space-y-[2px]">{body(14, '#000', 70)}</div></div></Page>),
    (<Page><div className="absolute inset-0 bg-black text-[#39FF14] p-[6%] font-mono"><div className="text-[3.5px] uppercase tracking-[0.22em] opacity-70">// {brand.name.toLowerCase()}.memo</div><div className="text-[10px] mt-2">$ cat letter.txt</div><div className="text-[5px] mt-3 leading-[1.6] opacity-90">{`> ${brand.name}: a small note from operations.\n> we keep things small. we keep them careful.\n> read on for the rest.`}</div></div></Page>),
    (<Page><div className="absolute inset-0 p-[6%] font-mono"><div className="text-[3.5px] uppercase tracking-[0.22em] border-b-4 border-black pb-1">FILE: LETTER_014.{brand.name.toLowerCase()}</div><div className="text-[18px] font-extrabold leading-none mt-2">JANE.SMITH</div><div className="text-[3.5px] uppercase tracking-[0.22em] mt-1">VP // {brand.name.toUpperCase()} // OPERATIONS</div><div className="mt-3 space-y-[2px]">{body(15, '#1F1F1F', 80)}</div></div></Page>),
    (<Page><div className="absolute inset-0 bg-white"><div className="absolute top-0 inset-x-0 h-[20%]" style={{backgroundColor:p}} /><div className="absolute top-[20%] inset-x-[6%] text-[24px] font-extrabold uppercase font-mono leading-none">DEAR,</div><div className="absolute inset-x-[6%] top-[34%] space-y-[2px]">{body(15, '#000', 80)}</div></div></Page>),
    (<Page><div className="absolute inset-0 bg-white p-[6%]"><div className="grid grid-cols-2 gap-1"><div className="bg-black text-white p-1 text-[3.5px] uppercase tracking-[0.22em] font-mono">FROM</div><div className="border-2 border-black p-1 text-[3.5px] uppercase tracking-[0.22em] font-mono">TO</div><div className="border-2 border-black p-1 text-[3.5px] font-mono">JANE_S</div><div className="bg-black text-white p-1 text-[3.5px] font-mono">ACME</div></div><div className="mt-3 space-y-[2px] font-mono">{body(14, '#000', 80)}</div></div></Page>),
    (<Page><div className="absolute inset-0 bg-yellow-300 font-mono"><div className="border-b-4 border-black p-2 text-[5px] uppercase tracking-[0.22em] font-bold">!!! NOT FOR DISTRIBUTION</div><div className="p-3 text-[18px] font-extrabold leading-[0.92]">JANE,<br/>READ.</div><div className="px-3 mt-2 space-y-[2px]">{body(13, '#000', 75)}</div></div></Page>),
    (<Page><div className="absolute inset-0 bg-white p-[6%]"><div className="text-[24px] font-extrabold uppercase font-mono leading-[0.92]">MEMO</div><div className="text-[24px] font-extrabold uppercase font-mono leading-[0.92]" style={{color:p}}>014</div><div className="mt-3 space-y-[2px] font-mono">{body(16, '#000', 80)}</div></div></Page>),
    (<Page><div className="absolute inset-0 bg-[#0F1216] text-yellow-300 p-[6%] font-mono"><div className="text-[3.5px] uppercase tracking-[0.22em] opacity-70">root@{brand.name.toLowerCase()}:~$</div><div className="text-[5px] mt-2">read /letters/014.txt</div><div className="mt-2 space-y-[2px]">{body(15, '#39FF14', 80)}</div><div className="absolute right-[6%] bottom-[6%] text-[3.5px] uppercase tracking-[0.32em]">EOF.</div></div></Page>),
    (<Page><div className="absolute inset-0" style={{ background: 'repeating-linear-gradient(0deg, #000 0 2px, #fff 2px 4px)' }}><div className="absolute inset-[8%] bg-white p-3"><div className="text-[5px] uppercase tracking-[0.22em] font-mono font-bold">{brand.name} · 014</div><div className="text-[16px] font-extrabold uppercase font-mono mt-1">DEAR.</div><div className="mt-2 space-y-[2px] font-mono">{body(13, '#000', 80)}</div></div></div></Page>),
    (<Page><div className="absolute inset-0 bg-white p-[6%] font-mono"><div className="grid grid-cols-3 gap-1 mb-2">{Array.from({length:3}).map((_,i)=>(<div key={i} className="border-2 border-black p-1 text-[3px] uppercase tracking-[0.22em] text-center font-bold" style={{backgroundColor:i===0?p:'#fff',color:i===0?'#fff':'#000'}}>BLOCK_0{i+1}</div>))}</div><div className="space-y-[2px]">{body(16, '#000', 80)}</div></div></Page>),
    (<Page><div className="absolute inset-0 bg-white p-[6%]"><div className="text-[36px] font-extrabold leading-[0.85] uppercase font-mono">JANE,<br/><span style={{color:p}}>READ.</span></div></div></Page>),
    (<Page><div className="absolute inset-0 bg-[#FF3B30] text-white p-[6%] font-mono"><div className="text-[3.5px] uppercase tracking-[0.22em] opacity-90">!! HOT MEMO</div><div className="text-[20px] font-extrabold leading-[0.92] mt-1">URGENT.<br/>READ.<br/>NOW.</div><div className="mt-3 space-y-[2px]">{body(11, '#fff', 80)}</div></div></Page>),
    (<Page><div className="absolute inset-0 bg-white p-[6%] font-mono"><div className="text-[5px] uppercase tracking-[0.22em] font-bold">[draft 003]</div><div className="text-[16px] font-extrabold leading-none mt-1">RE: SHIP.</div><div className="mt-3 space-y-[2px]">{body(16, '#000', 80)}</div><div className="absolute right-[6%] bottom-[6%] text-[3.5px] uppercase tracking-[0.22em] font-bold" style={{color:p}}>// EOF</div></div></Page>),
    (<Page><div className="absolute inset-0 bg-yellow-300 p-[6%] font-mono"><div className="border-2 border-black inline-block px-2 py-0.5 -rotate-3"><span className="text-[5px] uppercase tracking-[0.22em] font-bold">CONFIDENTIAL</span></div><div className="text-[18px] font-extrabold uppercase mt-3 leading-none">EYES_ONLY</div><div className="mt-3 space-y-[2px]">{body(13, '#000', 80)}</div></div></Page>),
    (<Page><div className="absolute inset-0 bg-white p-[6%] font-mono"><div className="grid grid-cols-2 gap-1 mb-2"><div className="bg-black text-white p-1 text-[3.5px] uppercase">FROM: {brand.name.toLowerCase()}</div><div className="border-2 border-black p-1 text-[3.5px] uppercase">TO: ACME</div></div><div className="text-[14px] font-extrabold uppercase">SUBJECT: SHIP IT.</div><div className="mt-2 space-y-[2px]">{body(14, '#000', 80)}</div></div></Page>),

    // ─── SWISS / VIGNELLI (15)
    (<Page><div className="absolute inset-x-[7%] top-[7%] border-b-2 border-black pb-1 text-[3.5px] uppercase tracking-[0.32em] font-bold">{brand.name} · BUSINESS LETTER · 014 · SPRING 2026</div><div className="absolute inset-x-[7%] top-[16%] grid grid-cols-12 gap-1 text-[3.5px] uppercase tracking-[0.22em]"><span className="col-span-2 text-gray-400">to</span><span className="col-span-10">Acme Corp · NY</span><span className="col-span-2 text-gray-400">from</span><span className="col-span-10">{brand.name}</span><span className="col-span-2 text-gray-400">date</span><span className="col-span-10">27 · 04 · 2026</span></div><div className="absolute inset-x-[7%] top-[36%] space-y-[2.5px]">{body(14)}</div></Page>),
    (<Page><div className="absolute inset-x-[7%] top-[7%] grid grid-cols-12"><div className="col-span-2 text-[3.5px] uppercase tracking-[0.32em] font-bold">{brand.name}</div><div className="col-span-7 text-[10px] font-bold leading-none">An open letter to the team.</div><div className="col-span-3 text-right text-[3.5px] uppercase tracking-[0.32em] text-gray-400">N° 014</div></div><div className="absolute inset-x-[7%] top-[24%] space-y-[2.5px]">{body(16)}</div></Page>),
    (<Page><div className="absolute inset-x-[7%] top-[8%] flex justify-between items-end border-b-2 border-black pb-1"><BrandLogo brand={brand} size="xs" /><span className="text-[10px] font-bold">14 / 014</span></div><div className="absolute inset-x-[7%] top-[20%] space-y-[2.5px]">{body(17)}</div><div className="absolute inset-x-[7%] bottom-[6%] flex justify-between text-[3.5px] uppercase tracking-[0.32em] border-t border-black pt-1"><span>{lower}.com</span><span>jane@{lower}.com</span></div></Page>),
    (<Page><div className="absolute left-[6%] top-[7%] bottom-[7%] w-[1px] bg-black" /><div className="absolute inset-x-[10%] top-[10%] text-[3.5px] uppercase tracking-[0.4em] font-bold">{brand.name}</div><div className="absolute inset-x-[10%] top-[24%] space-y-[2.5px]">{body(17)}</div></Page>),
    (<Page><div className="absolute inset-x-[7%] top-[7%] grid grid-cols-3 text-[3.5px] uppercase tracking-[0.32em] font-bold border-b-2 border-black pb-1"><span>FROM · {brand.name}</span><span className="text-center">N° 014 · 2026</span><span className="text-right">P. 1 / 4</span></div><div className="absolute inset-x-[7%] top-[20%] space-y-[2.5px]">{body(16)}</div></Page>),
    (<Page><div className="absolute inset-x-[7%] top-[7%] text-center text-[3.5px] uppercase tracking-[0.5em] font-bold border-b-2 border-black pb-1.5">{brand.name} CO.</div><div className="absolute inset-x-[10%] top-[20%] space-y-[2.5px]">{body(17)}</div><div className="absolute inset-x-[7%] bottom-[6%] text-center text-[3px] uppercase tracking-[0.4em] border-t border-black pt-1">+1 234 56789 · jane@{lower} · {lower}.com</div></Page>),
    (<Page><div className="absolute inset-x-[7%] top-[8%] flex items-baseline gap-2"><div className="text-[20px] font-black tabular-nums">14</div><div className="text-[3.5px] uppercase tracking-[0.32em]" style={{color:p}}>{brand.name} · 014</div></div><div className="absolute inset-x-[7%] top-[26%] space-y-[2.5px]">{body(16)}</div></Page>),
    (<Page><div className="absolute inset-x-[7%] top-[7%] grid grid-cols-12 gap-1"><div className="col-span-12 text-[5px] uppercase tracking-[0.32em] font-bold border-b border-black pb-1">{brand.name} · DEPARTMENT OF OPERATIONS</div><div className="col-span-12 mt-2 grid grid-cols-2"><div className="text-[3.5px] uppercase tracking-[0.32em] text-gray-400">— jane smith</div><div className="text-right text-[3.5px] uppercase tracking-[0.32em]" style={{color:p}}>vp</div></div></div><div className="absolute inset-x-[7%] top-[24%] space-y-[2.5px]">{body(16)}</div></Page>),
    (<Page><div className="absolute inset-x-[6%] top-[6%] bottom-[6%] grid grid-cols-12 grid-rows-12 gap-1"><div className="col-span-12 text-[3.5px] uppercase tracking-[0.32em] font-bold">{brand.name}</div><div className="col-span-12 row-span-9 grid grid-cols-12 gap-x-1"><div className="col-span-3 text-[3.5px] uppercase tracking-[0.32em] text-gray-400">— body</div><div className="col-span-9 space-y-[2.5px] mt-[2px]">{body(13)}</div></div><div className="col-span-12 row-span-2 text-[3.5px] uppercase tracking-[0.32em] flex items-end justify-between border-t border-black pt-1"><span>+1 234 56789</span><span>jane@{lower}.com</span></div></div></Page>),
    (<Page><div className="absolute left-[6%] top-[6%] right-[6%] h-[1px] bg-black" /><div className="absolute left-[6%] top-[10%] right-[6%] h-[1px]" style={{backgroundColor:p}} /><div className="absolute inset-x-[6%] top-[14%] text-[3.5px] uppercase tracking-[0.32em] font-bold">{brand.name} OFFICE</div><div className="absolute inset-x-[6%] top-[24%] space-y-[2.5px]">{body(17)}</div></Page>),
    (<Page><div className="absolute inset-x-[7%] top-[7%] flex items-baseline gap-2"><div className="text-[3.5px] uppercase tracking-[0.32em] font-bold">{brand.name}</div><div className="flex-1 h-[1px] bg-black mx-1" /><div className="text-[3.5px] uppercase tracking-[0.32em]">N° 014</div></div><div className="absolute inset-x-[7%] top-[18%] space-y-[2.5px]">{body(18)}</div></Page>),
    (<Page><div className="absolute inset-x-[7%] top-[7%]"><div className="text-[3.5px] uppercase tracking-[0.32em] font-bold">{brand.name} · OFFICIAL</div><div className="text-[14px] font-bold mt-1 leading-none">RE: Q1 Brief</div></div><div className="absolute inset-x-[7%] top-[28%] grid grid-cols-12 gap-x-1"><div className="col-span-2 text-[3.5px] uppercase tracking-[0.32em] text-gray-400">summary</div><div className="col-span-10 space-y-[2.5px]">{body(13)}</div></div></Page>),
    (<Page><div className="absolute left-[6%] top-[6%] bottom-[6%] w-[14%] flex flex-col justify-between"><div className="text-[3.5px] uppercase tracking-[0.32em] font-bold">{brand.name}</div><BrandLogo brand={brand} size="xs" /></div><div className="absolute left-[24%] top-[8%] right-[7%] text-[10px] font-bold leading-none">An Open Letter</div><div className="absolute left-[24%] top-[18%] right-[7%] space-y-[2.5px]">{body(18)}</div></Page>),
    (<Page><div className="absolute inset-x-[6%] top-[6%]"><div className="border-y-2 border-black py-1.5 text-center text-[5px] uppercase tracking-[0.5em] font-bold">{brand.name} · 014</div></div><div className="absolute inset-x-[10%] top-[20%] space-y-[2.5px]">{body(17)}</div></Page>),
    (<Page><div className="absolute inset-x-[7%] top-[7%] text-[3.5px] uppercase tracking-[0.32em] font-bold border-b border-black pb-1">SECTION A · INTRODUCTION</div><div className="absolute inset-x-[7%] top-[16%] space-y-[2.5px]">{body(7)}</div><div className="absolute inset-x-[7%] top-[44%] text-[3.5px] uppercase tracking-[0.32em] font-bold border-b border-black pb-1">SECTION B · DETAIL</div><div className="absolute inset-x-[7%] top-[54%] space-y-[2.5px]">{body(8)}</div></Page>),

    // ─── BENTO / MODULAR (10)
    (<Page><div className="absolute inset-[6%] grid grid-cols-3 grid-rows-5 gap-1.5"><div className="col-span-2 row-span-2 rounded-lg" style={{backgroundColor:p}} /><div className="rounded-lg bg-[#F5F5F7] flex items-center justify-center"><BrandLogo brand={brand} size="xs" color={p} /></div><div className="rounded-lg bg-[#0F1216] flex items-center justify-center"><span className="text-white text-[10px] font-bold">{init}</span></div><div className="col-span-3 row-span-3 bg-white p-2 space-y-[2px] border border-[#E5E0D2] rounded-lg">{body(12)}</div></div></Page>),
    (<Page><div className="absolute inset-[5%] grid grid-cols-2 grid-rows-4 gap-1"><div className="rounded-lg flex items-center justify-center" style={{backgroundColor:p}}><span className="text-white text-[10px] font-bold">{brand.name}</span></div><div className="rounded-lg bg-[#F5F5F7] p-1.5 text-[3.5px]"><div className="uppercase tracking-[0.22em] text-gray-400">14</div></div><div className="col-span-2 row-span-2 rounded-lg bg-white border p-2 space-y-[2px]">{body(11)}</div><div className="col-span-2 rounded-lg bg-[#0F1216] flex items-center justify-center"><span className="text-white text-[3.5px] uppercase tracking-[0.22em]">jane@{lower}</span></div></div></Page>),
    (<Page><div className="absolute inset-[5%] grid grid-cols-3 grid-rows-3 gap-1.5"><div className="col-span-3 rounded-xl bg-[#F5F5F7] p-2"><div className="text-[3.5px] uppercase tracking-[0.32em] text-gray-400">{brand.name} · MEMO 014</div></div><div className="row-span-2 rounded-xl flex items-end p-2" style={{backgroundColor:p}}><span className="text-white text-[7px] font-bold">jane.</span></div><div className="col-span-2 row-span-2 rounded-xl bg-white border p-2 space-y-[2px]">{body(10)}</div></div></Page>),
    (<Page><div className="absolute inset-[5%] grid grid-cols-4 grid-rows-5 gap-1"><div className="col-span-4 rounded-lg flex items-center justify-between px-2" style={{backgroundColor:p}}><BrandLogo brand={brand} size="xs" color="#fff" /><span className="text-white text-[3.5px] uppercase tracking-[0.32em]">{brand.name}</span></div><div className="col-span-3 row-span-4 bg-white border rounded-lg p-2 space-y-[2px]">{body(15)}</div><div className="row-span-2 bg-[#F5F5F7] rounded-lg flex items-center justify-center text-[10px] font-bold tabular-nums" style={{color:p}}>14</div><div className="row-span-2 bg-[#0F1216] rounded-lg" /></div></Page>),
    (<Page><div className="absolute inset-[5%] grid grid-cols-2 grid-rows-3 gap-1.5"><div className="rounded-2xl bg-white border p-2"><div className="text-[3.5px] uppercase tracking-[0.32em]" style={{color:p}}>FROM</div><div className="text-[7px] font-bold mt-0.5">{brand.name}</div></div><div className="rounded-2xl bg-white border p-2"><div className="text-[3.5px] uppercase tracking-[0.32em]" style={{color:p}}>TO</div><div className="text-[7px] font-bold mt-0.5">Acme</div></div><div className="col-span-2 row-span-2 rounded-2xl bg-[#FBF8EE] p-2 space-y-[2px]">{body(14)}</div></div></Page>),
    (<Page><div className="absolute inset-[5%] grid grid-cols-3 grid-rows-4 gap-1"><div className="col-span-3 rounded-lg bg-[#F5F5F7] flex items-center justify-between px-2"><span className="text-[3.5px] uppercase tracking-[0.32em]">{brand.name}</span><span className="text-[3.5px] uppercase tracking-[0.32em] text-gray-400">014</span></div><div className="row-span-2 rounded-lg" style={{backgroundColor:p}} /><div className="col-span-2 row-span-3 rounded-lg bg-white border p-2 space-y-[2px]">{body(13)}</div><div className="rounded-lg bg-[#0F1216]" /></div></Page>),
    (<Page><div className="absolute inset-[5%] grid grid-cols-5 grid-rows-6 gap-[3px]"><div className="col-span-5 row-span-1 rounded bg-[#F5F5F7] flex items-center px-2 text-[3.5px] uppercase tracking-[0.32em]">{brand.name} · LETTER</div><div className="col-span-2 row-span-5 rounded p-2 flex flex-col justify-end" style={{backgroundColor:p}}><span className="text-white text-[14px] font-bold leading-none">An open letter</span></div><div className="col-span-3 row-span-5 rounded bg-white border p-2 space-y-[2px]">{body(15)}</div></div></Page>),
    (<Page><div className="absolute inset-[5%] grid grid-cols-3 grid-rows-6 gap-1"><div className="col-span-3 row-span-1 rounded bg-white border p-1 text-[3.5px] uppercase tracking-[0.22em] flex items-center"><BrandLogo brand={brand} size="xs" /><span className="ml-1">{brand.name} · 014</span></div><div className="row-span-4 rounded" style={{backgroundColor:p}} /><div className="col-span-2 row-span-4 rounded bg-white border p-2 space-y-[2px]">{body(13)}</div><div className="col-span-3 rounded bg-[#FBF8EE] p-1 text-[3.5px] uppercase tracking-[0.22em]">jane@{lower}.com · +1 234 56789</div></div></Page>),
    (<Page><div className="absolute inset-[5%] grid grid-cols-2 grid-rows-4 gap-1.5"><div className="row-span-2 rounded-2xl bg-[#F5F5F7] flex items-center justify-center"><BrandLogo brand={brand} size="md" color={p} /></div><div className="rounded-2xl flex items-center justify-center" style={{backgroundColor:p}}><span className="text-white text-[10px] font-bold">VP</span></div><div className="rounded-2xl bg-[#0F1216] flex items-center justify-center"><span className="text-white text-[3.5px] uppercase tracking-[0.32em]">jane</span></div><div className="col-span-2 row-span-2 rounded-2xl bg-white border p-2 space-y-[2px]">{body(12)}</div></div></Page>),
    (<Page><div className="absolute inset-[5%] grid grid-cols-4 grid-rows-6 gap-1"><div className="col-span-4 row-span-1 rounded bg-[#F5F5F7] p-1 text-[3.5px] uppercase tracking-[0.32em]">{brand.name} OFFICE · A LETTER</div><div className="col-span-4 row-span-4 rounded bg-white border p-3 space-y-[2px]">{body(16)}</div><div className="col-span-1 rounded" style={{backgroundColor:p}} /><div className="col-span-2 rounded bg-[#0F1216] flex items-center justify-center text-white text-[3.5px] uppercase tracking-[0.32em]">— jane smith</div><div className="col-span-1 rounded bg-[#FBF8EE] flex items-center justify-center text-[3.5px] uppercase tracking-[0.32em]">vp</div></div></Page>),

    // ─── GLASSMORPHISM (10)
    (<Page><div className="absolute inset-0" style={{ background: `linear-gradient(135deg, ${p}, ${s})` }} /><div className="absolute inset-[8%] rounded-2xl backdrop-blur-md bg-white/30 border border-white/50 p-3"><div className="text-white text-[3.5px] uppercase tracking-[0.32em] opacity-90">{brand.name} · 014</div><div className="text-white text-[10px] font-light mt-2">Hello,</div><div className="mt-3 space-y-[2px]">{body(14, 'rgba(255,255,255,0.4)', 80)}</div></div></Page>),
    (<Page><div className="absolute inset-0 bg-[#0F1216]" /><div className="absolute inset-0" style={{ background: `radial-gradient(80% 60% at 30% 30%, ${p} 0%, transparent 70%)` }} /><div className="absolute inset-[6%] rounded-3xl backdrop-blur-md bg-white/10 border border-white/20 p-3 text-white"><div className="text-[3.5px] uppercase tracking-[0.32em] opacity-90">{brand.name}</div><div className="text-[10px] font-light mt-2">An open letter.</div><div className="mt-3 space-y-[2px]">{body(13, 'rgba(255,255,255,0.25)', 80)}</div></div></Page>),
    (<Page><div className="absolute inset-0 bg-[#FBF8EE]" /><div className="absolute -left-[10%] top-[10%] w-[60%] aspect-square rounded-full" style={{ background: `radial-gradient(circle, ${p}, transparent 70%)` }} /><div className="absolute right-[10%] bottom-[10%] w-[40%] aspect-square rounded-full" style={{ background: `radial-gradient(circle, ${s}AA, transparent 70%)` }} /><div className="absolute inset-[8%] rounded-2xl backdrop-blur-2xl bg-white/40 border border-white/60 p-3"><div className="text-[3.5px] uppercase tracking-[0.32em] text-gray-700">{brand.name} · 014</div><div className="mt-2 space-y-[2px]">{body(15)}</div></div></Page>),
    (<Page><div className="absolute inset-0 grid grid-cols-3 grid-rows-3"><div style={{backgroundColor:p}} /><div className="bg-white" /><div style={{backgroundColor:s}} /><div className="bg-white" /><div style={{backgroundColor:p,opacity:0.6}} /><div className="bg-white" /><div style={{backgroundColor:s,opacity:0.4}} /><div className="bg-white" /><div style={{backgroundColor:p}} /></div><div className="absolute inset-[8%] rounded-2xl backdrop-blur-2xl bg-white/50 border border-white/60 p-3"><div className="text-[3.5px] uppercase tracking-[0.32em]" style={{color:p}}>{brand.name} · 014</div><div className="mt-2 space-y-[2px]">{body(15)}</div></div></Page>),
    (<Page><div className="absolute inset-0" style={{ background: `conic-gradient(from 0deg, ${p}, ${s}, ${p})` }} /><div className="absolute inset-[6%] rounded-3xl backdrop-blur-3xl bg-white/40 border border-white/60 p-3"><div className="text-[10px] font-light text-gray-900">A letter,</div><div className="mt-2 space-y-[2px]">{body(15)}</div></div></Page>),
    (<Page><div className="absolute inset-0 bg-white" /><div className="absolute inset-x-0 top-0 h-[40%]" style={{ background: `linear-gradient(180deg, ${p}, transparent)` }} /><div className="absolute inset-[6%] rounded-2xl backdrop-blur-md bg-white/50 border border-white/70 p-3"><BrandLogo brand={brand} size="xs" color={p} /><div className="mt-2 space-y-[2px]">{body(16)}</div></div></Page>),
    (<Page><div className="absolute inset-0 bg-[#1F1F1F]" /><div className="absolute inset-0" style={{ background: `radial-gradient(40% 30% at 80% 20%, ${p}AA 0%, transparent 100%), radial-gradient(40% 30% at 20% 80%, ${s}AA 0%, transparent 100%)` }} /><div className="absolute inset-[6%] rounded-3xl backdrop-blur-md bg-white/5 border border-white/15 p-3 text-white"><div className="text-[3.5px] uppercase tracking-[0.32em] opacity-70">— a quiet note —</div><div className="mt-2 space-y-[2px]">{body(15, 'rgba(255,255,255,0.25)', 80)}</div></div></Page>),
    (<Page><div className="absolute inset-0" style={{background:`linear-gradient(180deg, ${p} 0%, ${p}AA 30%, transparent 70%)`,backgroundColor:'#FBF8EE'}} /><div className="absolute inset-[6%] rounded-2xl backdrop-blur-lg bg-white/40 border border-white/70 p-3"><div className="text-[10px] font-medium">Spring update</div><div className="mt-2 space-y-[2px]">{body(15)}</div></div></Page>),
    (<Page><div className="absolute inset-0 bg-white" /><div className="absolute inset-x-[20%] top-[20%] aspect-square rounded-full" style={{ background: `radial-gradient(circle, ${p}, transparent 70%)` }} /><div className="absolute inset-[8%] rounded-2xl backdrop-blur-md bg-white/40 border border-white/70 p-3"><div className="text-[3.5px] uppercase tracking-[0.32em]" style={{color:p}}>jane @ {brand.name}</div><div className="mt-2 space-y-[2px]">{body(16)}</div></div></Page>),
    (<Page><div className="absolute inset-0 bg-[#0F1216]" /><div className="absolute inset-0" style={{background:`linear-gradient(45deg, transparent 0%, ${p}55 50%, transparent 100%)`}} /><div className="absolute inset-[6%] rounded-2xl backdrop-blur-xl bg-white/10 border border-white/20 p-3 text-white"><div className="text-[3.5px] uppercase tracking-[0.32em] opacity-90">{brand.name} · DRAFT</div><div className="text-[10px] font-light mt-2">Read me.</div><div className="mt-2 space-y-[2px]">{body(14, 'rgba(255,255,255,0.3)', 80)}</div></div></Page>),

    // ─── GRADIENT MESH (10)
    (<Page><div className="absolute inset-0" style={{ background: `radial-gradient(120% 80% at 20% 30%, ${p} 0%, transparent 60%), radial-gradient(120% 80% at 80% 70%, ${s} 0%, transparent 60%), #FBF8EE` }} /><div className="absolute inset-[7%]"><div className="text-[5px] uppercase tracking-[0.32em]" style={{color:p,filter:'brightness(0.6)'}}>{brand.name} · 014</div><div className="text-[10px] font-light mt-2 text-gray-900">Hello.</div><div className="mt-3 space-y-[2px]">{body(15)}</div></div></Page>),
    (<Page><div className="absolute inset-0" style={{background:`linear-gradient(135deg, ${p}, ${s})`}} /><div className="absolute inset-[7%] text-white"><BrandLogo brand={brand} size="xs" color="#fff" /><div className="text-[14px] font-light mt-3">A note,</div><div className="mt-3 space-y-[2px]">{body(14, 'rgba(255,255,255,0.4)', 80)}</div></div></Page>),
    (<Page><div className="absolute inset-x-0 top-0 h-[40%]" style={{background:`linear-gradient(180deg, ${p}, transparent)`}} /><div className="absolute inset-[7%] top-[28%]"><div className="space-y-[2px]">{body(18)}</div></div></Page>),
    (<Page><div className="absolute inset-0" style={{background:`radial-gradient(circle at 50% 0%, ${p} 0%, transparent 50%)`,backgroundColor:'#FBF8EE'}} /><div className="absolute inset-[7%]"><div className="text-[10px] font-light text-gray-900 mt-[20%]">Dear team,</div><div className="mt-3 space-y-[2px]">{body(15)}</div></div></Page>),
    (<Page><div className="absolute inset-0" style={{background:`linear-gradient(180deg, ${p} 0%, ${p}66 50%, white 100%)`}} /><div className="absolute inset-x-[7%] top-[10%] text-white"><div className="text-[3.5px] uppercase tracking-[0.32em] opacity-90">{brand.name}</div><div className="text-[14px] font-light mt-1">A spring update.</div></div><div className="absolute inset-x-[7%] top-[44%] space-y-[2px]">{body(15)}</div></Page>),
    (<Page><div className="absolute inset-0" style={{background:`conic-gradient(from 90deg at 30% 70%, ${p}AA, ${s}AA, ${p}AA)`,backgroundColor:'#FBF8EE'}} /><div className="absolute inset-[7%] mt-[6%]"><div className="text-[3.5px] uppercase tracking-[0.32em] text-gray-700">{brand.name} · 014</div><div className="mt-3 space-y-[2px]">{body(16)}</div></div></Page>),
    (<Page><div className="absolute inset-0 bg-white" /><div className="absolute -left-[20%] -top-[20%] w-[60%] aspect-square rounded-full" style={{background:`radial-gradient(circle, ${p}, transparent 70%)`}} /><div className="absolute -right-[20%] -bottom-[20%] w-[60%] aspect-square rounded-full" style={{background:`radial-gradient(circle, ${s}, transparent 70%)`}} /><div className="absolute inset-[7%] z-10 relative"><div className="text-[3.5px] uppercase tracking-[0.32em]" style={{color:p}}>{brand.name}</div><div className="mt-2 space-y-[2px]">{body(17)}</div></div></Page>),
    (<Page><div className="absolute inset-0" style={{background:`linear-gradient(105deg, ${p} 0%, ${p} 38%, white 38.5%, white 100%)`}} /><div className="absolute right-[7%] top-[10%] left-[44%] text-[3.5px] uppercase tracking-[0.32em]" style={{color:p}}>{brand.name} · 014</div><div className="absolute right-[7%] top-[24%] left-[44%] space-y-[2px]">{body(15, '#D4D2CB', 95)}</div></Page>),
    (<Page><div className="absolute inset-0" style={{background:`linear-gradient(45deg, ${p}55 0%, transparent 50%), linear-gradient(135deg, ${s}55 0%, transparent 50%), white`}} /><div className="absolute inset-[7%]"><div className="text-[10px] font-light mt-[14%]">Hello,</div><div className="mt-3 space-y-[2px]">{body(15)}</div></div></Page>),
    (<Page><div className="absolute inset-0" style={{background:`linear-gradient(225deg, ${p}, ${s}, ${p})`}} /><div className="absolute inset-[6%] rounded-2xl bg-white/95 backdrop-blur p-3"><div className="text-[3.5px] uppercase tracking-[0.32em]" style={{color:p}}>{brand.name} · 014</div><div className="text-[10px] font-light mt-2">A spring memo.</div><div className="mt-3 space-y-[2px]">{body(14)}</div></div></Page>),

    // ─── PENTAGRAM-FLEXIBLE (10)
    (<Page><div className="absolute inset-x-[7%] top-[7%] grid grid-cols-12 gap-[1px]">{Array.from({length:12}).map((_,i)=><div key={i} className="h-[3px]" style={{backgroundColor:i<7?p:'#E5E0D2'}} />)}</div><div className="absolute inset-x-[7%] top-[14%]"><div className="text-[16px] font-bold leading-none">{brand.name}</div><div className="text-[3.5px] uppercase tracking-[0.32em] mt-1" style={{color:p}}>spring · 2026</div></div><div className="absolute inset-x-[7%] top-[36%] space-y-[2px]">{body(15)}</div></Page>),
    (<Page><div className="absolute inset-x-[7%] top-[7%] grid grid-cols-8 gap-[1px]">{Array.from({length:8}).map((_,i)=><div key={i} className="aspect-square" style={{backgroundColor:[1,3,5].includes(i)?p:[0,2,4,6].includes(i)?'#0F1216':'#FBF8EE'}} />)}</div><div className="absolute inset-x-[7%] top-[26%] space-y-[2px]">{body(17)}</div></Page>),
    (<Page><div className="absolute inset-x-[7%] top-[7%] flex gap-1">{Array.from({length:6}).map((_,i)=><div key={i} className="h-[14px] flex-1" style={{backgroundColor:i===2?p:i%2===0?'#0F1216':'#FBF8EE'}} />)}</div><div className="absolute inset-x-[7%] top-[20%] space-y-[2px]">{body(18)}</div></Page>),
    (<Page><div className="absolute left-[7%] top-[7%] right-[7%] grid grid-cols-3 gap-1">{Array.from({length:3}).map((_,i)=><div key={i} className="aspect-square rounded-full" style={{backgroundColor:i===1?p:`${p}33`}} />)}</div><div className="absolute inset-x-[7%] top-[34%] space-y-[2px]">{body(16)}</div></Page>),
    (<Page><div className="absolute left-0 top-0 bottom-0 w-[6%]" style={{backgroundColor:p}} /><div className="absolute left-[6%] top-0 bottom-0 w-[6%] bg-[#0F1216]" /><div className="absolute inset-x-[16%] top-[8%] right-[7%] grid grid-cols-12 gap-1"><div className="col-span-12 text-[3.5px] uppercase tracking-[0.32em] font-bold">{brand.name}</div></div><div className="absolute left-[16%] right-[7%] top-[20%] space-y-[2px]">{body(17)}</div></Page>),
    (<Page><div className="absolute inset-x-[7%] top-[8%] flex flex-wrap gap-1">{Array.from({length:24}).map((_,i)=><div key={i} className="w-[5px] h-[5px] rounded-full" style={{backgroundColor:i%4===0?p:i%4===1?'#0F1216':'#E5E0D2'}} />)}</div><div className="absolute inset-x-[7%] top-[24%] space-y-[2px]">{body(17)}</div></Page>),
    (<Page><div className="absolute inset-x-[7%] top-[7%] h-[44px] grid grid-cols-12">{Array.from({length:12}).map((_,i)=>(<div key={i} className="border-r border-[#E5E0D2] last:border-r-0 flex items-end p-1"><div className="w-full" style={{height:`${30+(i*7)%60}%`,backgroundColor:i===5?p:'#0F1216'}} /></div>))}</div><div className="absolute inset-x-[7%] top-[36%] space-y-[2px]">{body(16)}</div></Page>),
    (<Page><div className="absolute inset-x-[7%] top-[7%] grid grid-cols-2 gap-1"><div className="aspect-[2/1]" style={{backgroundColor:p}} /><div className="aspect-[2/1] bg-[#0F1216]" /></div><div className="absolute inset-x-[7%] top-[24%] grid grid-cols-3 gap-1"><div className="aspect-square" style={{backgroundColor:`${p}66`}} /><div className="aspect-square bg-[#FBF8EE]" /><div className="aspect-square" style={{backgroundColor:p}} /></div><div className="absolute inset-x-[7%] top-[44%] space-y-[2px]">{body(13)}</div></Page>),
    (<Page><div className="absolute inset-x-[7%] top-[8%] grid grid-cols-12 grid-rows-3 gap-[2px]">{Array.from({length:36}).map((_,i)=><div key={i} className="h-[3px]" style={{backgroundColor:[2,5,9,11,15,16,18,22,25,28,29].includes(i)?p:'transparent'}} />)}</div><div className="absolute inset-x-[7%] top-[24%] space-y-[2px]">{body(17)}</div></Page>),
    (<Page><div className="absolute inset-x-[7%] top-[7%] flex items-center gap-1.5"><div className="w-[20px] h-[20px] rounded-full flex items-center justify-center text-white text-[8px] font-bold" style={{backgroundColor:p}}>{init}</div><div className="text-[3.5px] uppercase tracking-[0.32em] font-bold">{brand.name} · OFFICE OF VP</div></div><div className="absolute inset-x-[7%] top-[20%] space-y-[2px]">{body(18)}</div></Page>),

    // ─── EDITORIAL MIXED CREATIVE (15)
    (<Page><div className="absolute inset-x-[7%] top-[10%]"><div className="text-[36px] font-serif italic font-black leading-none" style={{color:p}}>"</div><div className="text-[14px] font-serif italic font-bold leading-tight mt-1">small things,<br/>made well.</div></div><div className="absolute inset-x-[7%] top-[42%] space-y-[2px]">{body(13)}</div><div className="absolute right-[7%] bottom-[6%] text-right text-[3.5px] uppercase tracking-[0.32em]" style={{color:p}}>— {brand.name}</div></Page>),
    (<Page><div className="absolute right-0 top-0 w-[20%] h-full" style={{backgroundColor:p}} /><div className="absolute inset-x-[7%] top-[10%] right-[27%]"><div className="text-[3.5px] uppercase tracking-[0.32em] text-gray-400">{brand.name} · 014</div><div className="text-[14px] font-serif font-bold mt-1">An open letter.</div></div><div className="absolute left-[7%] right-[27%] top-[28%] space-y-[2px]">{body(16)}</div></Page>),
    (<Page><div className="absolute inset-0 grid grid-rows-2"><div className="bg-[#FBF8EE] p-3 flex flex-col justify-end"><div className="text-[14px] font-serif italic" style={{color:p}}>Spring 2026</div><div className="text-[3.5px] uppercase tracking-[0.32em] mt-1 text-gray-500">— {brand.name}</div></div><div className="bg-white p-3 space-y-[2px]">{body(13)}</div></div></Page>),
    (<Page><div className="absolute inset-x-[7%] top-[10%]"><div className="text-[80px] font-serif font-black leading-none" style={{color:`${p}11`}}>14</div><div className="absolute right-0 top-[8%] text-right text-[3.5px] uppercase tracking-[0.32em]" style={{color:p}}>{brand.name} · spring</div></div><div className="absolute inset-x-[7%] top-[40%] space-y-[2px]">{body(15)}</div></Page>),
    (<Page><div className="absolute inset-x-[7%] top-[10%] flex justify-between items-baseline"><div className="text-[14px] font-serif font-bold">An Open Letter</div><div className="text-[3.5px] uppercase tracking-[0.32em] text-gray-400">№ 014</div></div><div className="absolute left-[7%] right-[7%] top-[20%] h-[1px]" style={{backgroundColor:p}} /><div className="absolute inset-x-[7%] top-[24%] space-y-[2px]">{body(17)}</div></Page>),
    (<Page><div className="absolute inset-x-[7%] top-[8%] grid grid-cols-3 gap-2 text-[3.5px]"><div><div className="uppercase tracking-[0.32em] text-gray-400">no.</div><div className="text-[10px] font-bold mt-0.5">14</div></div><div><div className="uppercase tracking-[0.32em] text-gray-400">date</div><div className="text-[5px] mt-0.5">27 / 04 / 26</div></div><div><div className="uppercase tracking-[0.32em] text-gray-400">by</div><div className="text-[5px] mt-0.5" style={{color:p}}>Jane Smith</div></div></div><div className="absolute inset-x-[7%] top-[28%] space-y-[2px]">{body(16)}</div></Page>),
    (<Page><div className="absolute inset-x-[7%] top-[8%]"><div className="border-y-2 py-2 border-black"><div className="text-center text-[10px] font-serif font-bold">{brand.name} JOURNAL</div></div></div><div className="absolute inset-x-[7%] top-[26%] space-y-[2px]">{body(17)}</div></Page>),
    (<Page><div className="absolute inset-x-[7%] top-[8%]"><BrandLogo brand={brand} size="xs" /></div><div className="absolute inset-x-[7%] top-[16%] flex items-baseline gap-2"><span className="text-[5px] uppercase tracking-[0.4em]" style={{color:p}}>spring</span><span className="text-[5px] uppercase tracking-[0.4em] text-gray-400">·</span><span className="text-[5px] uppercase tracking-[0.4em] text-gray-400">2026</span></div><div className="absolute inset-x-[7%] top-[26%] space-y-[2px]">{body(17)}</div></Page>),
    (<Page><div className="absolute inset-x-[7%] top-[10%] text-center"><div className="text-[18px] font-serif italic font-light text-gray-900">{brand.name}</div><div className="h-[1px] mx-auto w-[40%] mt-1" style={{backgroundColor:p}} /><div className="text-[3.5px] uppercase tracking-[0.4em] mt-1 text-gray-500">— a letter —</div></div><div className="absolute inset-x-[10%] top-[34%] space-y-[2px]">{body(15)}</div></Page>),
    (<Page><div className="absolute inset-x-[7%] top-[8%] flex items-center gap-1"><div className="w-[6px] h-[6px] rounded-full bg-[#7BC56A]" /><span className="text-[3.5px] uppercase tracking-[0.32em] text-gray-700">live · {brand.name.toLowerCase()}.com</span></div><div className="absolute inset-x-[7%] top-[16%]"><div className="text-[10px] font-medium">Spring update.</div></div><div className="absolute inset-x-[7%] top-[28%] space-y-[2px]">{body(17)}</div></Page>),
    (<Page><div className="absolute inset-x-[7%] top-[8%]"><div className="text-[5px] uppercase tracking-[0.32em] text-gray-400">— from the desk of —</div><div className="text-[12px] font-serif italic font-bold mt-1" style={{color:p}}>Jane Smith</div></div><div className="absolute inset-x-[7%] top-[24%] space-y-[2px]">{body(17)}</div></Page>),
    (<Page><div className="absolute inset-0 bg-[#0F1216] text-white"><div className="absolute inset-x-[7%] top-[8%] flex items-center gap-1.5"><div className="w-[6px] h-[6px] rounded-full" style={{backgroundColor:p}} /><span className="text-[3.5px] uppercase tracking-[0.32em] opacity-90">{brand.name} · 014</span></div><div className="absolute inset-x-[7%] top-[18%] space-y-[2px]">{body(18, 'rgba(255,255,255,0.25)', 80)}</div></div></Page>),
    (<Page><div className="absolute inset-x-[7%] top-[8%] grid grid-cols-12"><div className="col-span-1 text-[3.5px] uppercase tracking-[0.32em] text-gray-400 self-end">A.</div><div className="col-span-11 text-[3.5px] uppercase tracking-[0.32em] font-bold border-b border-black pb-1">{brand.name} · A LETTER · 014</div></div><div className="absolute inset-x-[7%] top-[20%] space-y-[2px]">{body(18)}</div></Page>),
    (<Page><div className="absolute left-[7%] top-[7%] right-[7%] flex items-end gap-3"><div className="text-[40px] font-serif font-black leading-none" style={{color:p}}>{init}.</div><div><div className="text-[3.5px] uppercase tracking-[0.32em] text-gray-400">a letter from</div><div className="text-[7px] font-bold mt-1">{brand.name}</div></div></div><div className="absolute inset-x-[7%] top-[30%] space-y-[2px]">{body(17)}</div></Page>),
    (<Page><div className="absolute inset-x-[7%] top-[10%]"><div className="grid grid-cols-2 gap-2 text-[3.5px] uppercase tracking-[0.32em]"><div><div className="text-gray-400">{brand.name}</div><div className="text-gray-700">— a small studio</div></div><div className="text-right"><div className="text-gray-400">no. 014</div><div className="text-gray-700">— spring 2026</div></div></div></div><div className="absolute inset-x-[7%] top-[26%] space-y-[2px]">{body(17)}</div></Page>),
  ];

  return designs[templateIndex] ?? designs[0];
}

export const LETTERHEAD_EXTENDED_2 = Array.from({ length: 100 }, (_, i) => ({
  idSuffix: `ext-${i + 31}`,
  name: `Wave 2 · ${String(i + 1).padStart(2, '0')}`,
  category: 'Modern',
}));
