import type { Brand } from '@/shared/types/brand';
import { BrandLogo } from '@/features/brandkit/components/renderers/BrandLogo';

/** Billboard mockups — 30 outdoor-poster scenes with brand artwork. */
interface Props { brand: Brand; templateIndex: number }

function BillboardFrame({ children }: { children: React.ReactNode }) {
  return (
    <div className="w-full h-full bg-[#3F4348] flex items-center justify-center p-[3%]">
      <div className="relative w-[88%] h-[80%]">
        <div className="absolute inset-0 bg-black p-[2px] shadow-2xl">
          <div className="w-full h-full overflow-hidden bg-white">{children}</div>
        </div>
        <div className="absolute -bottom-[8%] left-[10%] w-[3%] h-[24%] bg-[#1F2429]" />
        <div className="absolute -bottom-[8%] right-[10%] w-[3%] h-[24%] bg-[#1F2429]" />
      </div>
    </div>
  );
}

export function MockupBillboardExtendedRenderer({ brand, templateIndex }: Props) {
  const p = brand.primaryColor;
  const init = brand.name.charAt(0).toUpperCase();

  const compositions = [
    (<div className="w-full h-full flex items-center justify-center" style={{backgroundColor:p}}><div className="text-center text-white"><BrandLogo brand={brand} size="lg" color="#fff" /><div className="text-[8px] uppercase tracking-[0.32em] mt-2 opacity-90">{brand.name}</div></div></div>),
    (<div className="w-full h-full flex items-center justify-center bg-white"><div className="text-[40px] font-serif font-black" style={{color:p}}>{brand.name}.</div></div>),
    (<div className="w-full h-full flex"><div className="w-1/2" style={{backgroundColor:p}} /><div className="w-1/2 bg-white flex items-center justify-center"><div className="text-center"><div className="text-[5px] uppercase tracking-[0.32em] text-gray-500">launching</div><div className="text-[18px] font-serif font-black" style={{color:p}}>SS 2026</div></div></div></div>),
    (<div className="w-full h-full" style={{ background: `linear-gradient(135deg, ${p} 0%, ${p}66 100%)` }}><div className="absolute inset-0 flex items-center justify-center text-white text-center"><div><div className="text-[20px] font-serif italic font-bold">make better.</div><div className="text-[6px] uppercase tracking-[0.32em] mt-2 opacity-90">— {brand.name}</div></div></div></div>),
    (<div className="w-full h-full bg-[#0F1216] text-white flex items-center justify-center"><div className="text-center"><div className="text-[6px] uppercase tracking-[0.32em] opacity-70" style={{color:p}}>● ON AIR</div><div className="text-[24px] font-mono font-extrabold tracking-tight">{brand.name.toUpperCase()}</div></div></div>),
    (<div className="w-full h-full bg-white p-3 flex items-center"><div className="text-[36px] leading-none font-serif" style={{color:p}}>"</div><div className="ml-2"><div className="text-[10px] font-serif italic font-bold text-gray-900">a small studio.</div><div className="text-[10px] font-serif italic font-bold text-gray-900">big ideas.</div><div className="text-[5px] uppercase tracking-[0.32em] mt-2" style={{color:p}}>— {brand.name}</div></div></div>),
    (<div className="w-full h-full" style={{ background: `radial-gradient(140% 80% at 30% 30%, ${p} 0%, ${p}AA 35%, transparent 80%)` }}><div className="absolute inset-0 flex items-center justify-center"><div className="bg-white/70 backdrop-blur rounded-md px-4 py-2"><div className="text-[14px] font-bold" style={{color:p}}>{brand.name}.com</div></div></div></div>),
    (<div className="w-full h-full bg-[#FAF6EE]"><div className="absolute -left-[6%] -top-[40%] w-[80%] aspect-square rounded-full" style={{ background: `conic-gradient(from 180deg, ${p} 0deg, ${p}99 30deg, transparent 60deg, ${p} 90deg, transparent 150deg, ${p} 180deg)`, opacity:0.85 }} /><div className="absolute right-[6%] top-1/2 -translate-y-1/2 text-right"><div className="text-[20px] font-serif font-black text-gray-900">{brand.name}</div><div className="text-[6px] uppercase tracking-[0.32em] mt-1" style={{color:p}}>since 2026</div></div></div>),
    (<div className="w-full h-full bg-white p-3 flex flex-col justify-center" style={{ lineHeight: 0.85 }}>{Array.from({length:4}).map((_,i)=><div key={i} className="text-[26px] font-serif font-black uppercase tracking-tight" style={{ color: i===1?p:`${p}33` }}>{brand.name}</div>)}</div>),
    (<div className="w-full h-full flex items-center justify-center bg-[#FAF6EE]"><div className="-rotate-6 border-2 px-3 py-2" style={{ borderColor: p, color: p }}><div className="text-[6px] uppercase tracking-[0.32em] text-center">approved</div><div className="text-[20px] font-serif font-black leading-none">{brand.name}</div></div></div>),
    (<div className="w-full h-full grid grid-cols-3"><div style={{backgroundColor:p}} className="flex items-center justify-center"><div className="text-white text-[20px] font-serif font-black">{init}</div></div><div className="bg-white" /><div className="bg-[#0F1216]" /></div>),
    (<div className="w-full h-full bg-[#FBF8EE] p-3 flex items-center"><div className="text-[80px] font-bold tabular-nums leading-none" style={{color:p}}>14</div><div className="ml-3"><div className="text-[6px] uppercase tracking-[0.32em] text-gray-500">issue</div><div className="text-[16px] font-serif font-bold">spring 2026</div><div className="text-[6px] uppercase tracking-[0.32em] mt-1" style={{color:p}}>— {brand.name}</div></div></div>),
    (<div className="w-full h-full bg-white"><div className="absolute inset-0" style={{ background: p, clipPath: 'polygon(0 0, 100% 0, 100% 70%, 0 100%)' }} /><div className="absolute right-[6%] bottom-[8%] text-right"><div className="text-[10px] font-bold text-gray-900">make less. ship more.</div><div className="text-[5px] uppercase tracking-[0.32em] mt-1" style={{color:p}}>{brand.name}</div></div></div>),
    (<div className="w-full h-full bg-[#FBF8EE]"><div className="absolute left-0 right-0 bottom-0 h-[55%]" style={{backgroundColor:p}} /><div className="absolute left-0 right-0 bottom-[55%] h-[12%]" style={{backgroundColor:`${p}77`}} /><div className="absolute right-[16%] top-[14%] w-[14%] aspect-square rounded-full bg-white/70" /><div className="absolute left-[6%] bottom-[8%] text-white"><div className="text-[16px] font-serif font-bold">{brand.name}</div></div></div>),
    (<div className="w-full h-full bg-white flex items-center justify-center"><div className="text-center"><div className="text-[5px] uppercase tracking-[0.32em]" style={{color:p}}>NOW HIRING</div><div className="text-[18px] font-serif font-black mt-1">join the studio.</div><div className="text-[5px] uppercase tracking-[0.32em] mt-1 text-gray-500">{brand.name.toLowerCase()}.com/jobs</div></div></div>),
    (<div className="w-full h-full bg-[#0F1216]"><div className="absolute inset-0 opacity-15" style={{ backgroundImage: 'linear-gradient(to right, #fff 1px, transparent 1px), linear-gradient(to bottom, #fff 1px, transparent 1px)', backgroundSize: '12px 12px' }} /><div className="absolute inset-0 flex items-center justify-center"><div className="text-center text-white"><div className="text-[6px] uppercase tracking-[0.32em]" style={{color:p}}>{brand.name.toUpperCase()} / SYS</div><div className="text-[24px] font-mono font-extrabold mt-1">RUN.LIVE</div></div></div></div>),
    (<div className="w-full h-full" style={{backgroundColor:p}}><div className="absolute inset-x-0 top-1/3 h-[30%] bg-white flex items-center justify-center"><div className="text-[14px] font-bold" style={{color:p}}>{brand.name}</div></div></div>),
    (<div className="w-full h-full bg-[#FAF6EE] flex items-center justify-center"><div className="text-center"><div className="text-[60px] leading-none font-serif" style={{color:p}}>"</div><div className="text-[10px] font-serif italic">a brand worth knowing.</div><div className="text-[5px] uppercase tracking-[0.32em] mt-1 text-gray-500">— a happy client</div></div></div>),
    (<div className="w-full h-full bg-white p-3 grid grid-cols-2 gap-2"><div className="rounded p-2" style={{backgroundColor:p}}><div className="text-white text-[12px] font-bold">make.</div></div><div className="rounded p-2 border-2" style={{borderColor:p}}><div className="text-[12px] font-bold" style={{color:p}}>better.</div></div></div>),
    (<div className="w-full h-full bg-white"><div className="absolute inset-0 grid grid-cols-12">{Array.from({length:12}).map((_,i)=><div key={i} style={{borderRight:'1px solid #00000010'}} />)}</div><div className="absolute inset-0 flex items-center justify-center"><div className="text-[24px] font-bold tracking-tight" style={{color:p}}>{brand.name}.</div></div></div>),
    (<div className="w-full h-full bg-[#FAF6EE]" style={{ background: `repeating-linear-gradient(0deg, ${p} 0 8px, #FAF6EE 8px 16px)` }}><div className="absolute inset-0 flex items-center justify-center"><div className="bg-white px-4 py-2 shadow-md"><div className="text-[14px] font-bold text-gray-900">{brand.name}</div></div></div></div>),
    (<div className="w-full h-full bg-[#0F1216]"><div className="absolute inset-0" style={{ background: `radial-gradient(60% 80% at 30% 50%, ${p}AA 0%, transparent 70%)` }} /><div className="absolute left-[6%] top-1/2 -translate-y-1/2 text-white"><BrandLogo brand={brand} size="lg" color="#fff" /><div className="text-[16px] font-serif font-bold mt-2">{brand.name}</div></div></div>),
    (<div className="w-full h-full bg-white p-3 flex flex-col justify-center"><div className="text-[5px] uppercase tracking-[0.32em] mb-1" style={{color:p}}>— manifesto —</div>{['Make less.','Make better.','Make it last.'].map((s,i)=>(<div key={i} className="text-[14px] font-serif italic font-bold" style={{color:i===1?p:'#0F1216'}}>{s}</div>))}</div>),
    (<div className="w-full h-full grid grid-cols-2"><div className="bg-white flex items-center justify-center"><BrandLogo brand={brand} size="lg" color={p} /></div><div className="flex items-center justify-center" style={{backgroundColor:p}}><div className="text-white text-[14px] font-serif font-bold">— studio</div></div></div>),
    (<div className="w-full h-full" style={{ background: `linear-gradient(180deg, ${p} 0%, ${p}88 50%, #FBF8EE 100%)` }}><div className="absolute right-[14%] top-[14%] w-[14%] aspect-square rounded-full bg-white/80" /><div className="absolute left-[6%] bottom-[10%]"><div className="text-[14px] font-serif italic font-bold text-gray-900">good morning,</div><div className="text-[20px] font-serif font-black mt-0.5" style={{color:p,filter:'brightness(0.65)'}}>{brand.name}</div></div></div>),
    (<div className="w-full h-full bg-[#FBF8EE] flex items-center justify-center"><div className="text-center"><div className="text-[20px] font-serif font-black tracking-tight">{brand.name}</div><div className="h-[2px] mx-auto w-[40%] my-1" style={{backgroundColor:p}} /><div className="text-[6px] uppercase tracking-[0.32em] text-gray-500">a studio · est. 2026</div></div></div>),
    (<div className="w-full h-full bg-white p-3"><div className="text-[5px] uppercase tracking-[0.32em] text-gray-500">{brand.name} · 014</div><div className="text-[24px] font-serif font-black mt-1" style={{color:p}}>spring</div><div className="text-[24px] font-serif font-black -mt-1">issue.</div></div>),
    (<div className="w-full h-full" style={{backgroundColor:p}}><div className="absolute inset-0 flex items-center justify-center text-white text-center"><div><div className="text-[5px] uppercase tracking-[0.32em] opacity-80">— launching —</div><div className="text-[24px] font-serif font-black mt-1">SS 2026</div><div className="text-[5px] uppercase tracking-[0.32em] mt-1 opacity-80">{brand.name.toLowerCase()}.com</div></div></div></div>),
    (<div className="w-full h-full grid grid-cols-3 grid-rows-2 gap-[1px] bg-white">{Array.from({length:6}).map((_,i)=>(<div key={i} className="flex items-center justify-center" style={{backgroundColor: i===2?p:i%2===0?'#FBF8EE':'#0F1216',color:i%2===0?'#0F1216':'#fff'}}><span className="text-[10px] font-bold">{['M','A','K','E','I','T'][i]}</span></div>))}</div>),
    (<div className="w-full h-full bg-[#FBF8EE] flex items-center justify-center"><div className="text-center"><BrandLogo brand={brand} size="xl" color={p} /><div className="text-[8px] uppercase tracking-[0.4em] mt-3 text-gray-700">— since 2026 —</div></div></div>),
  ];

  return <BillboardFrame>{compositions[templateIndex] ?? compositions[0]}</BillboardFrame>;
}

export const MOCKUP_BILLBOARD_EXTENDED = Array.from({length:30},(_,i)=>({idSuffix:`ext-${i+1}`,name:['Solid','Big Type','Split','Italic','Mono Sys','Quote','Frosted','Sun','Type Wall','Stamp','Triple','Number','Diagonal','Mountain','Hiring','Brutalist','Bar','Editorial Quote','Two Cards','Grid','Stripes','Spotlight','Manifesto','Dual','Sunset','Underline','Issue','Launch','Letter Tiles','Crest'][i],category:'Environment'}));
