import type { Brand } from '@/shared/types/brand';
import { BrandLogo } from '@/features/brandkit/components/renderers/BrandLogo';

/**
 * Notecard — Wave 2: 100 new designs (idx 0-99). Folded greeting
 * card; cosmos tile shows the front face on the left half + a hint
 * of the inside on the right.
 */
interface Props { brand: Brand; templateIndex: number }

function C({ children, accent }: { children: React.ReactNode; accent?: string }) {
  return (
    <div className="w-full h-full bg-[#EFE9DA] flex items-center justify-center p-[6%]">
      <div className="flex shadow-md" style={{ width: '78%', aspectRatio: '1.6 / 1' }}>
        <div className="w-1/2 h-full relative overflow-hidden bg-white">{children}</div>
        <div className="w-1/2 h-full bg-[#FBF8EE] flex items-center justify-center"><span className="text-[5px] italic -rotate-3" style={{color:accent ?? '#aaa'}}>— inside —</span></div>
      </div>
    </div>
  );
}

export function NotecardExtended2Renderer({ brand, templateIndex }: Props) {
  const p = brand.primaryColor;
  const s = brand.secondaryColor || '#0F1216';
  const init = brand.name.charAt(0).toUpperCase();
  const N = brand.name.toUpperCase();

  const designs: React.ReactNode[] = [
    // Apple-restrained (15)
    (<C><div className="absolute inset-0 flex items-center justify-center"><div className="text-center"><div className="text-[24px] font-light text-gray-900">Hi.</div><div className="text-[5px] uppercase tracking-[0.32em] mt-2 text-gray-500">{brand.name}</div></div></div></C>),
    (<C><div className="absolute inset-0 flex items-center justify-center"><BrandLogo brand={brand} size="lg" color={p} /></div></C>),
    (<C><div className="absolute inset-x-[10%] bottom-[12%]"><div className="text-[10px] font-light text-gray-900">Thank you,</div><div className="text-[3.5px] uppercase tracking-[0.32em] mt-1 text-gray-500">— {brand.name}</div></div></C>),
    (<C><div className="absolute inset-x-[10%] top-[12%]"><div className="text-[3.5px] uppercase tracking-[0.32em] text-gray-400">— a small note —</div></div><div className="absolute inset-x-[10%] bottom-[12%]"><div className="text-[14px] font-light">Hello.</div></div></C>),
    (<C><div className="absolute inset-0 flex items-center justify-center"><div className="text-[60px] font-light leading-none text-gray-900">{init}</div></div></C>),
    (<C><div className="absolute inset-0 bg-[#F5F5F7]" /><div className="absolute inset-[8%] bg-white rounded-md flex items-center justify-center"><div className="text-center"><div className="text-[7px] font-medium">A note</div><div className="text-[3.5px] uppercase tracking-[0.32em] mt-1 text-gray-400">{brand.name}</div></div></div></C>),
    (<C><div className="absolute inset-x-[10%] top-[20%]"><div className="text-[3.5px] uppercase tracking-[0.4em] text-gray-400">— from —</div></div><div className="absolute inset-x-[10%] bottom-[20%]"><div className="text-[12px] font-light text-gray-900">Jane.</div></div></C>),
    (<C><div className="absolute inset-x-[10%] top-1/2 -translate-y-1/2"><div className="text-[3.5px] uppercase tracking-[0.32em] text-gray-400">{brand.name}</div><div className="text-[10px] font-light mt-1">Hello,</div><div className="h-[1px] w-[40%] mt-1" style={{backgroundColor:p}} /></div></C>),
    (<C><div className="absolute inset-0 flex items-center justify-center bg-[#FBF8EE]"><div className="text-center"><div className="text-[14px] font-light">A small thanks.</div></div></div></C>),
    (<C><div className="absolute inset-x-[10%] top-[14%]"><BrandLogo brand={brand} size="xs" /></div><div className="absolute inset-x-[10%] bottom-[14%]"><div className="text-[3.5px] uppercase tracking-[0.4em] text-gray-400">— a quiet card —</div></div></C>),
    (<C><div className="absolute inset-0 flex items-center justify-center"><div className="text-center"><div className="text-[3.5px] uppercase tracking-[0.5em] text-gray-400">— for —</div><div className="text-[10px] font-serif italic mt-1" style={{color:p}}>you.</div></div></div></C>),
    (<C><div className="absolute inset-x-[8%] top-[16%] flex items-center gap-1"><div className="w-[5px] h-[5px] rounded-full" style={{backgroundColor:p}} /><span className="text-[3.5px] uppercase tracking-[0.32em]">{brand.name} · live</span></div><div className="absolute inset-x-[8%] bottom-[16%] text-[10px] font-light">A note,</div></C>),
    (<C><div className="absolute inset-0 grid grid-rows-2"><div className="bg-[#FBF8EE] flex items-end p-2"><div className="text-[7px] font-medium">{brand.name}</div></div><div className="bg-white flex items-start p-2"><div className="text-[10px] font-light">Hello.</div></div></div></C>),
    (<C><div className="absolute inset-x-[10%] top-1/2 -translate-y-1/2 text-center"><div className="text-[14px] font-light text-gray-900">Hi,</div><div className="text-[3.5px] uppercase tracking-[0.32em] mt-1" style={{color:p}}>{brand.name}</div></div></C>),
    (<C><div className="absolute inset-x-[8%] top-[12%]"><div className="text-[3.5px] uppercase tracking-[0.32em] text-gray-400">a card from</div></div><div className="absolute inset-x-[8%] top-1/2 -translate-y-1/2"><div className="text-[14px] font-light">{brand.name}.</div></div></C>),

    // Brutalist (15)
    (<C accent="#fff"><div className="absolute inset-0 bg-yellow-300 p-[6%] font-mono"><div className="text-[5px] uppercase tracking-[0.22em] font-bold">{N} :: HELLO</div><div className="text-[18px] font-extrabold uppercase mt-2 leading-none">DEAR.</div></div></C>),
    (<C accent="#fff"><div className="absolute inset-0 bg-black text-yellow-300 p-[6%] font-mono"><div className="text-[5px] uppercase tracking-[0.22em] opacity-80">{`> echo "hi"`}</div><div className="text-[14px] font-extrabold mt-2 leading-none">HELLO.</div><div className="text-[5px] mt-2 opacity-80">{`>> ${brand.name.toLowerCase()}`}</div></div></C>),
    (<C accent="#fff"><div className="absolute inset-0 bg-[#FF3B30] p-[6%] font-mono text-white"><div className="text-[5px] uppercase tracking-[0.22em] opacity-90">!! READ ME</div><div className="text-[18px] font-extrabold uppercase mt-2 leading-[0.92]">URGENT.</div></div></C>),
    (<C><div className="absolute inset-0 p-[6%] font-mono"><div className="text-[5px] uppercase tracking-[0.22em] border-b-4 border-black pb-1">CARD/{init}.HELLO</div><div className="text-[18px] font-extrabold uppercase mt-2 leading-none">JANE,<br/>READ.</div></div></C>),
    (<C><div className="absolute inset-0" style={{ background: 'repeating-linear-gradient(0deg, #000 0 2px, #fff 2px 4px)' }}><div className="absolute inset-[14%] bg-white p-2 font-mono"><div className="text-[5px] uppercase tracking-[0.22em] font-bold">{brand.name}</div><div className="text-[12px] font-extrabold uppercase mt-1">HELLO.</div></div></div></C>),
    (<C accent="#fff"><div className="absolute inset-0 bg-[#39FF14] p-[6%] font-mono"><div className="text-[14px] font-extrabold uppercase">[OK]</div><div className="text-[5px] uppercase tracking-[0.22em] mt-1">DELIVERED → JANE</div></div></C>),
    (<C><div className="absolute inset-0 p-[6%] font-mono grid grid-cols-2 gap-1"><div className="bg-black text-white p-1.5 text-[5px] uppercase tracking-[0.22em] font-bold flex items-center justify-center">FROM</div><div className="border-2 border-black p-1.5 text-[5px] uppercase tracking-[0.22em] font-bold flex items-center justify-center">TO</div><div className="border-2 border-black p-1.5 text-[7px] font-extrabold flex items-center justify-center">{N}</div><div className="bg-black text-white p-1.5 text-[7px] font-extrabold flex items-center justify-center">JANE</div></div></C>),
    (<C accent="#fff"><div className="absolute inset-0 bg-[#0F1216] text-yellow-300 p-[6%] font-mono"><div className="text-[3.5px] uppercase tracking-[0.22em] opacity-80">root@{brand.name.toLowerCase()}:</div><div className="text-[10px] font-extrabold mt-2">say.hi(jane)</div></div></C>),
    (<C><div className="absolute inset-0 p-[6%] flex items-center font-mono"><div className="text-[36px] font-extrabold uppercase leading-none">HEY!</div></div></C>),
    (<C><div className="absolute inset-0 bg-yellow-300 p-[6%] font-mono"><div className="border-2 border-black inline-block px-2 py-0.5 -rotate-3"><span className="text-[5px] uppercase tracking-[0.22em] font-bold">CONFIDENTIAL</span></div><div className="text-[14px] font-extrabold uppercase mt-2">FOR JANE.</div></div></C>),
    (<C><div className="absolute inset-0 p-[6%] font-mono"><div className="text-[24px] font-extrabold leading-[0.85] uppercase">JANE,<br/><span style={{color:p}}>HI.</span></div></div></C>),
    (<C accent="#fff"><div className="absolute inset-0" style={{backgroundColor:p}}><div className="p-[6%] font-mono text-white"><div className="text-[5px] uppercase tracking-[0.22em] opacity-90">!! HOT NOTE</div><div className="text-[16px] font-extrabold uppercase mt-2 leading-none">READ.</div></div></div></C>),
    (<C><div className="absolute inset-0 p-[6%] font-mono"><div className="text-[5px] uppercase tracking-[0.22em] border-b-2 border-black pb-1">FILE: NOTE_HI.{brand.name.toLowerCase()}</div><div className="text-[14px] font-extrabold mt-2">DEAR_JANE.</div></div></C>),
    (<C><div className="absolute inset-0 p-[6%] font-mono"><div className="text-[5px] uppercase tracking-[0.22em] font-bold">[draft 002]</div><div className="text-[18px] font-extrabold leading-none mt-1 uppercase">HELLO,<br/>JANE.</div></div></C>),
    (<C accent="#fff"><div className="absolute inset-0 bg-black text-white p-[6%] font-mono"><div className="text-[3.5px] uppercase tracking-[0.32em] text-white/60">— a note —</div><div className="text-[10px] font-extrabold mt-2"><span className="opacity-60">$</span> say.hi</div></div></C>),

    // Swiss / Vignelli (15)
    (<C><div className="absolute inset-0 p-[7%] flex flex-col justify-between"><div className="text-[3.5px] uppercase tracking-[0.32em] font-bold border-b-2 border-black pb-0.5">{brand.name}</div><div className="text-[12px] font-bold leading-none">Hello,<br/>Jane.</div><div className="text-[3.5px] uppercase tracking-[0.32em] border-t-2 border-black pt-0.5" style={{color:p}}>NOTE 014</div></div></C>),
    (<C><div className="absolute inset-0 p-[7%]"><div className="border-y-2 border-black py-1.5 text-center text-[3.5px] uppercase tracking-[0.4em] font-bold">{brand.name} · NOTE</div><div className="text-[10px] font-bold mt-3 text-center">Jane Smith</div></div></C>),
    (<C><div className="absolute inset-0 p-[7%] grid grid-cols-12 gap-1"><div className="col-span-12 text-[3.5px] uppercase tracking-[0.32em] font-bold border-b-2 border-black pb-0.5">{brand.name} · NOTE A · 014</div><div className="col-span-12 mt-3"><div className="text-[12px] font-bold">An open note.</div></div></div></C>),
    (<C><div className="absolute left-[5%] top-[7%] bottom-[7%] w-[1px] bg-black" /><div className="absolute right-[5%] top-[7%] bottom-[7%] w-[1px]" style={{backgroundColor:p}} /><div className="absolute inset-0 flex items-center justify-center"><div className="text-center"><div className="text-[3.5px] uppercase tracking-[0.32em] font-bold">{brand.name}</div><div className="text-[12px] font-bold mt-1">Hello.</div></div></div></C>),
    (<C><div className="absolute inset-0 p-[7%] flex flex-col justify-center"><div className="text-[5px] uppercase tracking-[0.32em] font-bold">{brand.name}</div><div className="h-[2px] w-[40%] my-2" style={{backgroundColor:p}} /><div className="text-[7px] uppercase tracking-[0.32em]">A NOTE — JANE SMITH</div></div></C>),
    (<C><div className="absolute inset-0 p-[7%] grid grid-rows-3"><div className="text-[3.5px] uppercase tracking-[0.32em] font-bold">{brand.name}</div><div className="text-[14px] font-bold flex items-center">Hi.</div><div className="text-[3.5px] uppercase tracking-[0.32em] self-end" style={{color:p}}>014 / 2026</div></div></C>),
    (<C><div className="absolute inset-x-[5%] top-[5%] flex justify-between text-[3.5px] uppercase tracking-[0.32em] font-bold border-b-2 border-black pb-0.5"><span>{brand.name}</span><span>014</span></div><div className="absolute inset-x-[5%] top-1/2 -translate-y-1/2 text-[12px] font-bold text-center">A small note.</div></C>),
    (<C><div className="absolute inset-0 grid grid-cols-3"><div className="bg-black flex items-center justify-center"><span className="text-white text-[14px] font-bold">{init}</span></div><div className="col-span-2 p-[7%] flex flex-col justify-center"><div className="text-[3.5px] uppercase tracking-[0.32em] font-bold">{brand.name}</div><div className="text-[10px] font-bold mt-1">Hi, Jane.</div></div></div></C>),
    (<C><div className="absolute inset-x-[7%] top-[10%]"><div className="text-[24px] font-bold leading-none tabular-nums" style={{color:p}}>014.</div><div className="text-[3.5px] uppercase tracking-[0.32em] mt-1">— a note —</div></div></C>),
    (<C><div className="absolute inset-0 p-[7%]"><div className="text-[3.5px] uppercase tracking-[0.32em] font-bold border-b border-black pb-0.5">SECTION A · NOTE</div><div className="text-[12px] font-bold mt-3">Hello,</div></div></C>),
    (<C><div className="absolute inset-x-[6%] top-[8%] right-[6%] flex items-center"><span className="text-[3.5px] uppercase tracking-[0.32em] font-bold">{brand.name}</span><div className="flex-1 h-[1px] bg-black mx-1" /><span className="text-[3.5px] uppercase tracking-[0.32em] font-bold">JANE</span></div><div className="absolute inset-x-[6%] top-1/2 -translate-y-1/2 text-center"><div className="text-[10px] font-bold">Hello.</div></div></C>),
    (<C><div className="absolute inset-0 p-[7%]"><div className="text-[3.5px] uppercase tracking-[0.32em] font-bold border-y-2 border-black py-0.5 text-center">A — {brand.name} — 014</div><div className="text-[12px] font-bold mt-3 text-center">Hi.</div></div></C>),
    (<C><div className="absolute inset-0 p-[7%] flex flex-col justify-between"><BrandLogo brand={brand} size="xs" /><div className="text-[14px] font-bold leading-none">Hello.</div><div className="text-[3.5px] uppercase tracking-[0.32em] border-t-2 border-black pt-0.5">— from {brand.name}</div></div></C>),
    (<C><div className="absolute inset-x-[7%] top-[10%] grid grid-cols-3 text-[3.5px] uppercase tracking-[0.32em] font-bold"><span>{brand.name}</span><span className="text-center">·</span><span className="text-right">JANE</span></div><div className="absolute inset-x-[7%] bottom-[10%] text-[12px] font-bold">Hello.</div></C>),
    (<C><div className="absolute inset-x-[6%] top-1/2 -translate-y-1/2 grid grid-cols-12"><div className="col-span-2 text-[3.5px] uppercase tracking-[0.32em] text-gray-400 self-end">NO.</div><div className="col-span-10 text-[16px] font-bold tabular-nums">14</div></div></C>),

    // Bento (10)
    (<C><div className="absolute inset-[5%] grid grid-cols-3 grid-rows-2 gap-1"><div className="rounded-lg col-span-2 row-span-2 flex items-center justify-center" style={{backgroundColor:p}}><span className="text-white text-[14px] font-bold">Hi.</span></div><div className="rounded-lg bg-[#FBF8EE]" /><div className="rounded-lg bg-[#0F1216]" /></div></C>),
    (<C><div className="absolute inset-[5%] grid grid-cols-2 grid-rows-3 gap-1"><div className="row-span-2 rounded-lg flex items-center justify-center" style={{backgroundColor:p}}><BrandLogo brand={brand} size="md" color="#fff" /></div><div className="rounded-lg bg-[#0F1216] flex items-center justify-center"><span className="text-white text-[7px] font-bold">JANE</span></div><div className="rounded-lg bg-[#FBF8EE] flex items-center justify-center"><span className="text-[7px] font-bold">SMITH</span></div><div className="col-span-2 rounded-lg bg-white border flex items-center justify-center"><span className="text-[5px] uppercase tracking-[0.32em]">— a note —</span></div></div></C>),
    (<C><div className="absolute inset-[5%] grid grid-cols-3 grid-rows-3 gap-1"><div className="col-span-3 rounded bg-[#FBF8EE] flex items-center justify-center"><span className="text-[5px] uppercase tracking-[0.32em]">{brand.name}</span></div><div className="row-span-2 rounded" style={{backgroundColor:p}} /><div className="col-span-2 row-span-2 rounded bg-white border flex items-center justify-center"><span className="text-[12px] font-bold">Hi.</span></div></div></C>),
    (<C><div className="absolute inset-[5%] grid grid-cols-4 grid-rows-2 gap-1"><div className="col-span-3 row-span-2 rounded-2xl bg-white border flex items-end p-2"><div><div className="text-[10px] font-bold">Hello,</div><div className="text-[10px] font-bold">Jane.</div></div></div><div className="rounded-2xl flex items-center justify-center" style={{backgroundColor:p}}><span className="text-white text-[7px] font-bold">14</span></div><div className="rounded-2xl bg-[#0F1216]" /></div></C>),
    (<C><div className="absolute inset-[5%] grid grid-cols-2 gap-1"><div className="rounded-2xl flex items-center justify-center" style={{backgroundColor:p}}><BrandLogo brand={brand} size="lg" color="#fff" /></div><div className="rounded-2xl bg-white border p-2 flex flex-col justify-between"><div className="text-[3.5px] uppercase tracking-[0.32em] text-gray-400">a note</div><div className="text-[10px] font-bold">Hi.</div></div></div></C>),
    (<C><div className="absolute inset-[5%] grid grid-cols-3 grid-rows-3 gap-1"><div className="row-span-3 rounded bg-[#FBF8EE] flex items-end p-2"><div className="text-[7px] font-bold">{brand.name}</div></div><div className="col-span-2 rounded flex items-center justify-center" style={{backgroundColor:p}}><span className="text-white text-[7px] font-bold">JANE</span></div><div className="col-span-2 row-span-2 rounded bg-white border flex items-center justify-center"><span className="text-[14px] font-bold">Hi.</span></div></div></C>),
    (<C><div className="absolute inset-[5%] grid grid-cols-2 grid-rows-2 gap-1.5"><div className="rounded-3xl col-span-2 flex items-center justify-center" style={{backgroundColor:p}}><span className="text-white text-[14px] font-bold">Hello.</span></div><div className="rounded-3xl bg-[#0F1216] flex items-center justify-center"><span className="text-white text-[5px] uppercase tracking-[0.32em]">{brand.name}</span></div><div className="rounded-3xl bg-[#FBF8EE] flex items-center justify-center"><span className="text-[5px] uppercase tracking-[0.32em]">— jane —</span></div></div></C>),
    (<C><div className="absolute inset-[5%] grid grid-cols-3 grid-rows-2 gap-1"><div className="rounded-lg" style={{backgroundColor:p}} /><div className="rounded-lg bg-[#FBF8EE]" /><div className="rounded-lg bg-[#0F1216]" /><div className="col-span-3 rounded-lg bg-white border flex items-center justify-center"><span className="text-[12px] font-bold">Hi, Jane.</span></div></div></C>),
    (<C><div className="absolute inset-[5%] grid grid-cols-4 grid-rows-3 gap-[3px]"><div className="col-span-4 rounded bg-[#FBF8EE] p-1 text-[3.5px] uppercase tracking-[0.32em] flex items-center"><BrandLogo brand={brand} size="xs" /><span className="ml-1">{brand.name}</span></div><div className="col-span-2 row-span-2 rounded flex items-center justify-center" style={{backgroundColor:p}}><span className="text-white text-[14px] font-bold">Hi.</span></div><div className="col-span-2 rounded bg-[#0F1216] flex items-center justify-center"><span className="text-white text-[5px]">JANE</span></div><div className="col-span-2 rounded bg-white border flex items-center justify-center"><span className="text-[5px]">SMITH</span></div></div></C>),
    (<C><div className="absolute inset-[5%] grid grid-cols-2 grid-rows-3 gap-1"><div className="row-span-3 rounded-2xl bg-white border p-2 flex flex-col justify-between"><div className="text-[3.5px] uppercase tracking-[0.32em] text-gray-400">— from —</div><div><div className="text-[10px] font-bold">Hello.</div><div className="text-[3.5px] uppercase tracking-[0.32em] mt-1" style={{color:p}}>{brand.name}</div></div></div><div className="row-span-2 rounded-2xl" style={{backgroundColor:p}} /><div className="rounded-2xl bg-[#0F1216]" /></div></C>),

    // Glassmorphism (10)
    (<C accent="#fff"><div className="absolute inset-0" style={{background:`linear-gradient(135deg, ${p}, ${s})`}} /><div className="absolute inset-[14%] rounded-2xl backdrop-blur-md bg-white/30 border border-white/50 flex items-center justify-center"><span className="text-white text-[14px] font-light">Hi.</span></div></C>),
    (<C accent="#fff"><div className="absolute inset-0 bg-[#0F1216]" /><div className="absolute inset-0" style={{background:`radial-gradient(80% 60% at 30% 30%, ${p} 0%, transparent 70%)`}} /><div className="absolute inset-[12%] rounded-3xl backdrop-blur-md bg-white/10 border border-white/20 flex items-center justify-center"><span className="text-white text-[10px] font-light">Hello, Jane.</span></div></C>),
    (<C><div className="absolute inset-0" style={{background:`linear-gradient(180deg, ${p} 0%, ${p}99 100%)`}} /><div className="absolute inset-[14%] rounded-md backdrop-blur-lg bg-white/40 border border-white/60 flex items-center justify-center"><div className="text-center text-gray-900"><div className="text-[10px] font-medium">Hi.</div></div></div></C>),
    (<C><div className="absolute inset-0 grid grid-cols-2"><div style={{backgroundColor:p}} /><div style={{backgroundColor:s}} /></div><div className="absolute inset-[14%] rounded-md backdrop-blur-2xl bg-white/30 border border-white/50 flex items-center justify-center"><span className="text-white text-[10px] font-bold">Hello.</span></div></C>),
    (<C><div className="absolute inset-0" style={{background:`conic-gradient(from 0deg, ${p}, ${s}, ${p})`}} /><div className="absolute inset-[14%] rounded-2xl backdrop-blur-3xl bg-white/40 border border-white/60 flex items-center justify-center"><div className="text-[10px] font-light">Hi, Jane.</div></div></C>),
    (<C accent={p}><div className="absolute inset-0 bg-[#FAF6EE]" /><div className="absolute -left-[10%] top-[10%] w-[60%] aspect-square rounded-full" style={{background:`radial-gradient(circle, ${p}, transparent 70%)`}} /><div className="absolute inset-[14%] rounded-md backdrop-blur-md bg-white/50 border border-white/70 flex items-center justify-center"><div className="text-[10px] font-light">A note.</div></div></C>),
    (<C accent="#fff"><div className="absolute inset-0 bg-[#1F1F1F]" /><div className="absolute inset-0" style={{background:`radial-gradient(40% 80% at 30% 50%, ${p}AA 0%, transparent 100%)`}} /><div className="absolute inset-[14%] rounded-md backdrop-blur-md bg-white/5 border border-white/15 flex items-center justify-center"><span className="text-white text-[10px] font-light">— hi —</span></div></C>),
    (<C><div className="absolute inset-0" style={{background:`linear-gradient(180deg, ${p}, ${p}AA, transparent)`,backgroundColor:'#FBF8EE'}} /><div className="absolute inset-[14%] rounded-md backdrop-blur-lg bg-white/40 border border-white/70 flex items-center justify-center"><span className="text-[10px] font-medium">Hello,</span></div></C>),
    (<C><div className="absolute inset-0 bg-white" /><div className="absolute inset-x-[20%] top-[20%] aspect-square rounded-full" style={{background:`radial-gradient(circle, ${p}, transparent 70%)`}} /><div className="absolute inset-[14%] rounded-2xl backdrop-blur-md bg-white/40 border border-white/70 flex items-center justify-center"><span className="text-[10px] font-medium">A note.</span></div></C>),
    (<C accent="#fff"><div className="absolute inset-0 bg-[#0F1216]" /><div className="absolute inset-0" style={{background:`linear-gradient(45deg, transparent 0%, ${p}55 50%, transparent 100%)`}} /><div className="absolute inset-[14%] rounded-2xl backdrop-blur-xl bg-white/10 border border-white/20 flex items-center justify-center"><span className="text-white text-[10px] font-light">Hi, Jane.</span></div></C>),

    // Gradient mesh (10)
    (<C><div className="absolute inset-0" style={{background:`radial-gradient(120% 80% at 20% 30%, ${p} 0%, transparent 60%), radial-gradient(120% 80% at 80% 70%, ${s} 0%, transparent 60%), #FBF8EE`}} /><div className="absolute inset-0 flex items-center justify-center"><div className="text-[14px] font-light">Hi.</div></div></C>),
    (<C accent="#fff"><div className="absolute inset-0" style={{background:`linear-gradient(135deg, ${p}, ${s})`}} /><div className="absolute inset-x-[10%] bottom-[12%]"><div className="text-white text-[14px] font-light">Hello,</div></div></C>),
    (<C accent="#fff"><div className="absolute inset-0" style={{background:`conic-gradient(from 0deg at 30% 70%, ${p}, ${s}, ${p})`}} /><div className="absolute inset-x-[10%] top-[14%]"><div className="text-white text-[10px] font-bold">A small note.</div></div></C>),
    (<C><div className="absolute inset-0 flex"><div className="w-1/2" style={{background:`linear-gradient(180deg, ${p}, ${s})`}} /><div className="w-1/2 bg-white flex items-center px-2"><span className="text-[10px] font-bold">Hello.</span></div></div></C>),
    (<C accent="#fff"><div className="absolute inset-0" style={{background:`linear-gradient(180deg, ${s}, ${p})`}} /><div className="absolute inset-0 flex items-center justify-center"><div className="text-white text-[14px] font-light">Hi.</div></div></C>),
    (<C accent="#fff"><div className="absolute inset-0 bg-[#0F1216]" /><div className="absolute -inset-[10%]" style={{background:`radial-gradient(circle at 30% 30%, ${p}, transparent 50%), radial-gradient(circle at 70% 70%, ${s}, transparent 50%)`,opacity:0.7}} /><div className="absolute inset-x-[10%] bottom-[14%]"><div className="text-white text-[10px] font-light">A note.</div></div></C>),
    (<C><div className="absolute inset-0" style={{background:`linear-gradient(105deg, ${p} 0%, ${p} 50%, white 50%, white 100%)`}} /><div className="absolute right-[10%] top-1/2 -translate-y-1/2"><span className="text-[10px] font-bold">Hi.</span></div></C>),
    (<C accent="#fff"><div className="absolute inset-0 bg-white" /><div className="absolute inset-[12%] rounded-2xl flex items-center justify-center" style={{background:`linear-gradient(135deg, ${p} 0%, ${s} 100%)`}}><div className="text-white text-[12px] font-bold">Hello.</div></div></C>),
    (<C><div className="absolute inset-0" style={{background:`linear-gradient(45deg, ${p}, transparent), linear-gradient(135deg, ${s}, transparent), #FBF8EE`}} /><div className="absolute inset-x-[10%] bottom-[14%]"><span className="text-[10px] font-light">Hello.</span></div></C>),
    (<C accent="#fff"><div className="absolute inset-0" style={{background:`linear-gradient(225deg, ${p}, ${s}, ${p})`}} /><div className="absolute inset-[14%] rounded-md bg-black/30 backdrop-blur-sm border border-white/20 flex items-center justify-center"><span className="text-white text-[10px] font-light">Hi.</span></div></C>),

    // Pentagram (10)
    (<C><div className="absolute inset-x-[10%] top-[12%] grid grid-cols-12 gap-[1px]">{Array.from({length:12}).map((_,i)=><div key={i} className="h-[3px]" style={{backgroundColor:i<7?p:'#E5E0D2'}} />)}</div><div className="absolute inset-x-[10%] top-1/2 -translate-y-1/2"><span className="text-[14px] font-bold">Hi.</span></div></C>),
    (<C><div className="absolute inset-x-[10%] top-[14%] grid grid-cols-8 gap-[1px]">{Array.from({length:8}).map((_,i)=><div key={i} className="aspect-square" style={{backgroundColor:[1,3,5].includes(i)?p:[0,2,4,6].includes(i)?'#0F1216':'#FBF8EE'}} />)}</div><div className="absolute inset-x-[10%] bottom-[14%]"><span className="text-[10px] font-bold">Hello.</span></div></C>),
    (<C><div className="absolute left-0 top-0 bottom-0 w-[6%]" style={{backgroundColor:p}} /><div className="absolute left-[6%] top-0 bottom-0 w-[6%] bg-[#0F1216]" /><div className="absolute left-[16%] top-1/2 -translate-y-1/2"><span className="text-[14px] font-bold">Hi.</span></div></C>),
    (<C><div className="absolute inset-x-[10%] top-[14%] flex gap-1">{Array.from({length:5}).map((_,i)=><div key={i} className="h-[10px] flex-1" style={{backgroundColor:i===2?p:i%2===0?'#0F1216':'#FBF8EE'}} />)}</div><div className="absolute inset-x-[10%] bottom-[14%]"><span className="text-[10px] font-bold">Hello.</span></div></C>),
    (<C><div className="absolute left-[10%] top-1/2 -translate-y-1/2 grid grid-cols-3 gap-1">{Array.from({length:3}).map((_,i)=><div key={i} className="w-[10px] aspect-square rounded-full" style={{backgroundColor:i===1?p:`${p}33`}} />)}</div><div className="absolute right-[10%] top-1/2 -translate-y-1/2"><span className="text-[10px] font-bold">Hi.</span></div></C>),
    (<C><div className="absolute inset-x-[10%] top-[12%] flex flex-wrap gap-1">{Array.from({length:18}).map((_,i)=><div key={i} className="w-[5px] h-[5px] rounded-full" style={{backgroundColor:i%4===0?p:i%4===1?'#0F1216':'#E5E0D2'}} />)}</div><div className="absolute inset-x-[10%] bottom-[14%]"><span className="text-[10px] font-bold">Hi.</span></div></C>),
    (<C><div className="absolute inset-x-[10%] top-[14%] h-[16px] grid grid-cols-12">{Array.from({length:12}).map((_,i)=>(<div key={i} className="border-r border-[#E5E0D2] last:border-r-0 flex items-end p-[1px]"><div className="w-full" style={{height:`${30+(i*7)%60}%`,backgroundColor:i===5?p:'#0F1216'}} /></div>))}</div><div className="absolute inset-x-[10%] bottom-[14%]"><span className="text-[10px] font-bold">Hi.</span></div></C>),
    (<C><div className="absolute inset-x-[10%] top-[14%] grid grid-cols-2 gap-1"><div className="aspect-[3/1]" style={{backgroundColor:p}} /><div className="aspect-[3/1] bg-[#0F1216]" /></div><div className="absolute inset-x-[10%] bottom-[14%]"><span className="text-[10px] font-bold">Hello.</span></div></C>),
    (<C><div className="absolute inset-x-[10%] top-[12%] grid grid-cols-12 grid-rows-3 gap-[2px]">{Array.from({length:36}).map((_,i)=><div key={i} className="h-[3px]" style={{backgroundColor:[2,5,9,11,15,16,18,22,25,28,29].includes(i)?p:'transparent'}} />)}</div><div className="absolute inset-x-[10%] bottom-[14%]"><span className="text-[10px] font-bold">Hi.</span></div></C>),
    (<C><div className="absolute inset-x-[10%] top-[14%] flex items-center gap-1.5"><div className="w-[20px] h-[20px] rounded-full flex items-center justify-center text-white text-[10px] font-bold" style={{backgroundColor:p}}>{init}</div><div className="text-[3.5px] uppercase tracking-[0.32em] font-bold">{brand.name}</div></div><div className="absolute inset-x-[10%] bottom-[14%]"><span className="text-[10px] font-bold">Hi.</span></div></C>),

    // Editorial mixed creative (15)
    (<C><div className="absolute left-[10%] top-[12%] text-[24px] font-serif italic font-black leading-none" style={{color:p}}>"</div><div className="absolute right-[10%] bottom-[14%] text-right"><div className="text-[7px] font-serif italic font-bold">— Jane</div></div></C>),
    (<C><div className="absolute right-0 top-0 w-[20%] h-full" style={{backgroundColor:p}} /><div className="absolute left-[10%] top-1/2 -translate-y-1/2"><div className="text-[3.5px] uppercase tracking-[0.32em] text-gray-400">{brand.name}</div><div className="text-[10px] font-serif font-bold mt-0.5">Hello.</div></div></C>),
    (<C><div className="absolute inset-0 grid grid-rows-2"><div className="bg-[#FBF8EE] p-2 flex flex-col justify-end"><div className="text-[10px] font-serif italic" style={{color:p}}>Hi,</div></div><div className="bg-white p-2"><div className="text-[5px] uppercase tracking-[0.32em] text-gray-500">— from {brand.name}</div></div></div></C>),
    (<C><div className="absolute left-[5%] top-[10%] font-serif font-black leading-none" style={{color:`${p}11`,fontSize:'60px'}}>14</div><div className="absolute right-[10%] bottom-[14%] text-right"><div className="text-[10px] font-bold">Hello.</div></div></C>),
    (<C><div className="absolute inset-x-[10%] top-[16%] flex justify-between items-baseline"><div className="text-[10px] font-serif font-bold">A Note</div><div className="text-[3.5px] uppercase tracking-[0.32em] text-gray-400">№ 014</div></div><div className="absolute left-[10%] right-[10%] top-[40%] h-[1px]" style={{backgroundColor:p}} /><div className="absolute inset-x-[10%] bottom-[14%] text-[7px] font-bold">Hello, Jane.</div></C>),
    (<C><div className="absolute inset-x-[10%] top-1/2 -translate-y-1/2 grid grid-cols-3 gap-2 text-[3.5px]"><div><div className="uppercase tracking-[0.32em] text-gray-400">no.</div><div className="text-[10px] font-bold">14</div></div><div className="text-center"><div className="uppercase tracking-[0.32em] text-gray-400">to</div><div className="text-[5px] font-bold">Jane</div></div><div className="text-right"><div className="uppercase tracking-[0.32em] text-gray-400">by</div><div className="text-[5px] font-bold" style={{color:p}}>{brand.name}</div></div></div></C>),
    (<C><div className="absolute inset-x-[10%] top-[14%]"><div className="border-y-2 py-1 border-black"><div className="text-center text-[5px] uppercase tracking-[0.32em] font-bold">{brand.name} JOURNAL</div></div></div><div className="absolute inset-x-[10%] bottom-[14%] text-center"><div className="text-[10px] font-bold">Hello.</div></div></C>),
    (<C accent={p}><div className="absolute inset-0 bg-[#FBF8EE]" /><div className="absolute left-[10%] top-[14%]"><BrandLogo brand={brand} size="xs" /></div><div className="absolute left-[10%] bottom-[14%]"><div className="text-[10px] font-serif italic font-bold" style={{color:p}}>A note.</div></div></C>),
    (<C><div className="absolute inset-0 flex items-center justify-center"><div className="text-center"><div className="text-[12px] font-serif italic font-light text-gray-900">{brand.name}</div><div className="h-[1px] mx-auto w-[40%] my-1" style={{backgroundColor:p}} /><div className="text-[5px] uppercase tracking-[0.4em] text-gray-500">— a card —</div></div></div></C>),
    (<C><div className="absolute inset-x-[10%] top-1/2 -translate-y-1/2 flex items-center gap-1"><div className="w-[5px] h-[5px] rounded-full bg-[#7BC56A]" /><span className="text-[3.5px] uppercase tracking-[0.32em] text-gray-700">live · {brand.name.toLowerCase()}</span></div></C>),
    (<C><div className="absolute inset-x-[10%] top-[14%]"><div className="text-[3.5px] uppercase tracking-[0.32em] text-gray-400">— from the desk of —</div><div className="text-[10px] font-serif italic font-bold mt-1" style={{color:p}}>Jane Smith</div></div></C>),
    (<C accent="#fff"><div className="absolute inset-0 bg-[#0F1216]" /><div className="absolute inset-x-[10%] top-[14%] flex items-center gap-1"><div className="w-[5px] h-[5px] rounded-full" style={{backgroundColor:p}} /><span className="text-[3.5px] uppercase tracking-[0.32em] text-white opacity-90">{brand.name}</span></div><div className="absolute inset-x-[10%] bottom-[14%] text-white"><div className="text-[10px] font-light">Hi, Jane.</div></div></C>),
    (<C><div className="absolute inset-x-[10%] top-[14%] grid grid-cols-12"><div className="col-span-1 text-[3.5px] uppercase tracking-[0.32em] text-gray-400 self-end">A.</div><div className="col-span-11 text-[3.5px] uppercase tracking-[0.32em] font-bold border-b border-black pb-0.5">{brand.name} · CARD A · 014</div></div><div className="absolute inset-x-[10%] bottom-[14%]"><div className="text-[10px] font-bold">Hello.</div></div></C>),
    (<C><div className="absolute inset-x-[10%] top-1/2 -translate-y-1/2 flex items-end gap-2"><div className="text-[24px] font-serif font-black leading-none" style={{color:p}}>{init}.</div><div><div className="text-[3.5px] uppercase tracking-[0.32em] text-gray-400">a note from</div><div className="text-[5px] font-bold">{brand.name}</div></div></div></C>),
    (<C><div className="absolute inset-x-[10%] top-[14%] grid grid-cols-2 gap-2 text-[3.5px] uppercase tracking-[0.32em]"><div><div className="text-gray-400">{brand.name}</div><div className="text-gray-700">— a small studio</div></div><div className="text-right"><div className="text-gray-400">no. 014</div><div className="text-gray-700">— spring 2026</div></div></div></C>),
  ];

  return designs[templateIndex] ?? designs[0];
}

export const NOTECARD_EXTENDED_2 = Array.from({ length: 100 }, (_, i) => ({
  idSuffix: `ext-${i + 31}`,
  name: `Wave 2 · ${String(i + 1).padStart(2, '0')}`,
  category: 'Modern',
}));
