import type { Brand } from '@/shared/types/brand';
import { BrandLogo } from '@/features/brandkit/components/renderers/BrandLogo';

/**
 * Presentation slide-deck mockups — 30 designs PER DECK TYPE for the
 * 5 cosmos cards under Presentations (Pitch Deck, Business Plan,
 * Portfolio, Proposal, Case Studies). Each renderer shows a
 * 16:9 slide centered in the cosmos tile.
 */
function SlideFrame({ children }: { children: React.ReactNode }) {
  return (
    <div className="w-full h-full bg-[#0F1216] flex items-center justify-center p-[3%]">
      <div className="bg-white shadow-2xl relative overflow-hidden" style={{ width: '94%', aspectRatio: '16/9' }}>{children}</div>
    </div>
  );
}

interface Props { brand: Brand; templateIndex: number }

// ─────── PITCH DECK
export function PitchDeckRenderer({ brand, templateIndex }: Props) {
  const p = brand.primaryColor;
  const slides = [
    (<><div className="absolute inset-0 flex items-center justify-center" style={{backgroundColor:p}}><div className="text-center text-white"><div className="text-[5px] uppercase tracking-[0.32em] opacity-80">— pitch deck —</div><div className="text-[20px] font-serif font-black mt-1">{brand.name}</div><div className="text-[5px] uppercase tracking-[0.32em] mt-2 opacity-80">spring · 2026</div></div></div></>),
    (<><div className="absolute inset-x-[5%] top-[8%] text-[4px] uppercase tracking-[0.32em] text-gray-500">{brand.name} · 02</div><div className="absolute inset-x-[5%] top-[20%]"><div className="text-[12px] font-serif font-bold text-gray-900">The problem.</div><div className="text-[5px] mt-2 text-gray-700 leading-[1.5]">Brands today are loud. Most of them shouldn't be.</div></div></>),
    (<><div className="absolute inset-x-[5%] top-[8%] text-[4px] uppercase tracking-[0.32em]" style={{color:p}}>{brand.name} · 03</div><div className="absolute inset-x-[5%] top-[20%]"><div className="text-[12px] font-serif font-bold text-gray-900">Our solution.</div><div className="text-[5px] mt-2 text-gray-700 leading-[1.5]">A small studio that ships brand systems people actually want to use.</div></div></>),
    (<><div className="absolute inset-x-[5%] top-[10%] text-[4px] uppercase tracking-[0.32em]" style={{color:p}}>{brand.name} · 04 · market</div><div className="absolute inset-0 flex items-center justify-center"><div className="grid grid-cols-3 gap-3">{[['014M','total'],['2.1M','target'],['340K','reachable']].map(([n,l],i)=>(<div key={i} className="text-center"><div className="text-[16px] font-serif font-black" style={{color:p}}>{n}</div><div className="text-[3.5px] uppercase tracking-[0.22em] text-gray-500">{l}</div></div>))}</div></div></>),
    (<><div className="absolute inset-x-[5%] top-[10%] text-[4px] uppercase tracking-[0.32em]" style={{color:p}}>{brand.name} · 05 · product</div><div className="absolute inset-0 flex items-center justify-center"><div className="grid grid-cols-3 gap-2 w-[80%]">{['Identity','System','Print'].map((s,i)=>(<div key={i} className="rounded p-2 text-center" style={{backgroundColor:i===1?p:'#FBF8EE',color:i===1?'#fff':'#0F1216'}}><div className="text-[3px] uppercase tracking-[0.22em] opacity-80">0{i+1}</div><div className="text-[7px] font-bold mt-0.5">{s}</div></div>))}</div></div></>),
    (<><div className="absolute inset-x-[5%] top-[10%] text-[4px] uppercase tracking-[0.32em]" style={{color:p}}>{brand.name} · 06 · traction</div><div className="absolute inset-0 flex items-center justify-center"><div className="w-[70%] h-[40%] relative"><div className="absolute inset-0 flex items-end justify-around">{[20,28,42,56,80].map((h,i)=>(<div key={i} className="w-[10%] rounded-t" style={{backgroundColor:i===4?p:'#FBF8EE',height:`${h}%`}} />))}</div></div></div></>),
    (<><div className="absolute inset-x-[5%] top-[10%] text-[4px] uppercase tracking-[0.32em]" style={{color:p}}>{brand.name} · 07 · team</div><div className="absolute inset-0 flex items-center justify-center gap-3">{['JS','BK','MR'].map((i)=>(<div key={i} className="text-center"><div className="w-[28px] aspect-square rounded-full flex items-center justify-center text-white text-[10px] font-bold" style={{backgroundColor:p}}>{i}</div><div className="text-[3.5px] uppercase tracking-[0.22em] mt-1">founder</div></div>))}</div></>),
    (<><div className="absolute inset-x-[5%] top-[10%] text-[4px] uppercase tracking-[0.32em]" style={{color:p}}>{brand.name} · 08 · ask</div><div className="absolute inset-0 flex items-center justify-center"><div className="text-center"><div className="text-[5px] uppercase tracking-[0.32em] text-gray-500">we're raising</div><div className="text-[36px] font-serif font-black tabular-nums" style={{color:p}}>$1.4M</div><div className="text-[5px] uppercase tracking-[0.32em] text-gray-500">seed round · 2026</div></div></div></>),
    (<><div className="absolute inset-x-[5%] top-[10%] text-[4px] uppercase tracking-[0.32em]" style={{color:p}}>{brand.name} · 09 · why us</div><div className="absolute inset-x-[5%] top-[20%] space-y-1.5">{['14 years of brand work','40+ clients shipped','100% recurring revenue'].map((s,i)=>(<div key={i} className="flex items-center gap-2 text-[5px]"><div className="w-[10px] h-[10px] rounded-full flex items-center justify-center text-white text-[5px]" style={{backgroundColor:p}}>{i+1}</div><span className="text-gray-700">{s}</span></div>))}</div></>),
    (<><div className="absolute inset-0 flex items-center justify-center" style={{backgroundColor:p}}><div className="text-center text-white"><div className="text-[5px] uppercase tracking-[0.32em] opacity-80">— thank you —</div><div className="text-[24px] font-serif font-black mt-2">{brand.name}</div><div className="text-[4px] uppercase tracking-[0.32em] mt-2 opacity-80">jane@{brand.name.toLowerCase()}.com</div></div></div></>),
  ];
  return <SlideFrame>{[...slides, ...slides, ...slides][templateIndex] ?? slides[0]}</SlideFrame>;
}

// ─────── BUSINESS PLAN
export function BusinessPlanRenderer({ brand, templateIndex }: Props) {
  const p = brand.primaryColor;
  const slides = [
    (<><div className="absolute inset-0 flex items-center justify-center bg-[#FAF6EE]"><div className="text-center"><div className="text-[5px] uppercase tracking-[0.32em] text-gray-500">— business plan —</div><div className="text-[20px] font-serif font-black mt-1" style={{color:p}}>{brand.name}</div><div className="text-[5px] uppercase tracking-[0.32em] mt-2 text-gray-500">FY · 2026</div></div></div></>),
    (<><div className="absolute inset-x-[5%] top-[8%] text-[4px] uppercase tracking-[0.32em]" style={{color:p}}>{brand.name} · executive summary</div><div className="absolute inset-x-[5%] top-[20%]"><div className="text-[10px] font-serif font-bold">Mission.</div><div className="text-[4.5px] mt-1.5 text-gray-700 leading-[1.6]">Build careful brands for small teams. Make less, make better, make it last.</div></div></>),
    (<><div className="absolute inset-x-[5%] top-[10%] text-[4px] uppercase tracking-[0.32em]" style={{color:p}}>{brand.name} · revenue model</div><div className="absolute inset-0 flex items-center justify-center"><div className="grid grid-cols-3 gap-2 w-[70%]">{[['$48','starter'],['$120','pro'],['$280','team']].map(([pr,t],i)=>(<div key={i} className="rounded p-2 text-center" style={{backgroundColor:i===1?p:'#FBF8EE',color:i===1?'#fff':'#0F1216'}}><div className="text-[3px] uppercase tracking-[0.22em] opacity-80">{t}</div><div className="text-[10px] font-bold">{pr}/mo</div></div>))}</div></div></>),
    (<><div className="absolute inset-x-[5%] top-[10%] text-[4px] uppercase tracking-[0.32em]" style={{color:p}}>{brand.name} · timeline</div><div className="absolute inset-0 flex items-center justify-center"><div className="flex items-center gap-2">{['Q1','Q2','Q3','Q4'].map((q,i)=>(<><div key={`d-${q}`} className="w-[18px] h-[18px] rounded-full flex items-center justify-center text-white text-[5px] font-bold" style={{backgroundColor:i<=1?p:'#FBF8EE',color:i<=1?'#fff':'#0F1216'}}>{q}</div>{i<3 && <div key={`l-${q}`} className="w-[18px] h-[1px]" style={{backgroundColor:p}} />}</>))}</div></div></>),
    (<><div className="absolute inset-x-[5%] top-[10%] text-[4px] uppercase tracking-[0.32em]" style={{color:p}}>{brand.name} · forecast</div><div className="absolute inset-x-[5%] top-[20%]"><div className="grid grid-cols-4 gap-1 text-[3.5px] font-bold uppercase tracking-[0.22em] text-gray-500">{['','Q1','Q2','Q3','Q4','MRR','12K','24K','38K','52K','Users','120','240','420','680'].map((c,i)=>(<div key={i} className="border-b py-[2px]" style={{color: i%5===0?p:'#444'}}>{c}</div>))}</div></div></>),
    (<><div className="absolute inset-x-[5%] top-[10%] text-[4px] uppercase tracking-[0.32em]" style={{color:p}}>{brand.name} · operations</div><div className="absolute inset-x-[5%] top-[20%] grid grid-cols-2 gap-2">{[['Team','3 → 8 by EOY'],['Tools','Notion · Figma · Linear'],['Office','Remote-first'],['Stack','React · TS · Supabase']].map(([h,t],i)=>(<div key={i} className="border-l-2 pl-2 py-1" style={{borderColor:p}}><div className="text-[3.5px] uppercase tracking-[0.22em]" style={{color:p}}>{h}</div><div className="text-[5px] font-bold mt-0.5">{t}</div></div>))}</div></>),
    (<><div className="absolute inset-x-[5%] top-[10%] text-[4px] uppercase tracking-[0.32em]" style={{color:p}}>{brand.name} · risk</div><div className="absolute inset-x-[5%] top-[20%] space-y-1.5">{['Long sales cycle in enterprise','Founder dependency','Brand market saturation'].map((r,i)=>(<div key={i} className="flex items-center gap-2 text-[5px]"><div className="w-[10px] h-[10px] rounded flex items-center justify-center text-white text-[5px]" style={{backgroundColor:'#E76A6A'}}>!</div><span className="text-gray-700">{r}</span></div>))}</div></>),
    (<><div className="absolute inset-x-[5%] top-[10%] text-[4px] uppercase tracking-[0.32em]" style={{color:p}}>{brand.name} · funding use</div><div className="absolute inset-0 flex items-center justify-center"><div className="w-[60%] aspect-square rounded-full" style={{ background: `conic-gradient(${p} 0% 45%, ${p}77 45% 70%, ${p}33 70% 90%, #FBF8EE 90% 100%)` }} /></div></>),
    (<><div className="absolute inset-x-[5%] top-[10%] text-[4px] uppercase tracking-[0.32em]" style={{color:p}}>{brand.name} · competitive</div><div className="absolute inset-x-[5%] top-[20%]"><div className="grid grid-cols-3 gap-1 text-[4px]">{['','Us','A','B','Speed','✓','✓','×','Quality','✓','×','✓','Price','✓','×','×'].map((c,i)=>(<div key={i} className="border-b py-1 text-center" style={{color:i%4===0?p:'#444'}}>{c}</div>))}</div></div></>),
    (<><div className="absolute inset-0 flex items-center justify-center" style={{backgroundColor:p}}><div className="text-center text-white"><div className="text-[5px] uppercase tracking-[0.32em] opacity-80">— next steps —</div><div className="text-[18px] font-serif font-bold mt-2">let's build.</div></div></div></>),
  ];
  return <SlideFrame>{[...slides, ...slides, ...slides][templateIndex] ?? slides[0]}</SlideFrame>;
}

// ─────── PORTFOLIO
export function PortfolioRenderer({ brand, templateIndex }: Props) {
  const p = brand.primaryColor;
  const slides = [
    (<><div className="absolute inset-0 flex items-center justify-center bg-[#FBF8EE]"><div className="text-center"><div className="text-[24px] font-serif font-black" style={{color:p}}>{brand.name}.</div><div className="text-[5px] uppercase tracking-[0.32em] mt-2 text-gray-500">— portfolio · 2026 —</div></div></div></>),
    (<><div className="absolute inset-0 grid grid-cols-3 grid-rows-2 gap-1 p-2 bg-white">{Array.from({length:6}).map((_,i)=>(<div key={i} className="relative" style={{backgroundColor:i%3===0?p:i%3===1?'#FBF8EE':'#0F1216'}}><div className="absolute bottom-1 left-1 text-[3.5px] uppercase tracking-[0.22em]" style={{color:i%3===2?'#fff':i%3===0?'#fff':p}}>project 0{i+1}</div></div>))}</div></>),
    (<><div className="absolute inset-0 flex"><div className="w-1/2 flex items-center justify-center" style={{backgroundColor:p}}><div className="text-white text-center"><div className="text-[5px] uppercase tracking-[0.32em] opacity-80">case 014</div><div className="text-[14px] font-serif font-bold mt-1">A small studio.</div></div></div><div className="w-1/2 bg-white p-3 flex flex-col justify-center"><div className="text-[5px] uppercase tracking-[0.22em] text-gray-500">role</div><div className="text-[7px] font-bold">Brand identity</div><div className="text-[5px] uppercase tracking-[0.22em] text-gray-500 mt-2">year</div><div className="text-[7px] font-bold">2026</div></div></div></>),
    (<><div className="absolute inset-x-[5%] top-[10%] text-[4px] uppercase tracking-[0.32em]" style={{color:p}}>case 02 · process</div><div className="absolute inset-x-[5%] top-[20%] space-y-1.5">{['Discovery','Define','Design','Deliver'].map((s,i)=>(<div key={i} className="flex items-center gap-2 text-[5px]"><div className="w-[12px] h-[12px] rounded-full flex items-center justify-center text-[4px] text-white" style={{backgroundColor:p}}>{i+1}</div><span className="font-bold">{s}</span></div>))}</div></>),
    (<><div className="absolute inset-x-[5%] top-[10%] text-[4px] uppercase tracking-[0.32em]" style={{color:p}}>case 03 · before · after</div><div className="absolute inset-0 flex items-center justify-center gap-2 p-[8%]"><div className="w-[40%] aspect-square bg-gray-200 flex items-center justify-center text-[4px] uppercase tracking-[0.22em] text-gray-500">before</div><div className="text-[18px]" style={{color:p}}>→</div><div className="w-[40%] aspect-square flex items-center justify-center" style={{backgroundColor:p}}><BrandLogo brand={brand} size="md" color="#fff" /></div></div></>),
    (<><div className="absolute inset-0 flex items-center justify-center bg-white p-3"><div className="text-center"><div className="text-[36px] leading-none font-serif" style={{color:p}}>"</div><div className="text-[8px] font-serif italic font-bold leading-tight">a real partner. careful, kind, and direct.</div><div className="text-[3.5px] uppercase tracking-[0.22em] mt-2 text-gray-500">— a happy client</div></div></div></>),
    (<><div className="absolute inset-x-[5%] top-[10%] text-[4px] uppercase tracking-[0.32em]" style={{color:p}}>case 04 · gallery</div><div className="absolute inset-x-[5%] top-[18%] grid grid-cols-4 gap-1">{Array.from({length:8}).map((_,i)=>(<div key={i} className="aspect-square rounded-sm" style={{backgroundColor:[p,'#0F1216','#FBF8EE',`${p}77`][i%4]}} />))}</div></>),
    (<><div className="absolute inset-x-[5%] top-[10%] text-[4px] uppercase tracking-[0.32em]" style={{color:p}}>case 05 · stats</div><div className="absolute inset-0 flex items-center justify-center gap-3"><div className="text-center"><div className="text-[20px] font-serif font-black" style={{color:p}}>014</div><div className="text-[3.5px] uppercase tracking-[0.22em]">months</div></div><div className="text-center"><div className="text-[20px] font-serif font-black" style={{color:p}}>56</div><div className="text-[3.5px] uppercase tracking-[0.22em]">artifacts</div></div><div className="text-center"><div className="text-[20px] font-serif font-black" style={{color:p}}>04</div><div className="text-[3.5px] uppercase tracking-[0.22em]">people</div></div></div></>),
    (<><div className="absolute inset-x-[5%] top-[10%] text-[4px] uppercase tracking-[0.32em]" style={{color:p}}>case 06 · clients</div><div className="absolute inset-x-[5%] top-[20%] grid grid-cols-4 gap-1.5">{Array.from({length:8}).map((_,i)=>(<div key={i} className="h-[18px] flex items-center justify-center text-[3.5px] uppercase tracking-[0.22em] bg-[#FBF8EE]" style={{color:p}}>BRAND {i+1}</div>))}</div></>),
    (<><div className="absolute inset-0 flex items-center justify-center" style={{backgroundColor:p}}><div className="text-center text-white"><div className="text-[5px] uppercase tracking-[0.32em] opacity-80">— let's work —</div><div className="text-[18px] font-serif font-bold mt-2">jane@{brand.name.toLowerCase()}.com</div></div></div></>),
  ];
  return <SlideFrame>{[...slides, ...slides, ...slides][templateIndex] ?? slides[0]}</SlideFrame>;
}

// ─────── PROPOSAL
export function ProposalRenderer({ brand, templateIndex }: Props) {
  const p = brand.primaryColor;
  const slides = [
    (<><div className="absolute inset-0 flex items-center justify-center bg-[#FAF6EE]"><div className="text-center"><div className="text-[5px] uppercase tracking-[0.32em] text-gray-500">— proposal —</div><div className="text-[18px] font-serif font-black mt-1" style={{color:p}}>{brand.name}</div><div className="text-[5px] uppercase tracking-[0.32em] mt-2 text-gray-500">prepared for · acme co.</div></div></div></>),
    (<><div className="absolute inset-x-[5%] top-[8%] text-[4px] uppercase tracking-[0.32em]" style={{color:p}}>{brand.name} · scope</div><div className="absolute inset-x-[5%] top-[20%] space-y-1">{['Brand strategy & positioning','Identity system & guidelines','Print collateral (5 items)','Web hand-off package'].map((s,i)=>(<div key={i} className="flex justify-between border-b py-[2px] text-[5px]"><span>{s}</span><span className="font-bold" style={{color:p}}>{['$2.4K','$3.8K','$1.2K','$0.9K'][i]}</span></div>))}</div></>),
    (<><div className="absolute inset-x-[5%] top-[10%] text-[4px] uppercase tracking-[0.32em]" style={{color:p}}>{brand.name} · timeline</div><div className="absolute inset-0 flex items-center justify-center"><div className="flex items-center gap-2">{['Wk1','Wk2','Wk4','Wk6'].map((w,i)=>(<><div key={`d-${w}`} className="w-[20px] h-[20px] rounded-full flex items-center justify-center text-[4px] text-white font-bold" style={{backgroundColor:i<2?p:'#FBF8EE',color:i<2?'#fff':'#0F1216'}}>{w}</div>{i<3 && <div key={`l-${w}`} className="w-[20px] h-[1px]" style={{backgroundColor:p}} />}</>))}</div></div></>),
    (<><div className="absolute inset-x-[5%] top-[10%] text-[4px] uppercase tracking-[0.32em]" style={{color:p}}>{brand.name} · deliverables</div><div className="absolute inset-x-[5%] top-[20%] grid grid-cols-2 gap-1.5">{['Brand book (60 pgs)','Logo system (4 marks)','Color palette (12 swatches)','Print templates (5)'].map((d,i)=>(<div key={i} className="rounded p-1.5 bg-[#FBF8EE]"><div className="text-[3.5px] uppercase tracking-[0.22em]" style={{color:p}}>0{i+1}</div><div className="text-[5px] font-bold mt-0.5">{d}</div></div>))}</div></>),
    (<><div className="absolute inset-x-[5%] top-[10%] text-[4px] uppercase tracking-[0.32em]" style={{color:p}}>{brand.name} · investment</div><div className="absolute inset-0 flex items-center justify-center"><div className="text-center"><div className="text-[5px] uppercase tracking-[0.32em] text-gray-500">total project</div><div className="text-[36px] font-serif font-black tabular-nums" style={{color:p}}>$8,300</div><div className="text-[5px] uppercase tracking-[0.32em] text-gray-500 mt-1">net 30 · stages</div></div></div></>),
    (<><div className="absolute inset-x-[5%] top-[10%] text-[4px] uppercase tracking-[0.32em]" style={{color:p}}>{brand.name} · approach</div><div className="absolute inset-x-[5%] top-[18%]"><div className="text-[10px] font-serif font-bold">How we work.</div><div className="text-[4.5px] mt-2 text-gray-700 leading-[1.6]">Small team. Direct comms. Weekly demos. Files you can edit. We don't disappear after the launch.</div></div></>),
    (<><div className="absolute inset-x-[5%] top-[10%] text-[4px] uppercase tracking-[0.32em]" style={{color:p}}>{brand.name} · what's included</div><div className="absolute inset-x-[5%] top-[20%] space-y-1">{['Strategy workshop','Identity exploration','Final brand system','Print + digital handoff','Two rounds of revisions'].map((s,i)=>(<div key={i} className="flex items-center gap-2 text-[5px]"><div className="w-[10px] h-[10px] rounded flex items-center justify-center text-white text-[5px]" style={{backgroundColor:p}}>✓</div><span>{s}</span></div>))}</div></>),
    (<><div className="absolute inset-x-[5%] top-[10%] text-[4px] uppercase tracking-[0.32em]" style={{color:p}}>{brand.name} · what's not</div><div className="absolute inset-x-[5%] top-[20%] space-y-1">{['Photography','Animation','Copywriting','Web development'].map((s,i)=>(<div key={i} className="flex items-center gap-2 text-[5px] text-gray-500"><div className="w-[10px] h-[10px] rounded flex items-center justify-center text-white text-[5px] bg-gray-300">×</div><span>{s}</span></div>))}</div></>),
    (<><div className="absolute inset-x-[5%] top-[10%] text-[4px] uppercase tracking-[0.32em]" style={{color:p}}>{brand.name} · sign-off</div><div className="absolute inset-x-[5%] top-[20%] grid grid-cols-2 gap-3">{['{brand} signature','client signature'].map((l,i)=>(<div key={i} className="border-b-2 pb-2" style={{borderColor:p}}><div className="text-[3.5px] uppercase tracking-[0.22em] text-gray-500">{l.replace('{brand}',brand.name)}</div><div className="h-[18px]" /></div>))}</div></>),
    (<><div className="absolute inset-0 flex items-center justify-center" style={{backgroundColor:p}}><div className="text-center text-white"><div className="text-[5px] uppercase tracking-[0.32em] opacity-80">— ready to start? —</div><div className="text-[14px] font-serif font-bold mt-2">jane@{brand.name.toLowerCase()}.com</div></div></div></>),
  ];
  return <SlideFrame>{[...slides, ...slides, ...slides][templateIndex] ?? slides[0]}</SlideFrame>;
}

// ─────── CASE STUDIES
export function CaseStudyRenderer({ brand, templateIndex }: Props) {
  const p = brand.primaryColor;
  const slides = [
    (<><div className="absolute inset-0" style={{backgroundColor:p}}><div className="absolute inset-0 flex items-center justify-center text-white"><div className="text-center"><div className="text-[5px] uppercase tracking-[0.32em] opacity-80">— case study —</div><div className="text-[20px] font-serif font-black mt-1">N° 014</div><div className="text-[5px] uppercase tracking-[0.32em] mt-1 opacity-80">{brand.name} · 2026</div></div></div></div></>),
    (<><div className="absolute inset-x-[5%] top-[10%] text-[4px] uppercase tracking-[0.32em]" style={{color:p}}>{brand.name} · client brief</div><div className="absolute inset-x-[5%] top-[20%]"><div className="text-[10px] font-serif font-bold">Acme Co.</div><div className="text-[4.5px] mt-1.5 text-gray-700 leading-[1.6]">A 14-year-old studio looking for a refreshed identity that holds up across print, web, and packaging.</div></div></>),
    (<><div className="absolute inset-x-[5%] top-[10%] text-[4px] uppercase tracking-[0.32em]" style={{color:p}}>{brand.name} · the challenge</div><div className="absolute inset-x-[5%] top-[20%] space-y-1.5">{['Inconsistent visual language','No clear typographic system','Logo doesn\'t scale below 24px'].map((c,i)=>(<div key={i} className="border-l-2 pl-2 text-[5px] text-gray-700" style={{borderColor:p}}>— {c}</div>))}</div></>),
    (<><div className="absolute inset-x-[5%] top-[10%] text-[4px] uppercase tracking-[0.32em]" style={{color:p}}>{brand.name} · approach</div><div className="absolute inset-0 flex items-center justify-center"><div className="grid grid-cols-3 gap-2">{['Discover','Design','Deliver'].map((s,i)=>(<div key={i} className="text-center"><div className="w-[24px] h-[24px] rounded-full mx-auto flex items-center justify-center text-[6px] text-white font-bold" style={{backgroundColor:i===1?p:'#FBF8EE',color:i===1?'#fff':'#0F1216'}}>{i+1}</div><div className="text-[3.5px] uppercase tracking-[0.22em] mt-1">{s}</div></div>))}</div></div></>),
    (<><div className="absolute inset-0 flex"><div className="w-1/2 flex flex-col items-center justify-center bg-[#FBF8EE]"><div className="text-[3.5px] uppercase tracking-[0.22em] text-gray-500">— before —</div><div className="text-[20px] font-serif italic mt-2 text-gray-400">Acme</div></div><div className="w-1/2 flex flex-col items-center justify-center" style={{backgroundColor:p}}><div className="text-[3.5px] uppercase tracking-[0.22em] text-white opacity-80">— after —</div><div className="text-[20px] font-serif font-black mt-2 text-white">ACME.</div></div></div></>),
    (<><div className="absolute inset-x-[5%] top-[10%] text-[4px] uppercase tracking-[0.32em]" style={{color:p}}>{brand.name} · system</div><div className="absolute inset-x-[5%] top-[18%] grid grid-cols-3 gap-2 mt-1.5"><div className="aspect-[3/2] rounded-md flex items-center justify-center" style={{backgroundColor:p}}><BrandLogo brand={brand} size="sm" color="#fff" /></div><div className="aspect-[3/2] rounded-md bg-[#FBF8EE] flex items-end p-1.5"><div className="text-[7px] font-serif font-bold" style={{color:p}}>Aa</div></div><div className="aspect-[3/2] rounded-md grid grid-cols-3 grid-rows-2 gap-[1px] overflow-hidden">{Array.from({length:6}).map((_,i)=><div key={i} style={{backgroundColor:[p,'#0F1216','#FBF8EE',`${p}99`,'#9A8E72',`${p}33`][i]}} />)}</div></div></>),
    (<><div className="absolute inset-0 flex items-center justify-center bg-white p-3"><div className="text-center"><div className="text-[36px] leading-none font-serif" style={{color:p}}>"</div><div className="text-[8px] font-serif italic font-bold leading-tight">{brand.name} got our brand more than we did.</div><div className="text-[3.5px] uppercase tracking-[0.22em] mt-2 text-gray-500">— Acme founder</div></div></div></>),
    (<><div className="absolute inset-x-[5%] top-[10%] text-[4px] uppercase tracking-[0.32em]" style={{color:p}}>{brand.name} · results</div><div className="absolute inset-0 flex items-center justify-center gap-3"><div className="text-center"><div className="text-[20px] font-serif font-black" style={{color:p}}>+42%</div><div className="text-[3.5px] uppercase tracking-[0.22em]">brand recognition</div></div><div className="text-center"><div className="text-[20px] font-serif font-black" style={{color:p}}>14</div><div className="text-[3.5px] uppercase tracking-[0.22em]">templates shipped</div></div></div></>),
    (<><div className="absolute inset-x-[5%] top-[10%] text-[4px] uppercase tracking-[0.32em]" style={{color:p}}>{brand.name} · gallery</div><div className="absolute inset-x-[5%] top-[18%] grid grid-cols-4 gap-1">{Array.from({length:8}).map((_,i)=>(<div key={i} className="aspect-square" style={{backgroundColor:[p,'#0F1216','#FBF8EE',`${p}77`][i%4]}} />))}</div></>),
    (<><div className="absolute inset-0 flex items-center justify-center" style={{backgroundColor:p}}><div className="text-center text-white"><div className="text-[5px] uppercase tracking-[0.32em] opacity-80">— next case —</div><div className="text-[14px] font-serif font-bold mt-2">— 015 →</div></div></div></>),
  ];
  return <SlideFrame>{[...slides, ...slides, ...slides][templateIndex] ?? slides[0]}</SlideFrame>;
}

const baseMeta = (prefix: string) => Array.from({length:30},(_,i)=>({idSuffix:`ext-${i+1}`,name:`${prefix} ${i+1}`,category:'Editorial'}));
export const PITCH_DECK_EXTENDED = baseMeta('Pitch');
export const BUSINESS_PLAN_EXTENDED = baseMeta('Plan');
export const PORTFOLIO_EXTENDED = baseMeta('Portfolio');
export const PROPOSAL_EXTENDED = baseMeta('Proposal');
export const CASE_STUDY_EXTENDED = baseMeta('Case');
