import type { CSSProperties } from 'react';
import type { Brand } from '@/shared/types/brand';
import {
  hydrateContent,
  type DeliverableContent,
  type ProfileContent,
} from '@/features/brandkit/content/kinds';
import type { TemplateDesignPicks } from '@/features/brandkit/content/schema';
import { Bind } from '@/features/brandkit/content/Bind';
import { logoUrl } from '@/shared/brand/logoUrl';
import { contrastOf, fontStack, logoOn, normalizeHex } from './brandStyle';
import { Frame, groundsFor, mixHex, type Ground, type Grounds } from './socialCommon';

/**
 * Profile icon — 24 designs, 1:1.
 *
 * An avatar is not a picture, it is THREE decisions: which mark goes in
 * the frame, what shape the frame is, and what colour it sits on. So this
 * family is a study rather than a gallery — six layouts across four
 * container shapes, each on a brand ground chosen so the mark can be seen
 * on it. That is also why there are 24 and not 130.
 *
 * What it replaces: 118 designs that were neither. The eighteen of wave 1
 * drew the brand's initial in `font-serif` on `#0F1216` and `#FBF8EE` —
 * Tailwind's typeface and two colours no brand here owns — and eleven of
 * them painted a gradient, which is a ground nothing can be measured
 * against. The hundred of wave 2 were generated by movement (fifteen
 * "Brutalist" on `#FFEB3B`, `#FF3B30` and `#39FF14`, one welded to
 * `Caveat, cursive`), named "Wave 2 · 43", and shipped `est. 2026` and
 * `— a brand —` as if they were facts about the customer.
 *
 * The four fields of the `profile` content, and where each one lands:
 *
 *   glyph     which mark fills the frame — the brand's logo, its icon
 *             mark, or the letters. Every design reads it; none overrides
 *             it, because a control that does nothing on the design you
 *             chose is the failure this wave exists to end.
 *   text      the letters, when the mark is a monogram — or when the
 *             brand owns no artwork that READS on this ground.
 *   tabTitle  the name beside the avatar. An avatar is never seen alone:
 *             it is seen in a row, with the account's name under it.
 *   url       the address that row links to.
 *
 * Ids `ext-1` … `ext-18` render from here directly; `ext-19` … `ext-24`
 * arrive through `SocialProfileExtended2` (the shared dispatch splits the
 * family at 18) and land on `DESIGNS[18…23]`. `ext-25` … `ext-118` are
 * archived. Nothing renumbers.
 */

interface Props {
  brand: Brand;
  templateIndex: number;
  content?: DeliverableContent;
}

/** The content this design paints, whether or not the editor supplied it. */
export function profileContentFor(brand: Brand, content?: DeliverableContent): ProfileContent {
  if (content && content.kind === 'profile') return content;
  return hydrateContent('profile', brand, undefined) as ProfileContent;
}

/* ── The container ────────────────────────────────────────────────── */

/** The four shapes an avatar is actually cut to. */
type Shape = 'circle' | 'squircle' | 'rounded' | 'square';

const RADIUS: Record<Shape, (px: number) => string> = {
  circle: () => '50%',
  squircle: (px) => `${Math.round(px * 0.3)}px`,
  rounded: (px) => `${Math.round(px * 0.16)}px`,
  square: () => '0px',
};

/** Which ground the badge is filled with, named by ROLE not by colour. */
type Fill = 'brand' | 'support' | 'paper' | 'tint' | 'ink' | 'page';

/**
 * The mark, on the badge's own ground.
 *
 * `glyph` is interpreted in exactly one place — here — and the fallback
 * order is a fallback, not a preference: artwork the brand owns is placed
 * only when `logoOn` says it READS on this colour, and the letters are
 * what a brand with no usable variant gets rather than an empty tile.
 * That is also why `text` stays bound on every design, including the ones
 * showing a logo today: the brand that has no logo tomorrow still needs
 * its monogram to be editable.
 */
function Glyph({
  brand,
  content,
  ground,
  size,
  shape,
  picks,
}: {
  brand: Brand;
  content: ProfileContent;
  /** The badge's ground — what the mark is actually drawn on. */
  ground: Ground;
  /** The badge's edge length in the 260px design space. */
  size: number;
  /** A circle's usable width is its inscribed square, not its diameter. */
  shape: Shape;
  picks?: TemplateDesignPicks;
}) {
  const hidden = picks?.showLogo === false;
  const placed = hidden
    ? undefined
    : content.glyph === 'logo'
      ? logoOn(brand, ground.bg)?.url
      : content.glyph === 'custom'
        ? logoUrl(brand, 'iconmark')
        : undefined;

  // A wordmark laid across a circle's full diameter touches the curve at
  // the top and bottom of its own line; the square it really fits inside
  // is narrower. Measured on Raqm's wordmark in `Ring Circle`.
  const inset = shape === 'circle' ? '58%' : '68%';
  const letterSize = Math.round(size * (shape === 'circle' ? 0.38 : 0.42));
  const picked = normalizeHex(picks?.logoColor);
  const letterInk =
    picked && contrastOf(picked, ground.bg) >= (letterSize >= 24 ? 3 : 4.5) ? picked : ground.ink;

  return (
    <div
      data-bind="glyph"
      style={{
        width: size,
        height: size,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        overflow: 'hidden',
        flex: '0 0 auto',
      }}
    >
      {placed ? (
        <img src={placed} alt="" style={{ width: inset, height: inset, objectFit: 'contain' }} />
      ) : (
        <Bind
          path="text"
          value={content.text.slice(0, 3)}
          fit="shrink"
          placeholder="AB"
          style={{
            fontFamily: fontStack(brand, 'heading'),
            fontWeight: 800,
            fontSize: letterSize,
            lineHeight: 1,
            letterSpacing: '-0.04em',
            color: letterInk,
            textTransform: 'uppercase',
          }}
        />
      )}
    </div>
  );
}

/** The avatar: a shaped container with the mark inside it. */
function Badge({
  brand,
  content,
  ground,
  size,
  shape,
  ring,
  picks,
}: {
  brand: Brand;
  content: ProfileContent;
  ground: Ground;
  size: number;
  shape: Shape;
  /** A drawn edge instead of a fill. Not text, so not contrast-bound. */
  ring?: string;
  picks?: TemplateDesignPicks;
}) {
  const style: CSSProperties = {
    width: size,
    height: size,
    borderRadius: RADIUS[shape](size),
    background: ground.bg,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    flex: '0 0 auto',
    ...(ring ? { boxShadow: `0 0 0 ${Math.max(1, Math.round(size * 0.035))}px ${ring}` } : {}),
  };
  return (
    <div style={style}>
      <Glyph
        brand={brand}
        content={content}
        ground={ground}
        size={size}
        shape={shape}
        picks={picks}
      />
    </div>
  );
}

/* ── The row the avatar is always seen in ─────────────────────────── */

function Caption({
  brand,
  content,
  ground,
  align = 'center',
  size = 9,
}: {
  brand: Brand;
  content: ProfileContent;
  ground: Ground;
  align?: 'left' | 'center';
  size?: number;
}) {
  return (
    <div
      style={{
        display: 'flex',
        flexDirection: 'column',
        gap: 2,
        minWidth: 0,
        alignItems: align === 'center' ? 'center' : 'flex-start',
        textAlign: align,
      }}
    >
      <Bind
        path="tabTitle"
        value={content.tabTitle}
        fit="shrink"
        placeholder="Your brand"
        style={{
          fontFamily: fontStack(brand, 'heading'),
          fontWeight: 700,
          fontSize: size,
          lineHeight: 1.15,
          letterSpacing: '-0.015em',
          color: ground.ink,
        }}
      />
      <Bind
        path="url"
        value={content.url}
        fit="clamp"
        placeholder="yoursite.co"
        style={{
          fontFamily: fontStack(brand, 'body'),
          fontWeight: 500,
          fontSize: Math.round(size * 0.78),
          lineHeight: 1.2,
          color: ground.soft,
        }}
      />
    </div>
  );
}

/* ── The 24 ───────────────────────────────────────────────────────── */

/**
 * Six readings of "a mark in a frame on a ground", one per layout.
 *
 * `portrait` centres it, `row` is the account line a follower actually
 * sees, `band` gives the identity its own solid foot, `ring` draws the
 * frame instead of filling it, `corner` and `stack` are the two asymmetric
 * placements. Four container shapes across six layouts is the whole
 * family — a study, not a gallery.
 */
type Layout = 'portrait' | 'row' | 'band' | 'ring' | 'corner' | 'stack';

type Spec = {
  name: string;
  layout: Layout;
  shape: Shape;
  /** The page's ground. */
  page: Fill;
  /** The badge's ground. `page` means "no fill" — used by `ring`. */
  badge: Fill;
};

const SPECS: Spec[] = [
  // Portrait — the avatar centred, the account under it.
  { name: 'Solid Circle', layout: 'portrait', shape: 'circle', page: 'paper', badge: 'brand' },
  { name: 'Brand Squircle', layout: 'portrait', shape: 'squircle', page: 'brand', badge: 'paper' },
  { name: 'Tinted Rounded', layout: 'portrait', shape: 'rounded', page: 'tint', badge: 'ink' },
  { name: 'Night Square', layout: 'portrait', shape: 'square', page: 'ink', badge: 'brand' },

  // Row — the account line: avatar left, name and address beside it.
  { name: 'Circle Row', layout: 'row', shape: 'circle', page: 'paper', badge: 'brand' },
  { name: 'Quiet Row', layout: 'row', shape: 'squircle', page: 'tint', badge: 'ink' },
  { name: 'Brand Row', layout: 'row', shape: 'rounded', page: 'brand', badge: 'paper' },
  { name: 'Support Row', layout: 'row', shape: 'square', page: 'support', badge: 'paper' },

  // Band — the identity gets its own solid foot.
  { name: 'Circle Band', layout: 'band', shape: 'circle', page: 'brand', badge: 'paper' },
  { name: 'Paper Band', layout: 'band', shape: 'squircle', page: 'paper', badge: 'brand' },
  { name: 'Night Band', layout: 'band', shape: 'rounded', page: 'ink', badge: 'brand' },
  { name: 'Tint Band', layout: 'band', shape: 'square', page: 'tint', badge: 'ink' },

  // Ring — the frame is drawn, not filled, so the page shows through.
  { name: 'Ring Circle', layout: 'ring', shape: 'circle', page: 'paper', badge: 'page' },
  { name: 'Ring Squircle', layout: 'ring', shape: 'squircle', page: 'tint', badge: 'page' },
  { name: 'Ring Rounded', layout: 'ring', shape: 'rounded', page: 'brand', badge: 'page' },
  { name: 'Ring Square', layout: 'ring', shape: 'square', page: 'ink', badge: 'page' },

  // Corner — the mark held low and right, the account high and left.
  { name: 'Corner Circle', layout: 'corner', shape: 'circle', page: 'brand', badge: 'paper' },
  { name: 'Corner Squircle', layout: 'corner', shape: 'squircle', page: 'paper', badge: 'ink' },
  { name: 'Corner Rounded', layout: 'corner', shape: 'rounded', page: 'support', badge: 'paper' },
  { name: 'Corner Square', layout: 'corner', shape: 'square', page: 'tint', badge: 'brand' },

  // Stack — mark above, account below, both left-aligned.
  { name: 'Stacked Circle', layout: 'stack', shape: 'circle', page: 'ink', badge: 'brand' },
  { name: 'Stacked Squircle', layout: 'stack', shape: 'squircle', page: 'brand', badge: 'paper' },
  { name: 'Stacked Rounded', layout: 'stack', shape: 'rounded', page: 'paper', badge: 'brand' },
  { name: 'Stacked Square', layout: 'stack', shape: 'square', page: 'support', badge: 'ink' },
];

function groundOf(g: Grounds, fill: Fill, page: Ground): Ground {
  switch (fill) {
    case 'brand':
      return g.brand;
    case 'support':
      return g.support;
    case 'paper':
      return g.paper;
    case 'tint':
      return g.tint;
    case 'ink':
      return g.ink;
    case 'page':
      return page;
  }
}

function ProfileDesign({
  brand,
  content,
  spec,
  g,
  picks,
}: {
  brand: Brand;
  content: ProfileContent;
  spec: Spec;
  g: Grounds;
  picks?: TemplateDesignPicks;
}) {
  const page = groundOf(g, spec.page, g.paper);
  const badge = groundOf(g, spec.badge, page);
  // A ring carries no words, so it wants the brand colour that can be
  // SEEN on this page (`mark`, WCAG 3:1) rather than the one held to
  // reading contrast — which on a light brand is not the brand's colour
  // at all, and would draw every ring in near-black.
  const ring = spec.layout === 'ring' ? page.mark : undefined;

  const avatar = (size: number) => (
    <Badge
      brand={brand}
      content={content}
      ground={badge}
      size={size}
      shape={spec.shape}
      ring={ring}
      picks={picks}
    />
  );

  switch (spec.layout) {
    case 'portrait':
      return (
        <Frame ground={page} pad={20}>
          <div
            style={{
              flex: 1,
              display: 'flex',
              flexDirection: 'column',
              alignItems: 'center',
              justifyContent: 'center',
              gap: 12,
              minHeight: 0,
            }}
          >
            {avatar(108)}
            <Caption brand={brand} content={content} ground={page} />
          </div>
        </Frame>
      );

    case 'row':
      return (
        <Frame ground={page} pad={20}>
          <div
            style={{
              flex: 1,
              display: 'flex',
              alignItems: 'center',
              gap: 12,
              minHeight: 0,
              minWidth: 0,
            }}
          >
            {avatar(64)}
            <Caption brand={brand} content={content} ground={page} align="left" size={10} />
          </div>
        </Frame>
      );

    case 'band':
      return (
        <Frame ground={page} pad={0}>
          <div
            style={{
              flex: 1,
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              minHeight: 0,
            }}
          >
            {avatar(96)}
          </div>
          <div
            style={{
              background: badge.bg,
              padding: '12px 18px',
              display: 'flex',
              justifyContent: 'center',
            }}
          >
            <Caption brand={brand} content={content} ground={badge} size={9} />
          </div>
        </Frame>
      );

    case 'ring':
      return (
        <Frame ground={page} pad={20}>
          <div
            style={{
              flex: 1,
              display: 'flex',
              flexDirection: 'column',
              alignItems: 'center',
              justifyContent: 'center',
              gap: 14,
              minHeight: 0,
            }}
          >
            {avatar(100)}
            <Caption brand={brand} content={content} ground={page} />
          </div>
        </Frame>
      );

    case 'corner':
      return (
        <Frame ground={page} pad={20}>
          <Caption brand={brand} content={content} ground={page} align="left" size={10} />
          <div
            style={{
              marginTop: 'auto',
              display: 'flex',
              justifyContent: 'flex-end',
            }}
          >
            {avatar(84)}
          </div>
        </Frame>
      );

    case 'stack':
      return (
        <Frame ground={page} pad={20}>
          <div style={{ display: 'flex' }}>{avatar(76)}</div>
          <div style={{ marginTop: 'auto' }}>
            <Caption brand={brand} content={content} ground={page} align="left" size={11} />
          </div>
          <div
            aria-hidden
            style={{
              marginTop: 10,
              height: 2,
              width: 34,
              background: mixHex(page.ink, page.bg, 0.35),
            }}
          />
        </Frame>
      );
  }
}

export function SocialProfileExtendedRenderer({ brand, templateIndex, content }: Props) {
  const c = profileContentFor(brand, content);
  const picks = content?.picks;
  const g = groundsFor(brand, picks);
  const spec = SPECS[templateIndex] ?? SPECS[0]!;
  return <ProfileDesign brand={brand} content={c} spec={spec} g={g} picks={picks} />;
}

/** Every design in the family, in id order. `ext-N` is `DESIGNS[N-1]`. */
export const PROFILE_DESIGNS: ReadonlyArray<{ name: string }> = SPECS.map((s) => ({
  name: s.name,
}));

/** Which style chip a layout wears. */
const CATEGORY: Record<Layout, string> = {
  portrait: 'Bold',
  row: 'Modern',
  band: 'Bold',
  ring: 'Minimalist',
  corner: 'Modern',
  stack: 'Minimalist',
};

/**
 * The first eighteen ids. The remaining six (`ext-19` … `ext-24`) are
 * declared by `SocialProfileExtended2` because the shared dispatch splits
 * this family at 18 — the split is arithmetic, not a design boundary.
 */
export const SOCIAL_PROFILE_EXTENDED = SPECS.slice(0, 18).map((s, i) => ({
  idSuffix: `ext-${i + 1}`,
  name: s.name,
  category: CATEGORY[s.layout],
}));

/** The last six, for `SocialProfileExtended2` to publish. */
export const SOCIAL_PROFILE_TAIL = SPECS.slice(18).map((s, i) => ({
  idSuffix: `ext-${i + 19}`,
  name: s.name,
  category: CATEGORY[s.layout],
}));

/** Every kept id, in order. */
export const PROFILE_KEPT_IDS: ReadonlyArray<string> = SPECS.map(
  (_, i) => `profile-icons-ext-${i + 1}`,
);
