/**
 * Product Surface Registry — the human-metadata layer of the Product Surface
 * Explorer (/_dev/product-map).
 *
 * IMPORTANT: this is NOT the source of truth for what routes exist — App.tsx is.
 * `discovery.ts` parses the real router source at runtime and the explorer warns
 * when (a) a real route has no entry here, or (b) an entry here points at a route
 * that no longer exists. A unit test enforces the same cross-check in CI
 * (registry.test.ts), so this file cannot silently go stale.
 *
 * Classification vocabulary is in ./types.ts. `duplicateGroup` links surfaces
 * that plausibly serve the same capability (evidence-based, not name-similarity).
 */
import type { SurfaceEntry } from './types';

export const SURFACE_REGISTRY: SurfaceEntry[] = [
  // ═══ AUTH ═══════════════════════════════════════════════════════════
  { id: 'auth-login', name: 'Login', route: '/login', type: 'PAGE', status: 'CURRENT', reachability: 'NAVIGATION', namespace: 'Public', source: 'src/pages/auth/login.tsx', description: 'Email/password + OAuth sign-in.', area: 'AUTH' },
  { id: 'auth-signup', name: 'Sign up', route: '/signup', type: 'PAGE', status: 'CURRENT', reachability: 'NAVIGATION', namespace: 'Public', source: 'src/pages/auth/login.tsx', description: 'Registration — same component as /login in signup mode.', area: 'AUTH' },
  { id: 'auth-callback', name: 'Auth callback', route: '/auth/callback', type: 'PAGE', status: 'CURRENT', reachability: 'INTERNAL LINK', namespace: 'Public', source: 'src/pages/auth/callback.tsx', description: 'Where Google OAuth and email links land (PKCE code exchange), then forwards to ?next.', area: 'AUTH' },
  { id: 'auth-reset', name: 'Reset password', route: '/auth/reset-password', type: 'PAGE', status: 'CURRENT', reachability: 'INTERNAL LINK', namespace: 'Public', source: 'src/pages/auth/reset-password.tsx', description: 'Password-recovery landing from the reset email.', area: 'AUTH' },

  // ═══ DASHBOARD / WORKSPACE ══════════════════════════════════════════
  { id: 'ws-home', name: 'Workspace Home', route: '/dashboard', type: 'PAGE', status: 'CURRENT', reachability: 'NAVIGATION', namespace: 'Workspace', source: 'src/pages/workspace/Home.tsx', description: 'The v2 workspace home — brand grid, continue-working surface, quick actions.', area: 'DASHBOARD' },
  { id: 'ws-brands', name: 'Brands', route: '/dashboard/brands', type: 'PAGE', status: 'CURRENT', reachability: 'NAVIGATION', namespace: 'Workspace', source: 'src/pages/dashboard/brands/index.tsx', description: 'All brands list — open, create, switch UI preference.', area: 'DASHBOARD' },
  { id: 'ws-activity', name: 'Activity', route: '/dashboard/activity', type: 'PAGE', status: 'CURRENT', reachability: 'NAVIGATION', namespace: 'Workspace', source: 'src/pages/dashboard/activity/index.tsx', description: 'Workspace activity feed.', area: 'DASHBOARD' },
  { id: 'ws-learn', name: 'Learn', route: '/learn', type: 'PAGE', status: 'CURRENT', reachability: 'NAVIGATION', namespace: 'Workspace', source: 'src/pages/workspace/Learn.tsx', description: 'Learning/help hub in the workspace shell.', area: 'DASHBOARD' },
  { id: 'ws-features', name: 'Features index', route: '/dashboard/features', type: 'PAGE', status: 'UNKNOWN', reachability: 'INTERNAL LINK', namespace: 'Workspace', source: 'src/pages/dashboard/features/index.tsx', description: 'A linked catalog of features; thin page — candidate for review.', area: 'DASHBOARD' },
  { id: 'ws-logo-maker-entry', name: 'Logo Maker (workspace entry)', route: '/dashboard/logo-maker', type: 'PAGE', status: 'CURRENT', reachability: 'NAVIGATION', namespace: 'Workspace', source: 'src/pages/dashboard/logo-maker.tsx', description: 'Workspace-level entry into the Logo Maker.', area: 'DASHBOARD', duplicateGroup: 'logo-maker-entry' },
  { id: 'ws-admin-brands', name: 'Admin: brands (old dashboard)', route: '/dashboard/admin/brands', type: 'ADMIN', status: 'LEGACY', reachability: 'NAVIGATION', namespace: 'Admin', source: 'src/pages/dashboard/admin/brands/index.tsx', description: 'Pre-/admin generation of the all-brands admin list. Still linked from DashboardSidebar.', area: 'DASHBOARD', duplicateGroup: 'admin-brands' },
  { id: 'ws-admin-analytics', name: 'Admin: analytics (old dashboard)', route: '/dashboard/admin/analytics', type: 'ADMIN', status: 'LEGACY', reachability: 'NAVIGATION', namespace: 'Admin', source: 'src/pages/dashboard/admin/analytics/index.tsx', description: 'Pre-/admin generation of system analytics. Overlaps the /admin dashboard.', area: 'DASHBOARD', duplicateGroup: 'admin-analytics' },

  // ═══ ONBOARDING ═════════════════════════════════════════════════════
  { id: 'ob-v1', name: 'Onboarding v1', route: '/onboarding', type: 'PAGE', status: 'LEGACY', reachability: 'INTERNAL LINK', namespace: 'Shared', source: 'src/pages/onboarding/index.tsx', description: 'First-generation onboarding. Still navigated to from useDashboard/LogoExportPanel.', area: 'ONBOARDING', duplicateGroup: 'onboarding-gen' },
  { id: 'ob-v1-preview', name: 'Brand preview (onboarding v1)', route: '/onboarding/preview', type: 'FLOW STEP', status: 'LEGACY', reachability: 'INTERNAL LINK', namespace: 'Shared', source: 'src/pages/onboarding/preview.tsx', description: 'Preview step of the v1 flow.', area: 'ONBOARDING' },
  { id: 'ob-v2', name: 'Onboarding v2 (brand)', route: '/onboarding-brand', type: 'PAGE', status: 'LEGACY', reachability: 'INTERNAL LINK', namespace: 'Shared', source: 'src/pages/onboarding-brand/index.tsx', description: 'Second-generation onboarding. Navigated from BrandChooserDialog + templates marketplace.', area: 'ONBOARDING', duplicateGroup: 'onboarding-gen' },
  { id: 'ob-review', name: 'Onboard Brand — review & resume', route: '/onboard-brand/:slug', type: 'FLOW STEP', status: 'CURRENT', reachability: 'INTERNAL LINK', namespace: 'Shared', source: 'src/pages/onboard-brand/index.tsx', description: 'Review your uploads, at a restorable address. The brand exists by this point, so the URL survives a refresh and can be shared or resumed.', area: 'ONBOARDING' },
  { id: 'ob-create', name: 'Onboard Brand — create from scratch', route: '/onboard-brand/create', type: 'PAGE', status: 'CURRENT', reachability: 'INTERNAL LINK', namespace: 'Shared', source: 'src/pages/onboard-brand/create.tsx', description: 'The from-scratch path: define, then pick the feel. Reached from the "No brand yet?" switch on /onboard-brand.', area: 'ONBOARDING', duplicateGroup: 'onboarding-gen' },
  { id: 'ob-canonical', name: 'Onboard Brand', route: '/onboard-brand', type: 'PAGE', status: 'CURRENT', reachability: 'NAVIGATION', namespace: 'Shared', source: 'src/pages/onboard-brand/index.tsx', description: 'The upload onboarding path — Set up your Brand, then Review your uploads. Switches to /onboard-brand/create for the from-scratch path.', area: 'ONBOARDING' },

  // ═══ BRAND (STUDIO /b/:slug) ════════════════════════════════════════
  { id: 'b-index', name: 'Studio index (fallback)', route: '/b/:slug', type: 'REDIRECT', status: 'REDIRECT', reachability: 'REDIRECT ONLY', namespace: 'Studio', source: 'src/App.tsx (StudioToClassicFallback)', description: 'No Studio overview exists — bounces to the appropriate section.', area: 'BRAND (STUDIO)' },
  { id: 'b-catchall', name: 'Studio catch-all → Classic', route: '/b/:slug/*', type: 'REDIRECT', status: 'REDIRECT', reachability: 'REDIRECT ONLY', namespace: 'Studio', source: 'src/App.tsx (StudioToClassicFallback)', description: 'Unmigrated Studio sections fall back to the Classic equivalent.', area: 'BRAND (STUDIO)' },
  { id: 'b-setup', name: 'Setup (Studio)', route: '/b/:slug/setup', type: 'PAGE', status: 'CURRENT', reachability: 'NAVIGATION', namespace: 'Studio', source: 'src/pages/b/[slug]/setup.tsx', description: 'Brand setup surface — logos, colors, fonts, voice, about. Writes through canonical identity ops.', area: 'SETUP & IDENTITY', duplicateGroup: 'brand-home' },
  { id: 'b-brand-kit', name: 'Brand Kit (Studio cosmos)', route: '/b/:slug/brand-kit', type: 'PAGE', status: 'CURRENT', reachability: 'NAVIGATION', namespace: 'Studio', source: 'src/features/brand-kit/BrandKitCosmosPage.tsx', description: 'The visual brand-kit showcase — 7 sections, drilldowns, card editor.', area: 'BRAND KIT', duplicateGroup: 'brand-kit' },
  { id: 'b-brand-kit-next', name: 'Brand Kit lifecycle redesign (next)', route: '/b/:slug/brand-kit-next', type: 'PAGE', status: 'DEV', reachability: 'DIRECT URL ONLY', namespace: 'Studio', source: 'src/features/brand-kit/BrandKitNextPage.tsx', description: 'Generate/review/approve lifecycle experiment — owner iterating; not in top nav (direct URL only).', area: 'BRAND KIT', duplicateGroup: 'brand-kit' },
  { id: 'b-guideline', name: 'Guideline (Studio)', route: '/b/:slug/guideline', type: 'PAGE', status: 'CURRENT', reachability: 'NAVIGATION', namespace: 'Studio', source: 'src/pages/b/[slug]/guideline.tsx', description: 'Studio guideline surface.', area: 'GUIDELINES', duplicateGroup: 'guideline' },
  { id: 'b-design', name: 'Design launchpad (Studio)', route: '/b/:slug/design', type: 'PAGE', status: 'CURRENT', reachability: 'NAVIGATION', namespace: 'Studio', source: 'src/pages/b/[slug]/design.tsx', description: 'Design entry — Blank Canvas, AI Design, Recent designs.', area: 'DESIGN & EDITORS' },
  { id: 'b-tools', name: 'Tools hub (Studio)', route: '/b/:slug/tools', type: 'PAGE', status: 'CURRENT', reachability: 'NAVIGATION', namespace: 'Studio', source: 'src/pages/b/[slug]/tools.tsx', description: 'Brand-scoped tools directory.', area: 'TOOLS' },
  { id: 'b-templates', name: 'Templates (Studio)', route: '/b/:slug/templates', type: 'PAGE', status: 'CURRENT', reachability: 'NAVIGATION', namespace: 'Studio', source: 'src/pages/b/[slug]/templates.tsx', description: 'Brand templates browser (tabs: All · Brand Board · Guidelines · Bento · Social · Print · Screen · Utility).', area: 'TEMPLATES' },
  { id: 'b-identity', name: 'Identity (Studio)', route: '/b/:slug/identity', type: 'PAGE', status: 'CURRENT', reachability: 'NAVIGATION', namespace: 'Studio', source: 'src/pages/b/[slug]/identity/index.tsx', description: 'Identity hub — tabs: Logo · Colors · Typography · Voice · Strategy.', area: 'SETUP & IDENTITY' },
  { id: 'b-content', name: 'Content (Studio)', route: '/b/:slug/content', type: 'PAGE', status: 'CURRENT', reachability: 'NAVIGATION', namespace: 'Studio', source: 'src/pages/b/[slug]/content.tsx', description: 'Content hub — tabs: Calendar · Posts · Drafts; social formats open the editor directly.', area: 'BRAND (STUDIO)' },
  { id: 'b-folders', name: 'Folders / DAM (Studio)', route: '/b/:slug/folders', type: 'PAGE', status: 'CURRENT', reachability: 'NAVIGATION', namespace: 'Studio', source: 'src/features/dam/DamPage.tsx', description: 'Asset library (server-backed via public.assets) + Designs tab.', area: 'ASSETS', duplicateGroup: 'folders' },
  { id: 'b-share', name: 'Share (Studio)', route: '/b/:slug/share', type: 'PAGE', status: 'CURRENT', reachability: 'NAVIGATION', namespace: 'Studio', source: 'src/pages/b/[slug]/share.tsx', description: 'Share hub — tabs: Guidelines · Showcase · Exports (public link, logo deck).', area: 'PUBLIC & SHARE' },
  { id: 'b-settings', name: 'Brand settings (Studio mount)', route: '/b/:slug/settings', type: 'PAGE', status: 'CURRENT', reachability: 'NAVIGATION', namespace: 'Studio', source: 'src/features/brand-kit-alt/BrandSettingsPage.tsx', description: 'Brand settings — SAME component as Classic /a/:slug/settings.', area: 'SETTINGS', duplicateGroup: 'brand-settings' },
  { id: 'b-editor', name: 'Editor (Studio, brand-scoped)', route: '/b/:slug/editor', type: 'EDITOR', status: 'CURRENT', reachability: 'INTERNAL LINK', namespace: 'Studio', source: 'src/features/editor/shell/Editor.tsx', description: 'Unified Fabric editor mounted in the brand context.', area: 'DESIGN & EDITORS' },
  { id: 'b-design-editor', name: 'Design editor (production route)', route: '/b/:slug/design/:designSlug', type: 'EDITOR', status: 'CURRENT', reachability: 'INTERNAL LINK', namespace: 'Studio', source: 'src/pages/b/[slug]/design/[designSlug].tsx', description: 'THE production unified editor — Fabric canvas, AI prompt bar, autosave to server-backed designs.', area: 'DESIGN & EDITORS', duplicateGroup: 'design-editor' },
  { id: 'b-social', name: 'Social media designer', route: '/b/:slug/social-media', type: 'EDITOR', status: 'CURRENT', reachability: 'NAVIGATION', namespace: 'Studio', source: 'src/features/social-media/SocialMediaDesigner.tsx', description: 'Platform/format-aware social design surface.', area: 'DESIGN & EDITORS' },
  { id: 'b-presentations', name: 'Presentations', route: '/b/:slug/presentations', type: 'PAGE', status: 'CURRENT', reachability: 'NAVIGATION', namespace: 'Studio', source: 'src/pages/b/[slug]/presentations.tsx', description: 'Presentation hub (v1 DOM-slide engine via EditorWorkspace).', area: 'PRESENTATIONS & DECKS' },
  { id: 'b-case-study', name: 'Case study deck', route: '/b/:slug/case-study', type: 'PAGE', status: 'CURRENT', reachability: 'INTERNAL LINK', namespace: 'Studio', source: 'src/features/case-study-deck/pages/CaseStudyPage.tsx', description: 'Case-study deck viewer (linked from Share + Templates).', area: 'PRESENTATIONS & DECKS' },
  { id: 'b-case-study-edit', name: 'Case study slide editor', route: '/b/:slug/case-study/edit/:idx', type: 'EDITOR', status: 'CURRENT', reachability: 'INTERNAL LINK', namespace: 'Studio', source: 'src/features/case-study-deck/pages/CaseStudySlideEditorPage.tsx', description: 'Per-slide inline editor for the case-study deck.', area: 'PRESENTATIONS & DECKS' },
  { id: 'b-pitch-deck', name: 'Pitch deck', route: '/b/:slug/pitch-deck', type: 'PAGE', status: 'DEFERRED', reachability: 'DIRECT URL ONLY', namespace: 'Studio', source: 'src/features/pitch-deck/PitchDeckPage.tsx', description: 'ORPHAN route — hardcoded variants, no in-app link. One of two overlapping generic-deck engines (product decision pending).', area: 'PRESENTATIONS & DECKS', duplicateGroup: 'generic-deck' },
  { id: 'b-deck-v2', name: 'Deck OS v2', route: '/b/:slug/deck-v2', type: 'PAGE', status: 'DEFERRED', reachability: 'DIRECT URL ONLY', namespace: 'Studio', source: 'src/pages/b/[slug]/deck-v2.tsx', description: 'ORPHAN route — newer AI script-to-deck engine (layout registry + GeneratePanel), unlinked. The other overlapping generic-deck engine.', area: 'PRESENTATIONS & DECKS', duplicateGroup: 'generic-deck' },
  { id: 'b-brand-guides', name: 'Brand guides', route: '/b/:slug/brand-guides', type: 'PAGE', status: 'CURRENT', reachability: 'INTERNAL LINK', namespace: 'Studio', source: 'src/pages/b/[slug]/brand-guides.tsx', description: 'Brand-guides family (routes through the legacy multi-page guidelines UI).', area: 'GUIDELINES', duplicateGroup: 'guideline' },
  { id: 'b-logo-presentation', name: 'Logo presentation', route: '/b/:slug/logo-presentation', type: 'PAGE', status: 'CURRENT', reachability: 'INTERNAL LINK', namespace: 'Studio', source: 'src/features/logo-presentation/index.tsx', description: 'Logo reveal deck — two live viewers (full + simple) chosen by template.', area: 'PRESENTATIONS & DECKS' },
  { id: 'b-guidelines-canvas', name: 'Guidelines canvas editor', route: '/b/:slug/guidelines/canvas', type: 'EDITOR', status: 'CURRENT', reachability: 'INTERNAL LINK', namespace: 'Studio', source: 'src/features/guidelines/CanvasGuidelinesEditor.tsx', description: 'Canvas-style guideline editor — persists to guideline_presentations/_slides tables.', area: 'GUIDELINES', duplicateGroup: 'guideline' },
  { id: 'b-guidelines-blocks', name: 'Guidelines blocks editor', route: '/b/:slug/guidelines/blocks', type: 'EDITOR', status: 'EXPERIMENTAL', reachability: 'DIRECT URL ONLY', namespace: 'Studio', source: 'src/pages/b/[slug]/guidelines/blocks.tsx', description: 'Block-based guideline editing experiment.', area: 'GUIDELINES', duplicateGroup: 'guideline' },
  { id: 'b-brand-board', name: 'Brand Board', route: '/b/:slug/brand-board', type: 'EDITOR', status: 'CURRENT', reachability: 'NAVIGATION', namespace: 'Studio', source: 'src/features/brand-board/BrandBoardPage.tsx', description: 'Interactive brand-identity poster editor — shuffle colors/type/UI style, saves through canonical identity ops.', area: 'BRAND (STUDIO)' },
  { id: 'b-bento', name: 'Bento (brand)', route: '/b/:slug/bento', type: 'EDITOR', status: 'CURRENT', reachability: 'NAVIGATION', namespace: 'Studio', source: 'src/features/bento/BentoEditor.tsx', description: 'Bento-grid brand page editor.', area: 'BRAND (STUDIO)', duplicateGroup: 'bento' },
  { id: 'b-analytics', name: 'Brand analytics', route: '/b/:slug/analytics', type: 'PAGE', status: 'CURRENT', reachability: 'NAVIGATION', namespace: 'Studio', source: 'src/pages/b/[slug]/analytics.tsx', description: 'Per-brand analytics view.', area: 'BRAND (STUDIO)' },
  { id: 'b-approvals', name: 'Approvals', route: '/b/:slug/approvals', type: 'PAGE', status: 'DEFERRED', reachability: 'DIRECT URL ONLY', namespace: 'Studio', source: 'src/pages/b/[slug]/approvals.tsx', description: 'Approvals queue — v1 localStorage store (server tables exist, deferred collaboration feature).', area: 'BRAND (STUDIO)' },
  { id: 'b-tool-variant', name: 'Variant Studio (in-app)', route: '/b/:slug/tools/variant-studio', type: 'PAGE', status: 'CURRENT', reachability: 'NAVIGATION', namespace: 'Studio', source: 'src/features/tools/variant-studio/', description: 'Logo variant generator scoped to the brand.', area: 'TOOLS', duplicateGroup: 'tool-variant' },
  { id: 'b-tool-colors', name: 'UI Color System (in-app)', route: '/b/:slug/tools/ui-color-system', type: 'PAGE', status: 'CURRENT', reachability: 'NAVIGATION', namespace: 'Studio', source: 'src/pages/dashboard/brand/[slug]/tools/ui-color-system.tsx', description: 'Color-system generator; Save-to-Brand writes through changeBrandColors.', area: 'TOOLS', duplicateGroup: 'tool-colors' },
  { id: 'b-tool-typescale', name: 'Typescale (in-app)', route: '/b/:slug/tools/typescale', type: 'PAGE', status: 'CURRENT', reachability: 'NAVIGATION', namespace: 'Studio', source: 'src/features/tools/typescale/', description: 'Type-scale explorer; family picks persist through canonical typography op.', area: 'TOOLS', duplicateGroup: 'tool-typescale' },
  { id: 'b-tool-mockup', name: 'Mockup Studio (in-app)', route: '/b/:slug/tools/mockup-studio', type: 'PAGE', status: 'CURRENT', reachability: 'NAVIGATION', namespace: 'Studio', source: 'src/features/mockup-studio/', description: 'PixiJS mockup renderer in brand context.', area: 'TOOLS', duplicateGroup: 'tool-mockup' },

  // ═══ BRAND (CLASSIC /a/:slug) ═══════════════════════════════════════
  { id: 'a-index', name: 'Classic index → Setup', route: '/a/:slug', type: 'REDIRECT', status: 'REDIRECT', reachability: 'REDIRECT ONLY', namespace: 'Classic', source: 'src/App.tsx (ClassicIndexToSetupRedirect)', description: 'Bare Classic URL forwards to /a/:slug/setup.', area: 'BRAND (CLASSIC)' },
  { id: 'a-setup', name: 'Overview/Home (Classic)', route: '/a/:slug/setup', type: 'PAGE', status: 'LEGACY', reachability: 'NAVIGATION', namespace: 'Classic', source: 'src/features/brand/…/BrandHomePage', description: 'Classic brand home (Recent/Search/Templates tabs). Live via the UI-preference toggle.', area: 'BRAND (CLASSIC)', duplicateGroup: 'brand-home' },
  { id: 'a-edit', name: 'Brand metadata editor (Classic)', route: '/a/:slug/edit', type: 'PAGE', status: 'LEGACY', reachability: 'NAVIGATION', namespace: 'Classic', source: 'src/features/brand/components/BrandEditor.tsx', description: 'Legacy brand metadata editor.', area: 'BRAND (CLASSIC)' },
  { id: 'a-identity', name: 'Identity (Classic)', route: '/a/:slug/identity', type: 'PAGE', status: 'LEGACY', reachability: 'NAVIGATION', namespace: 'Classic', source: 'src/pages (IdentityPage)', description: 'Classic identity hub.', area: 'BRAND (CLASSIC)' },
  { id: 'a-content', name: 'Content (Classic)', route: '/a/:slug/content', type: 'PAGE', status: 'LEGACY', reachability: 'NAVIGATION', namespace: 'Classic', source: 'src/pages (ContentHubPage)', description: 'Classic content hub.', area: 'BRAND (CLASSIC)' },
  { id: 'a-design', name: 'Design launchpad (Classic)', route: '/a/:slug/design', type: 'PAGE', status: 'LEGACY', reachability: 'NAVIGATION', namespace: 'Classic', source: 'src/pages (DesignLaunchpadPage)', description: 'Classic design launchpad.', area: 'BRAND (CLASSIC)' },
  { id: 'a-share', name: 'Share (Classic)', route: '/a/:slug/share', type: 'PAGE', status: 'LEGACY', reachability: 'NAVIGATION', namespace: 'Classic', source: 'src/pages (SharePage)', description: 'Classic share hub.', area: 'BRAND (CLASSIC)' },
  { id: 'a-templates', name: 'Templates (Classic)', route: '/a/:slug/templates', type: 'PAGE', status: 'LEGACY', reachability: 'NAVIGATION', namespace: 'Classic', source: 'src/pages (BrandTemplatesPage)', description: 'Classic templates browser.', area: 'BRAND (CLASSIC)' },
  { id: 'a-brand-kit', name: 'Brand Kit hub (Classic V2)', route: '/a/:slug/brand-kit', type: 'PAGE', status: 'LEGACY', reachability: 'NAVIGATION', namespace: 'Classic', source: 'src/features/brand-kit-alt/BrandKitV2Page.tsx', description: 'Edit-first brand-kit hub with bulk export + PDF guides (the alternate fork).', area: 'BRAND KIT', duplicateGroup: 'brand-kit' },
  { id: 'a-brandkit-module', name: 'Brand Kit module drilldown (Classic)', route: '/a/:slug/brandkit/:moduleId', type: 'PAGE', status: 'LEGACY', reachability: 'INTERNAL LINK', namespace: 'Classic', source: 'src/features/brandkit/ (BrandKitModulePage)', description: 'Per-module brand-kit view (renderers/templates per module).', area: 'BRAND KIT', duplicateGroup: 'brand-kit' },
  { id: 'a-folders', name: 'Folders / DAM (Classic mount)', route: '/a/:slug/folders', type: 'PAGE', status: 'LEGACY', reachability: 'NAVIGATION', namespace: 'Classic', source: 'src/features/dam/DamPage.tsx', description: 'Same DamPage as Studio, Classic shell.', area: 'ASSETS', duplicateGroup: 'folders' },
  { id: 'a-studio', name: 'Consistency Studio', route: '/a/:slug/studio', type: 'PAGE', status: 'CURRENT', reachability: 'NAVIGATION', namespace: 'Classic', source: 'src/features/brand-consistency/ (ConsistencyStudioPage)', description: 'Brand Consistency engine — AI copy generation across output specs (now via anthropic-proxy).', area: 'TOOLS' },
  { id: 'a-guideline', name: 'Guidelines hub (Classic)', route: '/a/:slug/guideline', type: 'PAGE', status: 'LEGACY', reachability: 'NAVIGATION', namespace: 'Classic', source: 'src/features/guidelines/ (GuidelinesHubPage)', description: 'Classic multi-page guidelines hub/editor (52 files — its own dedicated UI).', area: 'GUIDELINES', duplicateGroup: 'guideline' },
  { id: 'a-settings', name: 'Brand settings (Classic mount)', route: '/a/:slug/settings', type: 'PAGE', status: 'LEGACY', reachability: 'NAVIGATION', namespace: 'Classic', source: 'src/features/brand-kit-alt/BrandSettingsPage.tsx', description: 'Same BrandSettingsV2Page as the Studio mount.', area: 'SETTINGS', duplicateGroup: 'brand-settings' },
  { id: 'a-r-kit', name: 'kit → brand-kit (rename compat)', route: '/a/:slug/kit', type: 'REDIRECT', status: 'REDIRECT', reachability: 'REDIRECT ONLY', namespace: 'Classic', source: 'src/App.tsx (ClassicKitToBrandKitRedirect)', description: 'Old path name; bookmark compatibility.', area: 'BRAND (CLASSIC)' },
  { id: 'a-r-guidelines', name: 'guidelines → guideline (rename compat)', route: '/a/:slug/guidelines', type: 'REDIRECT', status: 'REDIRECT', reachability: 'REDIRECT ONLY', namespace: 'Classic', source: 'src/App.tsx (ClassicGuidelinesToGuidelineRedirect)', description: 'Old path name; bookmark compatibility.', area: 'BRAND (CLASSIC)' },
  { id: 'a-r-assets', name: 'assets → templates', route: '/a/:slug/assets', type: 'REDIRECT', status: 'REDIRECT', reachability: 'REDIRECT ONLY', namespace: 'Classic', source: 'src/App.tsx (AssetsRedirect)', description: 'Assets catalog folded into Templates.', area: 'BRAND (CLASSIC)' },
  { id: 'a-r-dam', name: 'dam → folders', route: '/a/:slug/dam', type: 'REDIRECT', status: 'REDIRECT', reachability: 'REDIRECT ONLY', namespace: 'Classic', source: 'src/App.tsx (DamRedirect)', description: 'Old DAM path; preserves ?category filter.', area: 'BRAND (CLASSIC)' },
  { id: 'a-r-brandkit', name: 'brandkit (no id) → brand-kit', route: '/a/:slug/brandkit', type: 'REDIRECT', status: 'REDIRECT', reachability: 'REDIRECT ONLY', namespace: 'Classic', source: 'src/App.tsx (BrandKitRedirect)', description: 'Module hub without id forwards to the brand-kit hub.', area: 'BRAND (CLASSIC)' },
  { id: 'legacy-dashboard-brand', name: 'Legacy /dashboard/brand → Studio', route: '/dashboard/brand/:slug/*', type: 'REDIRECT', status: 'REDIRECT', reachability: 'REDIRECT ONLY', namespace: 'Shared', source: 'src/App.tsx (DashboardBrandToStudioRedirect)', description: 'Oldest brand namespace; 302s into /b (two-hop to Classic when unmigrated).', area: 'BRAND (CLASSIC)' },

  // ═══ EDITORS (standalone) ═══════════════════════════════════════════
  { id: 'ed-launcher', name: 'Editor launcher', route: '/editor', type: 'PAGE', status: 'CURRENT', reachability: 'INTERNAL LINK', namespace: 'Shared', source: 'src/pages/editor-launcher.tsx', description: 'Brand-chooser entry into the editor (standalone or brand-scoped).', area: 'DESIGN & EDITORS' },
  { id: 'ed-legacy', name: 'Legacy design editor (Gen-1)', route: '/editor/design/:slug', type: 'EDITOR', status: 'LEGACY', reachability: 'DIRECT URL ONLY', namespace: 'Shared', source: 'src/features/editor/components/EditorShell.tsx', description: 'OptimizedDesignEditor carve-out — kept only for its coupling to the frozen editable-export-v1 pipeline.', area: 'DESIGN & EDITORS', duplicateGroup: 'design-editor' },

  // ═══ LOGO MAKER (/logo-maker flow) ══════════════════════════════════
  { id: 'lm-mode', name: 'Logo Maker — mode select', route: '/logo-maker', type: 'FLOW STEP', status: 'CURRENT', reachability: 'NAVIGATION', namespace: 'Shared', source: 'src/features/logo-maker/flow/screens/01-mode-select.tsx', description: 'Entry: create with AI vs upload existing.', area: 'LOGO MAKER', duplicateGroup: 'logo-maker-entry' },
  { id: 'lm-brief', name: 'Logo Maker — brief', route: '/logo-maker/brief', type: 'FLOW STEP', status: 'CURRENT', reachability: 'INTERNAL LINK', namespace: 'Shared', source: 'src/features/logo-maker/flow/screens/02-brief.tsx', description: 'Brand brief inputs for generation.', area: 'LOGO MAKER' },
  { id: 'lm-generate', name: 'Logo Maker — generate', route: '/logo-maker/generate', type: 'FLOW STEP', status: 'DEFERRED', reachability: 'INTERNAL LINK', namespace: 'Shared', source: 'src/features/logo-maker/flow/screens/03-generate.tsx', description: 'Placeholder — full 36-concept AI pipeline (Claude + image model) is a future phase.', area: 'LOGO MAKER' },
  { id: 'lm-upload', name: 'Logo Maker — upload', route: '/logo-maker/upload', type: 'FLOW STEP', status: 'CURRENT', reachability: 'INTERNAL LINK', namespace: 'Shared', source: 'src/features/logo-maker/flow/screens/04-upload.tsx', description: 'Upload an existing logo into the flow.', area: 'LOGO MAKER' },
  { id: 'lm-editor', name: 'Logo Maker — editor', route: '/logo-maker/editor/:logoId', type: 'EDITOR', status: 'CURRENT', reachability: 'INTERNAL LINK', namespace: 'Shared', source: 'src/features/logo-maker/flow/screens/05-editor.tsx', description: 'Logo editing step (icon/layout/color/typography + AI suggestions).', area: 'LOGO MAKER' },
  { id: 'lm-variants', name: 'Logo Maker — variants', route: '/logo-maker/variants/:logoId', type: 'FLOW STEP', status: 'CURRENT', reachability: 'INTERNAL LINK', namespace: 'Shared', source: 'src/features/logo-maker/flow/screens/ (VariantStudioScreen)', description: 'Variant generation step.', area: 'LOGO MAKER' },
  { id: 'lm-brand-kit', name: 'Logo Maker — brand kit', route: '/logo-maker/brand-kit/:logoId', type: 'FLOW STEP', status: 'CURRENT', reachability: 'INTERNAL LINK', namespace: 'Shared', source: 'src/features/logo-maker/flow/screens/ (BrandKitScreen)', description: 'Brand-kit assembly from the created logo.', area: 'LOGO MAKER' },
  { id: 'lm-complete', name: 'Logo Maker — complete', route: '/logo-maker/complete/:brandId', type: 'FLOW STEP', status: 'CURRENT', reachability: 'INTERNAL LINK', namespace: 'Shared', source: 'src/features/logo-maker/flow/screens/06-complete.tsx', description: 'Completion — save to brand / continue into the app.', area: 'LOGO MAKER' },

  // ═══ TOOLS (public) ═════════════════════════════════════════════════
  { id: 'tools-dir', name: 'Tools directory (public)', route: '/tools', type: 'PUBLIC PAGE', status: 'CURRENT', reachability: 'NAVIGATION', namespace: 'Public', source: 'src/pages/tools/ (ToolsDirectoryPage)', description: 'Public marketing/tools directory.', area: 'TOOLS' },
  { id: 'tools-variant', name: 'Logo variant generator (public)', route: '/tools/logo-variant-generator', type: 'PUBLIC PAGE', status: 'CURRENT', reachability: 'INTERNAL LINK', namespace: 'Public', source: 'src/features/tools/variant-studio/', description: 'Public variant studio; claim flow converts session to a brand.', area: 'TOOLS', duplicateGroup: 'tool-variant' },
  { id: 'tools-svg', name: 'Logo to SVG (public)', route: '/tools/logo-to-svg', type: 'PUBLIC PAGE', status: 'CURRENT', reachability: 'INTERNAL LINK', namespace: 'Public', source: 'src/pages/tools/ (LogoToSvgPage)', description: 'Raster→SVG vectorizer tool.', area: 'TOOLS' },
  { id: 'tools-colors', name: 'UI Color System (public)', route: '/tools/ui-color-system', type: 'PUBLIC PAGE', status: 'CURRENT', reachability: 'INTERNAL LINK', namespace: 'Public', source: 'src/features/tools/ui-color-system/', description: 'Public color-system generator.', area: 'TOOLS', duplicateGroup: 'tool-colors' },
  { id: 'tools-typescale', name: 'Typescale (public)', route: '/tools/typescale', type: 'PUBLIC PAGE', status: 'CURRENT', reachability: 'INTERNAL LINK', namespace: 'Public', source: 'src/features/tools/typescale/', description: 'Public type-scale tool (anonymous session persistence).', area: 'TOOLS', duplicateGroup: 'tool-typescale' },
  { id: 'tools-mockup', name: 'Mockup Studio (public)', route: '/tools/mockup-studio', type: 'PUBLIC PAGE', status: 'CURRENT', reachability: 'INTERNAL LINK', namespace: 'Public', source: 'src/features/mockup-studio/', description: 'Standalone mockup studio.', area: 'TOOLS', duplicateGroup: 'tool-mockup' },
  { id: 'tools-claim', name: 'Tool session claim', route: '/claim', type: 'PAGE', status: 'CURRENT', reachability: 'REDIRECT ONLY', namespace: 'Public', source: 'src/features/tools/core/claim.ts (ClaimPage)', description: 'Converts an anonymous public-tool session into a real brand after signup.', area: 'TOOLS' },
  { id: 'tools-bento-public', name: 'Bento (standalone tool)', route: '/tools/bento', type: 'PAGE', status: 'CURRENT', reachability: 'INTERNAL LINK', namespace: 'Public', source: 'src/features/bento/', description: 'Bento editor outside a brand.', area: 'TOOLS', duplicateGroup: 'bento' },

  // ═══ TEMPLATES ══════════════════════════════════════════════════════
  { id: 'tpl-market', name: 'Templates marketplace', route: '/templates', type: 'PAGE', status: 'CURRENT', reachability: 'NAVIGATION', namespace: 'Workspace', source: 'src/pages/templates/ (TemplatesMarketplacePage)', description: 'Workspace templates browsing; picking one forces the brand chooser.', area: 'TEMPLATES', duplicateGroup: 'templates-market' },
  { id: 'tpl-market-alias', name: 'Marketplace', route: '/marketplace', type: 'PAGE', status: 'UNKNOWN', reachability: 'DIRECT URL ONLY', namespace: 'Workspace', source: 'src/App.tsx → marketplace element', description: 'Marketplace mount — overlaps /templates; review whether both should exist.', area: 'TEMPLATES', duplicateGroup: 'templates-market' },
  { id: 'tpl-ws', name: 'Templates (workspace v2 page)', route: '/dashboard/templates', type: 'PAGE', status: 'CURRENT', reachability: 'NAVIGATION', namespace: 'Workspace', source: 'src/pages/workspace/Templates.tsx', description: 'Workspace-shell templates page.', area: 'TEMPLATES', duplicateGroup: 'templates-market' },
  { id: 'tpl-builder', name: 'Template builder', route: '/templates/builder', type: 'EDITOR', status: 'EXPERIMENTAL', reachability: 'DIRECT URL ONLY', namespace: 'Workspace', source: 'src/features/templates/builder/TemplateBuilderPage.tsx', description: 'Variable-template authoring surface.', area: 'TEMPLATES' },
  { id: 'tpl-builder-id', name: 'Template builder (edit)', route: '/templates/builder/:templateId', type: 'EDITOR', status: 'EXPERIMENTAL', reachability: 'DIRECT URL ONLY', namespace: 'Workspace', source: 'src/features/templates/builder/TemplateBuilderPage.tsx', description: 'Edit an existing authored template.', area: 'TEMPLATES' },

  // ═══ PUBLIC & SHARE ═════════════════════════════════════════════════
  { id: 'pub-landing', name: 'Landing page', route: '/', type: 'PUBLIC PAGE', status: 'CURRENT', reachability: 'NAVIGATION', namespace: 'Public', source: 'src/pages/Index.tsx (domains/landing v1)', description: 'In-app marketing landing (the deployed marketing site is landingpage/, a separate project).', area: 'PUBLIC & SHARE' },
  { id: 'pub-privacy', name: 'Privacy policy', route: '/privacy', type: 'PUBLIC PAGE', status: 'CURRENT', reachability: 'INTERNAL LINK', namespace: 'Public', source: 'src/pages/privacy.tsx', description: 'Legal.', area: 'PUBLIC & SHARE' },
  { id: 'pub-deletion', name: 'Account deletion info', route: '/account-deletion', type: 'PUBLIC PAGE', status: 'CURRENT', reachability: 'INTERNAL LINK', namespace: 'Public', source: 'src/pages/account-deletion.tsx', description: 'Legal/compliance page.', area: 'PUBLIC & SHARE' },
  { id: 'pub-brand', name: 'Public brand page', route: '/brand/:slug', type: 'PUBLIC PAGE', status: 'CURRENT', reachability: 'INTERNAL LINK', namespace: 'Public', source: 'src/pages/brand/ (BrandDetailPage)', description: 'Shared public brand view.', area: 'PUBLIC & SHARE', duplicateGroup: 'public-brand' },
  { id: 'pub-showcase', name: 'Public brand showcase', route: '/brand/:slug/showcase', type: 'PUBLIC PAGE', status: 'CURRENT', reachability: 'INTERNAL LINK', namespace: 'Public', source: 'src/pages/brand/ (BrandShowcasePage)', description: 'Showcase presentation of a shared brand.', area: 'PUBLIC & SHARE', duplicateGroup: 'public-brand' },
  { id: 'pub-bento', name: 'Public bento page', route: '/brand/:slug/bento/:bentoId', type: 'PUBLIC PAGE', status: 'CURRENT', reachability: 'INTERNAL LINK', namespace: 'Public', source: 'src/features/bento/ (PublicBentoPage)', description: 'Shared bento grid.', area: 'PUBLIC & SHARE', duplicateGroup: 'bento' },
  { id: 'pub-identity', name: 'Published brand identity', route: '/i/:token', type: 'PUBLIC PAGE', status: 'CURRENT', reachability: 'DIRECT URL ONLY', namespace: 'Public', source: 'src/pages/i/[token].tsx', description: 'A published Brand Identity snapshot, addressed by share token. Reads one row and carries its own material inlined — no session, no Library, no bucket.', area: 'PUBLIC & SHARE' },
  { id: 'pub-portal', name: 'Brand portal v2', route: '/p/:slug', type: 'PUBLIC PAGE', status: 'CURRENT', reachability: 'INTERNAL LINK', namespace: 'Public', source: 'src/features/brand-portal/v2/BrandPortalV2Page.tsx', description: 'Newer public brand portal — overlaps /brand/:slug (two public-brand generations).', area: 'PUBLIC & SHARE', duplicateGroup: 'public-brand' },
  { id: 'pub-design', name: 'Public design page', route: '/d/:brandSlug/:designSlug', type: 'PUBLIC PAGE', status: 'CURRENT', reachability: 'INTERNAL LINK', namespace: 'Public', source: 'src/pages/d/ (PublicDesignPage)', description: 'Shared single design view.', area: 'PUBLIC & SHARE' },

  // ═══ SETTINGS (workspace) ═══════════════════════════════════════════
  { id: 'set-root', name: 'Settings → account (index)', route: '/settings', type: 'REDIRECT', status: 'REDIRECT', reachability: 'REDIRECT ONLY', namespace: 'Workspace', source: 'src/App.tsx (Navigate)', description: 'Index forwards to /settings/account.', area: 'SETTINGS' },
  { id: 'set-account', name: 'Account settings', route: '/settings/account', type: 'PAGE', status: 'CURRENT', reachability: 'NAVIGATION', namespace: 'Workspace', source: 'src/pages/settings/account.tsx', description: 'Profile + Interface preference (Studio ↔ Classic toggle lives here).', area: 'SETTINGS' },
  { id: 'set-workspace', name: 'Workspace settings', route: '/settings/workspace', type: 'PAGE', status: 'CURRENT', reachability: 'NAVIGATION', namespace: 'Workspace', source: 'src/pages/settings/workspace.tsx', description: 'Workspace name/logo/settings.', area: 'SETTINGS' },
  { id: 'set-members', name: 'Members', route: '/settings/members', type: 'PAGE', status: 'CURRENT', reachability: 'NAVIGATION', namespace: 'Workspace', source: 'src/pages/settings/members.tsx', description: 'Workspace members + roles.', area: 'SETTINGS' },
  { id: 'set-plans', name: 'Plans & billing', route: '/settings/plans', type: 'PAGE', status: 'CURRENT', reachability: 'NAVIGATION', namespace: 'Workspace', source: 'src/pages/settings/plans.tsx', description: 'Subscription plans (Stripe checkout/portal).', area: 'SETTINGS' },

  // ═══ ADMIN (/admin) ═════════════════════════════════════════════════
  { id: 'adm-overview', name: 'Admin overview', route: '/admin', type: 'ADMIN', status: 'CURRENT', reachability: 'NAVIGATION', namespace: 'Admin', source: 'src/features/admin/pages/ (AdminOverview)', description: 'Admin dashboard home.', area: 'ADMIN' },
  { id: 'adm-early', name: 'Early access', route: '/admin/early-access', type: 'ADMIN', status: 'CURRENT', reachability: 'NAVIGATION', namespace: 'Admin', source: 'src/features/admin/pages/AdminEarlyAccess.tsx', description: 'Early-access signups from the landing page.', area: 'ADMIN' },
  { id: 'adm-users', name: 'Users', route: '/admin/users', type: 'ADMIN', status: 'CURRENT', reachability: 'NAVIGATION', namespace: 'Admin', source: 'src/features/admin/pages/ (AdminUsersPage)', description: 'All users admin list.', area: 'ADMIN' },
  { id: 'adm-user-detail', name: 'User detail', route: '/admin/users/:userId', type: 'ADMIN', status: 'CURRENT', reachability: 'INTERNAL LINK', namespace: 'Admin', source: 'src/features/admin/pages/ (AdminUserDetailPage)', description: 'Single-user admin view.', area: 'ADMIN' },
  { id: 'adm-brands', name: 'Brands (admin)', route: '/admin/brands', type: 'ADMIN', status: 'CURRENT', reachability: 'NAVIGATION', namespace: 'Admin', source: 'src/features/admin/pages/AdminBrands.tsx', description: 'All brands admin list (current generation).', area: 'ADMIN', duplicateGroup: 'admin-brands' },
  { id: 'adm-workspaces', name: 'Workspaces (admin)', route: '/admin/workspaces', type: 'ADMIN', status: 'CURRENT', reachability: 'NAVIGATION', namespace: 'Admin', source: 'src/features/admin/pages/ (AdminWorkspacesPage)', description: 'All workspaces admin list.', area: 'ADMIN' },
  { id: 'adm-subs', name: 'Subscriptions (admin)', route: '/admin/subscriptions', type: 'ADMIN', status: 'CURRENT', reachability: 'NAVIGATION', namespace: 'Admin', source: 'src/features/admin/pages/ (AdminSubscriptionsPage)', description: 'Billing/subscriptions overview.', area: 'ADMIN' },
  { id: 'adm-reports', name: 'Reports (admin)', route: '/admin/reports', type: 'ADMIN', status: 'CURRENT', reachability: 'NAVIGATION', namespace: 'Admin', source: 'src/features/admin/pages/ (AdminReportsPage)', description: 'Cross-system reports/metrics.', area: 'ADMIN', duplicateGroup: 'admin-analytics' },
  { id: 'adm-announce', name: 'Announcements (admin)', route: '/admin/announcements', type: 'ADMIN', status: 'CURRENT', reachability: 'NAVIGATION', namespace: 'Admin', source: 'src/features/admin/pages/AdminAnnouncements.tsx', description: 'Platform announcements management.', area: 'ADMIN' },
  { id: 'adm-flags', name: 'Feature flags (admin)', route: '/admin/feature-flags', type: 'ADMIN', status: 'CURRENT', reachability: 'NAVIGATION', namespace: 'Admin', source: 'src/features/admin/pages/AdminFeatureFlags.tsx', description: 'Feature-flag toggles.', area: 'ADMIN' },
  { id: 'adm-activity', name: 'Activity (admin)', route: '/admin/activity', type: 'ADMIN', status: 'CURRENT', reachability: 'NAVIGATION', namespace: 'Admin', source: 'src/features/admin/pages/AdminActivity.tsx', description: 'System-wide activity log.', area: 'ADMIN' },
  { id: 'adm-settings', name: 'Admin settings', route: '/admin/settings', type: 'ADMIN', status: 'CURRENT', reachability: 'NAVIGATION', namespace: 'Admin', source: 'src/features/admin/pages/AdminSettings.tsx', description: 'Platform configuration.', area: 'ADMIN' },
  { id: 'adm-tpl-queue', name: 'Templates approval queue', route: '/admin/templates/queue', type: 'ADMIN', status: 'CURRENT', reachability: 'NAVIGATION', namespace: 'Admin', source: 'src/pages/admin/TemplatesQueuePage.tsx', description: 'Approve/reject community template submissions.', area: 'ADMIN' },

  // ═══ DEV / EXPERIMENTS ══════════════════════════════════════════════
  { id: 'dev-features', name: 'Dev: features inventory', route: '/_dev/features', type: 'DEV TOOL', status: 'DEV', reachability: 'DIRECT URL ONLY', namespace: 'Dev', source: 'src/pages/_dev/features.tsx', description: 'Developer feature catalog (self-gated: DEV or ?dev=1).', area: 'DEV / EXPERIMENTS' },
  { id: 'dev-editor', name: 'Dev: editor playground', route: '/_dev/editor', type: 'DEV TOOL', status: 'DEV', reachability: 'DIRECT URL ONLY', namespace: 'Dev', source: 'src/pages/dev-editor.tsx', description: 'Unified-editor demo with fixture doc (DEV builds only).', area: 'DEV / EXPERIMENTS' },
  { id: 'dev-chronicle', name: 'Dev: chronicle preview', route: '/_dev/chronicle', type: 'DEV TOOL', status: 'DEV', reachability: 'DIRECT URL ONLY', namespace: 'Dev', source: 'src/pages/_dev/chronicle.tsx', description: 'Chronicle editor-chrome preview (DEV builds only).', area: 'DEV / EXPERIMENTS' },
  { id: 'dev-product-map', name: 'Dev: Product Surface Explorer', route: '/_dev/product-map', type: 'DEV TOOL', status: 'DEV', reachability: 'DIRECT URL ONLY', namespace: 'Dev', source: 'src/pages/_dev/product-map.tsx', description: 'THIS tool — inventory + review of every product surface.', area: 'DEV / EXPERIMENTS' },
  { id: 'dev-design-system', name: 'Dev: DS token control center', route: '/_dev/design-system', type: 'DEV TOOL', status: 'DEV', reachability: 'DIRECT URL ONLY', namespace: 'Dev', source: 'src/pages/_dev/design-system/index.tsx', description: 'DS v1 Controller — live --ds-* token editing, diff + save to tokens.json (self-gated: DEV or ?dev=1).', area: 'DEV / EXPERIMENTS' },
  { id: 'dev-architecture', name: 'Dev: Code Navigator', route: '/__architecture', type: 'DEV TOOL', status: 'DEV', reachability: 'DIRECT URL ONLY', namespace: 'Dev', source: 'src/pages/__architecture.tsx', description: 'Engineering-facing route→component→file explorer, generated from the router AST. Sibling to this tool: that one is the product-facing surface review, this one is code orientation. See docs/dev-architecture/README.md.', area: 'DEV / EXPERIMENTS' },
  { id: 'dev-architecture-view', name: 'Dev: Code Navigator (Tree / Search view)', route: '/__architecture/:view', type: 'DEV TOOL', status: 'DEV', reachability: 'DIRECT URL ONLY', namespace: 'Dev', source: 'src/pages/__architecture.tsx', description: 'Direct addressing for the Code Navigator\'s two views — /__architecture/tree and /__architecture/search. Same page component as the entry point above.', area: 'DEV / EXPERIMENTS' },
  { id: 'not-found', name: '404 Not Found', route: '/*', type: 'PAGE', status: 'CURRENT', reachability: 'DIRECT URL ONLY', namespace: 'Shared', source: 'src/pages/NotFound.tsx', description: 'Catch-all.', area: 'PUBLIC & SHARE' },

  // ═══ NON-ROUTE SURFACES — BRAND KIT ═════════════════════════════════
  { id: 'bk-sec-assets', name: 'Brand Kit § Brand Assets', route: null, entryHint: '/b/:slug/brand-kit', type: 'TAB', status: 'CURRENT', reachability: 'INTERNAL LINK', namespace: 'Studio', source: 'src/features/brand-kit/BrandKitCosmosPage.tsx', description: 'Logos · Colors · Fonts · Icons · Photos · About cards with variant grids + downloads.', area: 'BRAND KIT' },
  { id: 'bk-sec-stationery', name: 'Brand Kit § Stationery', route: null, entryHint: '/b/:slug/brand-kit', type: 'TAB', status: 'CURRENT', reachability: 'INTERNAL LINK', namespace: 'Studio', source: 'src/features/brand-kit/BrandKitCosmosPage.tsx', description: 'Business Card · Letterhead · Envelope · Invoice tiles.', area: 'BRAND KIT' },
  { id: 'bk-sec-social', name: 'Brand Kit § Social Media', route: null, entryHint: '/b/:slug/brand-kit', type: 'TAB', status: 'CURRENT', reachability: 'INTERNAL LINK', namespace: 'Studio', source: 'src/features/brand-kit/BrandKitCosmosPage.tsx', description: 'Profile · Cover · Post · Story tiles.', area: 'BRAND KIT' },
  { id: 'bk-sec-web', name: 'Brand Kit § Web', route: null, entryHint: '/b/:slug/brand-kit', type: 'TAB', status: 'DEFERRED', reachability: 'INTERNAL LINK', namespace: 'Studio', source: 'src/features/brand-kit/BrandKitCosmosPage.tsx', description: 'Favicon · Website · Email signature · Landing — cosmos-only stubs (no renderer yet).', area: 'BRAND KIT' },
  { id: 'bk-sec-guides', name: 'Brand Kit § Brand Guides', route: null, entryHint: '/b/:slug/brand-kit', type: 'TAB', status: 'CURRENT', reachability: 'INTERNAL LINK', namespace: 'Studio', source: 'src/features/brand-kit/BrandKitCosmosPage.tsx', description: 'Logo · Color · Typography · Voice · Imagery guide tiles.', area: 'BRAND KIT' },
  { id: 'bk-sec-presentations', name: 'Brand Kit § Presentations', route: null, entryHint: '/b/:slug/brand-kit', type: 'TAB', status: 'CURRENT', reachability: 'INTERNAL LINK', namespace: 'Studio', source: 'src/features/brand-kit/BrandKitCosmosPage.tsx', description: 'Pitch Deck · Business Plan · Proposal · Case Studies tiles.', area: 'BRAND KIT' },
  { id: 'bk-sec-animations', name: 'Brand Kit § Animations', route: null, entryHint: '/b/:slug/brand-kit', type: 'TAB', status: 'CURRENT', reachability: 'INTERNAL LINK', namespace: 'Studio', source: 'src/features/brand-kit/BrandKitCosmosPage.tsx', description: 'Logo Reveal · Slide In · Fade · Rotate animated tiles.', area: 'BRAND KIT' },
  { id: 'bk-card-editor', name: 'Brand Kit card editor', route: null, entryHint: 'Brand Kit → right-click a card → Edit', type: 'EDITOR', status: 'CURRENT', reachability: 'INTERNAL LINK', namespace: 'Studio', source: 'src/features/brand-kit/BrandKitCardEditor.tsx', description: 'Full-page card editor overlay with live preview (save is toast-only today — known debt).', area: 'BRAND KIT' },

  // ═══ NON-ROUTE SURFACES — DIALOGS / PANELS / DRAWERS ════════════════
  { id: 'dlg-brand-settings', name: 'Brand Settings dialog', route: null, entryHint: 'Identity → Edit buttons / brand menus', type: 'MODAL', status: 'CURRENT', reachability: 'INTERNAL LINK', namespace: 'Shared', source: 'src/shared/brand-settings/BrandSettingsDialog.tsx', description: 'Tabbed identity editor: General · Logo · Colors · Typography · Voice · Strategy — all writes go through canonical identity ops.', area: 'SETUP & IDENTITY' },
  { id: 'dlg-brand-chooser', name: 'Brand chooser dialog', route: null, entryHint: 'Templates page / editor launcher', type: 'MODAL', status: 'CURRENT', reachability: 'INTERNAL LINK', namespace: 'Shared', source: 'src/features/brand/components/BrandChooserDialog.tsx', description: 'Pick which brand to act on; supports "start without brand" + "create new".', area: 'DASHBOARD' },
  { id: 'dlg-asset-source', name: 'Asset source popover', route: null, entryHint: 'Any brand-image slot (logo panels, etc.)', type: 'MODAL', status: 'CURRENT', reachability: 'INTERNAL LINK', namespace: 'Shared', source: 'src/shared/upload/AssetSourcePopover.tsx', description: 'Canonical "upload or pick from brand assets" surface (server-backed library).', area: 'ASSETS' },
  { id: 'dlg-asset-picker', name: 'Asset picker modal', route: null, entryHint: 'Editor → replace image / insert from assets', type: 'MODAL', status: 'CURRENT', reachability: 'INTERNAL LINK', namespace: 'Shared', source: 'src/shared/upload/AssetPicker.tsx', description: 'Asset library modal used by editor inspectors (server-backed library).', area: 'ASSETS' },
  { id: 'drw-assistant', name: 'Brand Assistant drawer', route: null, entryHint: '⌘J anywhere in-app', type: 'MODAL', status: 'CURRENT', reachability: 'INTERNAL LINK', namespace: 'Shared', source: 'src/features/ai/v5/BrandAssistantDrawer.tsx', description: 'App-wide AI assistant (Claude via anthropic-proxy) grounded in the active brand.', area: 'DESIGN & EDITORS' },
  { id: 'pnl-editor-templates', name: 'Editor § Templates panel', route: null, entryHint: 'Unified editor left rail', type: 'TAB', status: 'CURRENT', reachability: 'INTERNAL LINK', namespace: 'Studio', source: 'src/features/editor/shell/v2/panels/TemplatesPanel.tsx', description: 'Category-filtered template browser + My Designs + AI prompt presets inside the editor.', area: 'DESIGN & EDITORS' },
  { id: 'pnl-editor-generate', name: 'Editor § AI generate', route: null, entryHint: 'Unified editor — prompt bar / generate panel', type: 'TAB', status: 'CURRENT', reachability: 'INTERNAL LINK', namespace: 'Studio', source: 'src/features/editor/ai/ (applyCommand, generateImage)', description: 'AI doc mutation + image generation via Edge Functions.', area: 'DESIGN & EDITORS' },
  { id: 'pnl-editor-insert', name: 'Editor § Insert panel', route: null, entryHint: 'Unified editor left rail', type: 'TAB', status: 'CURRENT', reachability: 'INTERNAL LINK', namespace: 'Studio', source: 'src/features/editor/shell/v2/panels/InsertPanel.tsx', description: 'Insert text/shapes/images (brand-asset wiring pending).', area: 'DESIGN & EDITORS' },
  { id: 'pnl-save-as-template', name: 'Save as template popover', route: null, entryHint: 'Unified editor top chrome', type: 'MODAL', status: 'CURRENT', reachability: 'INTERNAL LINK', namespace: 'Studio', source: 'src/features/editor/shell/v2/EditorSaveAsTemplateButton.tsx', description: 'Converts the current doc into a reusable brand-agnostic template (private or community-pending).', area: 'TEMPLATES' },
  { id: 'pnl-editor-brand', name: 'Editor § Brand panel', route: null, entryHint: 'Unified editor left rail (4th panel)', type: 'TAB', status: 'CURRENT', reachability: 'INTERNAL LINK', namespace: 'Studio', source: 'src/features/editor/shell/v2/panels/BrandPanel.tsx', description: 'Page dimensions/background + applied-brand status/re-apply + collapsed Logo/Color/Typography summary.', area: 'DESIGN & EDITORS' },
  { id: 'dlg-export', name: 'Export dialog (universal)', route: null, entryHint: 'Editor/Social/Brand Kit → Export', type: 'MODAL', status: 'CURRENT', reachability: 'INTERNAL LINK', namespace: 'Shared', source: 'src/shared/components/ExportDialog.tsx', description: 'The shared export surface — format grid, resolution/quality, progress. Used by Social Designer, editor top bar, Brand Kit animations, legacy editor.', area: 'DESIGN & EDITORS' },
  { id: 'dlg-export-presentation', name: 'Presentation export modal', route: null, entryHint: 'Presentations → Export', type: 'MODAL', status: 'CURRENT', reachability: 'INTERNAL LINK', namespace: 'Shared', source: 'src/shared/editor/ExportModal.tsx', description: 'Deck-specific export incl. editable-PDF (the frozen editable-export-v1 pipeline).', area: 'PRESENTATIONS & DECKS' },
  { id: 'pnl-presentation-panels', name: 'Presentation editor panels', route: null, entryHint: 'Presentations editor — Theme · Background · Insert · Remix', type: 'TAB', status: 'CURRENT', reachability: 'INTERNAL LINK', namespace: 'Shared', source: 'src/shared/editor/EditorWorkspace.tsx (+ ThemeDrawer)', description: 'The v1 deck engine panel system (theme/background/insert/export/remix).', area: 'PRESENTATIONS & DECKS' },
  { id: 'mode-present', name: 'Present mode (fullscreen)', route: null, entryHint: 'Presentations → Present', type: 'TAB', status: 'CURRENT', reachability: 'INTERNAL LINK', namespace: 'Shared', source: 'src/shared/editor/EditorWorkspace.tsx (presentMode)', description: 'Fullscreen presenting state for decks.', area: 'PRESENTATIONS & DECKS' },
  { id: 'dlg-auth', name: 'Auth modal', route: null, entryHint: 'Navbar / landing — Sign in', type: 'MODAL', status: 'CURRENT', reachability: 'INTERNAL LINK', namespace: 'Public', source: 'src/features/auth/components/AuthModal.tsx', description: 'In-app sign-in/sign-up modal — the non-route half of auth (seeds the session store before navigating).', area: 'AUTH' },
  { id: 'dlg-tool-gate', name: 'Tool signup gate', route: null, entryHint: 'Public tools → gated action', type: 'MODAL', status: 'CURRENT', reachability: 'INTERNAL LINK', namespace: 'Public', source: 'src/features/tools/core/ToolGate.tsx', description: 'The universal "needs an account" gate — governs the public-tool → signup → claim funnel.', area: 'TOOLS' },
  { id: 'dlg-setup-upload', name: 'Setup upload modal', route: null, entryHint: '/b/:slug/setup → Upload', type: 'MODAL', status: 'CURRENT', reachability: 'INTERNAL LINK', namespace: 'Studio', source: 'src/features/setup/components/UploadModal.tsx', description: 'Multi-kind ingest (logos/photos/FONTS) committed to the brand — the only font-file ingestion path.', area: 'SETUP & IDENTITY' },
  { id: 'dlg-bk-download', name: 'Brand Kit download + bulk export', route: null, entryHint: 'Classic Brand Kit → Download buttons', type: 'MODAL', status: 'LEGACY', reachability: 'INTERNAL LINK', namespace: 'Classic', source: 'src/features/brand-kit-alt/DownloadDialog.tsx (+ bulkExport.ts)', description: 'Per-asset format/size download + whole-kit ZIP — exists only in the Classic fork.', area: 'BRAND KIT' },
  { id: 'dlg-typescale-embedded', name: 'Embedded Typescale dialog', route: null, entryHint: 'Setup → fonts → typescale', type: 'MODAL', status: 'CURRENT', reachability: 'INTERNAL LINK', namespace: 'Studio', source: 'src/features/tools/typescale/EmbeddedTypescaleDialog.tsx', description: 'The Typescale tool re-hosted as a modal inside Setup.', area: 'SETUP & IDENTITY', duplicateGroup: 'tool-typescale' },
  { id: 'dlg-early-access', name: 'Early access dialog', route: null, entryHint: 'Landing page CTA', type: 'MODAL', status: 'CURRENT', reachability: 'INTERNAL LINK', namespace: 'Public', source: 'src/domains/landing/components/EarlyAccessDialog.tsx', description: 'Waitlist capture — feeds /admin/early-access.', area: 'PUBLIC & SHARE' },
];

/** Areas in display order. */
export const AREA_ORDER: SurfaceEntry['area'][] = [
  'AUTH', 'DASHBOARD', 'ONBOARDING', 'BRAND (STUDIO)', 'BRAND (CLASSIC)',
  'BRAND KIT', 'SETUP & IDENTITY', 'GUIDELINES', 'DESIGN & EDITORS',
  'PRESENTATIONS & DECKS', 'ASSETS', 'TOOLS', 'TEMPLATES', 'LOGO MAKER',
  'PUBLIC & SHARE', 'SETTINGS', 'ADMIN', 'DEV / EXPERIMENTS',
];
