import type { Typescale } from '@/shared/types/typescale';

export function serializeJs(t: Typescale): string {
  const body = JSON.stringify(t, null, 2);
  return `// Generated by BrandOS Typescale. Paste into a .ts file.
export const typescale = ${body} as const;`;
}
