import { supabase } from '@/integrations/supabase/client';
import type { Brand, CreateBrandInput } from '@/shared/types/brand';
import type { IBrandsService } from '@/core/types/services';

export class SupabaseBrandsService implements IBrandsService {
  async list(workspaceId?: string): Promise<Brand[]> {
    let query = supabase
      .from('brands')
      .select('*')
      .order('created_at', { ascending: false });

    // RLS already scopes to workspace membership, but we can further filter
    if (workspaceId) {
      query = query.eq('workspace_id', workspaceId);
    }

    const { data, error } = await query;
    if (error) throw error;
    return (data ?? []).map(this.mapFromDatabase);
  }

  async getById(id: string): Promise<Brand | null> {
    const { data, error } = await supabase
      .from('brands')
      .select('*')
      .eq('id', id)
      .maybeSingle();

    if (error) throw error;
    return data ? this.mapFromDatabase(data) : null;
  }

  async getBySlug(slug: string): Promise<Brand | null> {
    const { data, error } = await supabase
      .from('brands')
      .select('*')
      .eq('slug', slug)
      .maybeSingle();

    if (error) throw error;
    return data ? this.mapFromDatabase(data) : null;
  }

  async create(input: CreateBrandInput): Promise<Brand> {
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) throw new Error('User not authenticated');

    const brandData: Record<string, unknown> = {
      user_id: user.id,
      name: input.name,
      logo_url: input.logo,
      primary_color: input.primaryColor,
      secondary_color: input.secondaryColor,
      fonts: input.fonts,
      tone: input.tone,
      audience: input.audience,
    };

    // Slug is auto-generated by DB trigger if not provided
    if (input.slug) brandData.slug = input.slug;
    if (input.workspaceId) brandData.workspace_id = input.workspaceId;

    const { data, error } = await supabase
      .from('brands')
      .insert(brandData)
      .select()
      .single();

    if (error) throw error;
    return this.mapFromDatabase(data);
  }

  async update(id: string, patch: Partial<Brand>): Promise<Brand> {
    const updateData: Record<string, unknown> = {};

    if (patch.name !== undefined) updateData.name = patch.name;
    if (patch.logo !== undefined) updateData.logo_url = patch.logo;
    if (patch.logoAssets !== undefined) updateData.logo_assets = patch.logoAssets;
    if (patch.primaryColor !== undefined) updateData.primary_color = patch.primaryColor;
    if (patch.secondaryColor !== undefined) updateData.secondary_color = patch.secondaryColor;
    if (patch.fonts !== undefined) updateData.fonts = patch.fonts;
    if (patch.tone !== undefined) updateData.tone = patch.tone;
    if (patch.audience !== undefined) updateData.audience = patch.audience;
    if (patch.strategy !== undefined) updateData.strategy = patch.strategy;
    if (patch.guidelines !== undefined) updateData.guidelines = patch.guidelines;
    if (patch.isPublic !== undefined) updateData.is_public = patch.isPublic;
    if (patch.publicUrl !== undefined) updateData.public_url = patch.publicUrl;
    if (patch.customDomain !== undefined) updateData.custom_domain = patch.customDomain;

    const { data, error } = await supabase
      .from('brands')
      .update(updateData)
      .eq('id', id)
      .select()
      .single();

    if (error) throw error;
    return this.mapFromDatabase(data);
  }

  async delete(id: string): Promise<void> {
    const { error } = await supabase
      .from('brands')
      .delete()
      .eq('id', id);

    if (error) throw error;
  }

  private mapFromDatabase(data: any): Brand {
    return {
      id: data.id,
      slug: data.slug,
      name: data.name,
      logo: data.logo_url,
      logoAssets: data.logo_assets || undefined,
      primaryColor: data.primary_color,
      secondaryColor: data.secondary_color,
      fonts: data.fonts || { primary: 'Inter' },
      tone: data.tone || '',
      audience: data.audience || '',
      strategy: data.strategy || undefined,
      guidelines: data.guidelines || undefined,
      isPublic: data.is_public || false,
      publicUrl: data.public_url || undefined,
      customDomain: data.custom_domain || undefined,
      assets: [], // Loaded separately via IAssetsService
      createdAt: new Date(data.created_at),
      updatedAt: new Date(data.updated_at),
    };
  }
}
