/**
 * IR → SVG markup
 *
 * Pure synchronous emitter (apart from optional vector-image inlining,
 * which is async because it has to fetch the source SVG markup). Output is
 * a real, editable SVG that opens in Illustrator with selectable text and
 * shapes.
 */

import type { VectorIR, RectNode, TextNode, ImageNode, RasterFallbackNode } from './types';
import { firstFontFamily } from './cssParse';

export interface IrToSvgOptions {
  /** If true, attempts to fetch and inline SVG-source images as native vector groups. */
  inlineVectorImages?: boolean;
}

export async function irToSvg(ir: VectorIR, opts: IrToSvgOptions = {}): Promise<string> {
  const parts: string[] = [];

  parts.push('<?xml version="1.0" encoding="UTF-8"?>');
  parts.push('<!-- Generated by BrandOS — editable vector export -->');
  parts.push(
    `<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" ` +
      `viewBox="0 0 ${ir.width} ${ir.height}" width="${ir.width}" height="${ir.height}">`,
  );

  if (ir.background) {
    parts.push(`<rect width="${ir.width}" height="${ir.height}" fill="${ir.background}"/>`);
  }

  for (const node of ir.nodes) {
    switch (node.type) {
      case 'rect':
        parts.push(emitRect(node));
        break;
      case 'text':
        parts.push(emitText(node));
        break;
      case 'image':
        parts.push(await emitImage(node, opts));
        break;
      case 'raster-fallback':
        parts.push(emitRasterFallback(node));
        break;
    }
  }

  parts.push('</svg>');
  return parts.join('\n');
}

// ── Emitters ────────────────────────────────────────────────

function emitRect(n: RectNode): string {
  const attrs: string[] = [
    `x="${fmt(n.x)}"`,
    `y="${fmt(n.y)}"`,
    `width="${fmt(n.w)}"`,
    `height="${fmt(n.h)}"`,
  ];
  if (n.rx) attrs.push(`rx="${fmt(n.rx)}"`, `ry="${fmt(n.rx)}"`);
  if (n.fill) attrs.push(`fill="${n.fill}"`);
  else attrs.push('fill="none"');
  if (n.stroke) attrs.push(`stroke="${n.stroke}"`);
  if (n.strokeWidth) attrs.push(`stroke-width="${fmt(n.strokeWidth)}"`);
  if (n.opacity !== undefined && n.opacity < 1) attrs.push(`opacity="${fmt(n.opacity)}"`);
  return `<rect ${attrs.join(' ')}/>`;
}

function emitText(n: TextNode): string {
  const family = firstFontFamily(n.fontFamily);
  const anchor = n.align === 'center' ? 'middle' : n.align === 'right' ? 'end' : 'start';
  const anchorX = n.align === 'center' ? n.x + n.w / 2 : n.align === 'right' ? n.x + n.w : n.x;
  // SVG text y is the baseline; approximate baseline as top + 0.8*fontSize
  const baseline = n.y + n.fontSize * 0.85;

  const tspans = n.lines
    .map((line, i) => {
      const dy = i === 0 ? 0 : n.lineHeight;
      return `<tspan x="${fmt(anchorX)}" dy="${fmt(dy)}">${escapeXml(line)}</tspan>`;
    })
    .join('');

  const attrs = [
    `x="${fmt(anchorX)}"`,
    `y="${fmt(baseline)}"`,
    `font-family="${escapeAttr(family)}"`,
    `font-size="${fmt(n.fontSize)}"`,
    `font-weight="${n.fontWeight}"`,
    `fill="${n.color}"`,
    `text-anchor="${anchor}"`,
  ];
  if (n.fontStyle === 'italic') attrs.push('font-style="italic"');
  if (n.letterSpacing) attrs.push(`letter-spacing="${fmt(n.letterSpacing)}"`);

  return `<text ${attrs.join(' ')}>${tspans}</text>`;
}

async function emitImage(n: ImageNode, opts: IrToSvgOptions): Promise<string> {
  // Try to inline SVG sources as native vector
  if (n.isVectorSource && opts.inlineVectorImages !== false) {
    try {
      const inlined = await inlineSvg(n);
      if (inlined) return inlined;
    } catch (err) {
      console.warn('[vector-export] inline SVG failed, falling back to <image>', err);
    }
  }

  return emitImageHref(n);
}

function emitImageHref(n: ImageNode): string {
  const attrs = [
    `x="${fmt(n.x)}"`,
    `y="${fmt(n.y)}"`,
    `width="${fmt(n.w)}"`,
    `height="${fmt(n.h)}"`,
    `xlink:href="${escapeAttr(n.src)}"`,
    `href="${escapeAttr(n.src)}"`,
    `preserveAspectRatio="${objectFitToPreserve(n.objectFit)}"`,
  ];
  if (n.filter) attrs.push(`style="filter: ${escapeAttr(n.filter)}"`);
  return `<image ${attrs.join(' ')}/>`;
}

function emitRasterFallback(n: RasterFallbackNode): string {
  return (
    `<image x="${fmt(n.x)}" y="${fmt(n.y)}" width="${fmt(n.w)}" height="${fmt(n.h)}" ` +
    `xlink:href="${escapeAttr(n.pngDataUrl)}" href="${escapeAttr(n.pngDataUrl)}"/>`
  );
}

// ── SVG inlining ────────────────────────────────────────────

async function inlineSvg(n: ImageNode): Promise<string | null> {
  let svgText: string;

  if (n.src.startsWith('data:image/svg')) {
    // data:image/svg+xml;base64,... or data:image/svg+xml;utf8,...
    const comma = n.src.indexOf(',');
    if (comma === -1) return null;
    const meta = n.src.substring(0, comma);
    const data = n.src.substring(comma + 1);
    svgText = meta.includes('base64') ? atob(data) : decodeURIComponent(data);
  } else {
    const res = await fetch(n.src);
    if (!res.ok) return null;
    svgText = await res.text();
  }

  // Parse the SVG and grab its inner contents + viewBox
  const doc = new DOMParser().parseFromString(svgText, 'image/svg+xml');
  const svgEl = doc.querySelector('svg');
  if (!svgEl) return null;

  // Compute scale from viewBox → target size
  const vb = svgEl.getAttribute('viewBox')?.split(/[\s,]+/).map(Number);
  let vbW = vb && vb.length === 4 ? vb[2] : parseFloat(svgEl.getAttribute('width') || '0') || n.w;
  let vbH = vb && vb.length === 4 ? vb[3] : parseFloat(svgEl.getAttribute('height') || '0') || n.h;
  if (!vbW || !vbH) {
    vbW = n.w;
    vbH = n.h;
  }

  const sx = n.w / vbW;
  const sy = n.h / vbH;

  // For object-fit: contain — use uniform scale
  const fit = n.objectFit ?? 'fill';
  let scaleX = sx;
  let scaleY = sy;
  let offX = 0;
  let offY = 0;
  if (fit === 'contain' || fit === 'cover') {
    const uniform = fit === 'contain' ? Math.min(sx, sy) : Math.max(sx, sy);
    scaleX = uniform;
    scaleY = uniform;
    offX = (n.w - vbW * uniform) / 2;
    offY = (n.h - vbH * uniform) / 2;
  }

  // Strip outer <svg> tag and emit children inside a <g> with transform
  const inner = Array.from(svgEl.childNodes)
    .map((c) => (c as Element).outerHTML ?? c.textContent ?? '')
    .join('');

  const filterStyle = n.filter ? ` style="filter: ${escapeAttr(n.filter)}"` : '';
  return `<g transform="translate(${fmt(n.x + offX)} ${fmt(n.y + offY)}) scale(${fmt(scaleX)} ${fmt(scaleY)})"${filterStyle}>${inner}</g>`;
}

// ── Utils ───────────────────────────────────────────────────

function fmt(n: number): string {
  // 3 decimal places, drop trailing zeros
  return Number(n.toFixed(3)).toString();
}

function escapeXml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

function escapeAttr(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/"/g, '&quot;');
}

function objectFitToPreserve(fit: ImageNode['objectFit']): string {
  switch (fit) {
    case 'contain': return 'xMidYMid meet';
    case 'cover': return 'xMidYMid slice';
    case 'none': return 'xMidYMid';
    case 'fill':
    default: return 'none';
  }
}
